version: 1
backfiller:
  sources:
    dpp:
      format: html
      base_url: https://www.dpp.org.tw
      pager:
        type: "index"
        mode: "index"
        url_template: "{{.BaseURL}}/media/{{printf \"%02d\" .Value}}"
        first: 0
        step: 10

    tpp:
      format: html
      base_url: https://www.tpp.org.tw
      pager:
        type: "index"
        mode: "index"
        url_template: "{{.BaseURL}}/media"
        first: 1
        step: 1
        params:
          page: "{{.Value}}"

    kmt:
      format: atom
      base_url: https://www.kmt.org.tw
      pager:
        type: "index"
        mode: "index"
        url_template: "{{.BaseURL}}/feeds/posts/summary/-/新聞稿"
        first: 1
        step: 10
        params:
          start-index: "{{.Value}}"
          max-results: "10"

    pts:
      format: atom
      base_url: https://news.pts.org.tw
      pager:
        type: "index"
        mode: "index"
        url_template: "{{.BaseURL}}/xml/newsfeed.xml"
        first: 1
        step: 1

    cna:
      format: rss
      base_url: https://feeds.feedburner.com
      pager:
        type: "index"
        mode: "index"
        url_template: "{{.BaseURL}}/rsscna/politics"
        first: 1
        step: 1
