// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ChiaYuChang/prism/internal/repo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Analysis provides a mock function for the type MockRepository
func (_mock *MockRepository) Analysis() repo.Analysis {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Analysis")
	}

	var r0 repo.Analysis
	if returnFunc, ok := ret.Get(0).(func() repo.Analysis); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Analysis)
		}
	}
	return r0
}

// MockRepository_Analysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Analysis'
type MockRepository_Analysis_Call struct {
	*mock.Call
}

// Analysis is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Analysis() *MockRepository_Analysis_Call {
	return &MockRepository_Analysis_Call{Call: _e.mock.On("Analysis")}
}

func (_c *MockRepository_Analysis_Call) Run(run func()) *MockRepository_Analysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Analysis_Call) Return(analysis repo.Analysis) *MockRepository_Analysis_Call {
	_c.Call.Return(analysis)
	return _c
}

func (_c *MockRepository_Analysis_Call) RunAndReturn(run func() repo.Analysis) *MockRepository_Analysis_Call {
	_c.Call.Return(run)
	return _c
}

// Embedding provides a mock function for the type MockRepository
func (_mock *MockRepository) Embedding() repo.Embeddings {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Embedding")
	}

	var r0 repo.Embeddings
	if returnFunc, ok := ret.Get(0).(func() repo.Embeddings); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Embeddings)
		}
	}
	return r0
}

// MockRepository_Embedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embedding'
type MockRepository_Embedding_Call struct {
	*mock.Call
}

// Embedding is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Embedding() *MockRepository_Embedding_Call {
	return &MockRepository_Embedding_Call{Call: _e.mock.On("Embedding")}
}

func (_c *MockRepository_Embedding_Call) Run(run func()) *MockRepository_Embedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Embedding_Call) Return(embeddings repo.Embeddings) *MockRepository_Embedding_Call {
	_c.Call.Return(embeddings)
	return _c
}

func (_c *MockRepository_Embedding_Call) RunAndReturn(run func() repo.Embeddings) *MockRepository_Embedding_Call {
	_c.Call.Return(run)
	return _c
}

// Pipeline provides a mock function for the type MockRepository
func (_mock *MockRepository) Pipeline() repo.Pipeline {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pipeline")
	}

	var r0 repo.Pipeline
	if returnFunc, ok := ret.Get(0).(func() repo.Pipeline); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Pipeline)
		}
	}
	return r0
}

// MockRepository_Pipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pipeline'
type MockRepository_Pipeline_Call struct {
	*mock.Call
}

// Pipeline is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Pipeline() *MockRepository_Pipeline_Call {
	return &MockRepository_Pipeline_Call{Call: _e.mock.On("Pipeline")}
}

func (_c *MockRepository_Pipeline_Call) Run(run func()) *MockRepository_Pipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Pipeline_Call) Return(pipeline repo.Pipeline) *MockRepository_Pipeline_Call {
	_c.Call.Return(pipeline)
	return _c
}

func (_c *MockRepository_Pipeline_Call) RunAndReturn(run func() repo.Pipeline) *MockRepository_Pipeline_Call {
	_c.Call.Return(run)
	return _c
}

// Scheduler provides a mock function for the type MockRepository
func (_mock *MockRepository) Scheduler() repo.Scheduler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Scheduler")
	}

	var r0 repo.Scheduler
	if returnFunc, ok := ret.Get(0).(func() repo.Scheduler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Scheduler)
		}
	}
	return r0
}

// MockRepository_Scheduler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scheduler'
type MockRepository_Scheduler_Call struct {
	*mock.Call
}

// Scheduler is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Scheduler() *MockRepository_Scheduler_Call {
	return &MockRepository_Scheduler_Call{Call: _e.mock.On("Scheduler")}
}

func (_c *MockRepository_Scheduler_Call) Run(run func()) *MockRepository_Scheduler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Scheduler_Call) Return(scheduler repo.Scheduler) *MockRepository_Scheduler_Call {
	_c.Call.Return(scheduler)
	return _c
}

func (_c *MockRepository_Scheduler_Call) RunAndReturn(run func() repo.Scheduler) *MockRepository_Scheduler_Call {
	_c.Call.Return(run)
	return _c
}

// Scout provides a mock function for the type MockRepository
func (_mock *MockRepository) Scout() repo.Scout {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Scout")
	}

	var r0 repo.Scout
	if returnFunc, ok := ret.Get(0).(func() repo.Scout); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Scout)
		}
	}
	return r0
}

// MockRepository_Scout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scout'
type MockRepository_Scout_Call struct {
	*mock.Call
}

// Scout is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Scout() *MockRepository_Scout_Call {
	return &MockRepository_Scout_Call{Call: _e.mock.On("Scout")}
}

func (_c *MockRepository_Scout_Call) Run(run func()) *MockRepository_Scout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Scout_Call) Return(scout repo.Scout) *MockRepository_Scout_Call {
	_c.Call.Return(scout)
	return _c
}

func (_c *MockRepository_Scout_Call) RunAndReturn(run func() repo.Scout) *MockRepository_Scout_Call {
	_c.Call.Return(run)
	return _c
}

// Tasks provides a mock function for the type MockRepository
func (_mock *MockRepository) Tasks() repo.Tasks {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tasks")
	}

	var r0 repo.Tasks
	if returnFunc, ok := ret.Get(0).(func() repo.Tasks); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Tasks)
		}
	}
	return r0
}

// MockRepository_Tasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tasks'
type MockRepository_Tasks_Call struct {
	*mock.Call
}

// Tasks is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Tasks() *MockRepository_Tasks_Call {
	return &MockRepository_Tasks_Call{Call: _e.mock.On("Tasks")}
}

func (_c *MockRepository_Tasks_Call) Run(run func()) *MockRepository_Tasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Tasks_Call) Return(tasks repo.Tasks) *MockRepository_Tasks_Call {
	_c.Call.Return(tasks)
	return _c
}

func (_c *MockRepository_Tasks_Call) RunAndReturn(run func() repo.Tasks) *MockRepository_Tasks_Call {
	_c.Call.Return(run)
	return _c
}
