// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/repo"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTasks creates a new instance of MockTasks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTasks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTasks {
	mock := &MockTasks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTasks is an autogenerated mock type for the Tasks type
type MockTasks struct {
	mock.Mock
}

type MockTasks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTasks) EXPECT() *MockTasks_Expecter {
	return &MockTasks_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function for the type MockTasks
func (_mock *MockTasks) CreateTask(ctx context.Context, arg repo.CreateTaskParams) (repo.Task, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 repo.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateTaskParams) (repo.Task, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateTaskParams) repo.Task); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.CreateTaskParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasks_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTasks_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.CreateTaskParams
func (_e *MockTasks_Expecter) CreateTask(ctx interface{}, arg interface{}) *MockTasks_CreateTask_Call {
	return &MockTasks_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, arg)}
}

func (_c *MockTasks_CreateTask_Call) Run(run func(ctx context.Context, arg repo.CreateTaskParams)) *MockTasks_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.CreateTaskParams
		if args[1] != nil {
			arg1 = args[1].(repo.CreateTaskParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_CreateTask_Call) Return(task repo.Task, err error) *MockTasks_CreateTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTasks_CreateTask_Call) RunAndReturn(run func(ctx context.Context, arg repo.CreateTaskParams) (repo.Task, error)) *MockTasks_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByID provides a mock function for the type MockTasks
func (_mock *MockTasks) GetTaskByID(ctx context.Context, id uuid.UUID) (repo.Task, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 repo.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repo.Task, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repo.Task); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repo.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasks_GetTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByID'
type MockTasks_GetTaskByID_Call struct {
	*mock.Call
}

// GetTaskByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTasks_Expecter) GetTaskByID(ctx interface{}, id interface{}) *MockTasks_GetTaskByID_Call {
	return &MockTasks_GetTaskByID_Call{Call: _e.mock.On("GetTaskByID", ctx, id)}
}

func (_c *MockTasks_GetTaskByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTasks_GetTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_GetTaskByID_Call) Return(task repo.Task, err error) *MockTasks_GetTaskByID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTasks_GetTaskByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (repo.Task, error)) *MockTasks_GetTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasksByBatchID provides a mock function for the type MockTasks
func (_mock *MockTasks) ListTasksByBatchID(ctx context.Context, batchID uuid.UUID) ([]repo.Task, error) {
	ret := _mock.Called(ctx, batchID)

	if len(ret) == 0 {
		panic("no return value specified for ListTasksByBatchID")
	}

	var r0 []repo.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repo.Task, error)); ok {
		return returnFunc(ctx, batchID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repo.Task); ok {
		r0 = returnFunc(ctx, batchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, batchID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasks_ListTasksByBatchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasksByBatchID'
type MockTasks_ListTasksByBatchID_Call struct {
	*mock.Call
}

// ListTasksByBatchID is a helper method to define mock.On call
//   - ctx context.Context
//   - batchID uuid.UUID
func (_e *MockTasks_Expecter) ListTasksByBatchID(ctx interface{}, batchID interface{}) *MockTasks_ListTasksByBatchID_Call {
	return &MockTasks_ListTasksByBatchID_Call{Call: _e.mock.On("ListTasksByBatchID", ctx, batchID)}
}

func (_c *MockTasks_ListTasksByBatchID_Call) Run(run func(ctx context.Context, batchID uuid.UUID)) *MockTasks_ListTasksByBatchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_ListTasksByBatchID_Call) Return(tasks []repo.Task, err error) *MockTasks_ListTasksByBatchID_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTasks_ListTasksByBatchID_Call) RunAndReturn(run func(ctx context.Context, batchID uuid.UUID) ([]repo.Task, error)) *MockTasks_ListTasksByBatchID_Call {
	_c.Call.Return(run)
	return _c
}
