// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/repo"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduler creates a new instance of MockScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduler {
	mock := &MockScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduler is an autogenerated mock type for the Scheduler type
type MockScheduler struct {
	mock.Mock
}

type MockScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduler) EXPECT() *MockScheduler_Expecter {
	return &MockScheduler_Expecter{mock: &_m.Mock}
}

// ClaimTasks provides a mock function for the type MockScheduler
func (_mock *MockScheduler) ClaimTasks(ctx context.Context, limit int32) ([]repo.Task, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimTasks")
	}

	var r0 []repo.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]repo.Task, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []repo.Task); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduler_ClaimTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimTasks'
type MockScheduler_ClaimTasks_Call struct {
	*mock.Call
}

// ClaimTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
func (_e *MockScheduler_Expecter) ClaimTasks(ctx interface{}, limit interface{}) *MockScheduler_ClaimTasks_Call {
	return &MockScheduler_ClaimTasks_Call{Call: _e.mock.On("ClaimTasks", ctx, limit)}
}

func (_c *MockScheduler_ClaimTasks_Call) Run(run func(ctx context.Context, limit int32)) *MockScheduler_ClaimTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduler_ClaimTasks_Call) Return(tasks []repo.Task, err error) *MockScheduler_ClaimTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockScheduler_ClaimTasks_Call) RunAndReturn(run func(ctx context.Context, limit int32) ([]repo.Task, error)) *MockScheduler_ClaimTasks_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteTask provides a mock function for the type MockScheduler
func (_mock *MockScheduler) CompleteTask(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CompleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScheduler_CompleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteTask'
type MockScheduler_CompleteTask_Call struct {
	*mock.Call
}

// CompleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockScheduler_Expecter) CompleteTask(ctx interface{}, id interface{}) *MockScheduler_CompleteTask_Call {
	return &MockScheduler_CompleteTask_Call{Call: _e.mock.On("CompleteTask", ctx, id)}
}

func (_c *MockScheduler_CompleteTask_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockScheduler_CompleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduler_CompleteTask_Call) Return(err error) *MockScheduler_CompleteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScheduler_CompleteTask_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockScheduler_CompleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// FailTask provides a mock function for the type MockScheduler
func (_mock *MockScheduler) FailTask(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FailTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScheduler_FailTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailTask'
type MockScheduler_FailTask_Call struct {
	*mock.Call
}

// FailTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockScheduler_Expecter) FailTask(ctx interface{}, id interface{}) *MockScheduler_FailTask_Call {
	return &MockScheduler_FailTask_Call{Call: _e.mock.On("FailTask", ctx, id)}
}

func (_c *MockScheduler_FailTask_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockScheduler_FailTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduler_FailTask_Call) Return(err error) *MockScheduler_FailTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScheduler_FailTask_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockScheduler_FailTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListRunnableTasks provides a mock function for the type MockScheduler
func (_mock *MockScheduler) ListRunnableTasks(ctx context.Context, limit int32) ([]repo.Task, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRunnableTasks")
	}

	var r0 []repo.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]repo.Task, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []repo.Task); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduler_ListRunnableTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRunnableTasks'
type MockScheduler_ListRunnableTasks_Call struct {
	*mock.Call
}

// ListRunnableTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
func (_e *MockScheduler_Expecter) ListRunnableTasks(ctx interface{}, limit interface{}) *MockScheduler_ListRunnableTasks_Call {
	return &MockScheduler_ListRunnableTasks_Call{Call: _e.mock.On("ListRunnableTasks", ctx, limit)}
}

func (_c *MockScheduler_ListRunnableTasks_Call) Run(run func(ctx context.Context, limit int32)) *MockScheduler_ListRunnableTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduler_ListRunnableTasks_Call) Return(tasks []repo.Task, err error) *MockScheduler_ListRunnableTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockScheduler_ListRunnableTasks_Call) RunAndReturn(run func(ctx context.Context, limit int32) ([]repo.Task, error)) *MockScheduler_ListRunnableTasks_Call {
	_c.Call.Return(run)
	return _c
}
