// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskReporter creates a new instance of MockTaskReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskReporter {
	mock := &MockTaskReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskReporter is an autogenerated mock type for the TaskReporter type
type MockTaskReporter struct {
	mock.Mock
}

type MockTaskReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskReporter) EXPECT() *MockTaskReporter_Expecter {
	return &MockTaskReporter_Expecter{mock: &_m.Mock}
}

// CompleteTask provides a mock function for the type MockTaskReporter
func (_mock *MockTaskReporter) CompleteTask(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CompleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskReporter_CompleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteTask'
type MockTaskReporter_CompleteTask_Call struct {
	*mock.Call
}

// CompleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTaskReporter_Expecter) CompleteTask(ctx interface{}, id interface{}) *MockTaskReporter_CompleteTask_Call {
	return &MockTaskReporter_CompleteTask_Call{Call: _e.mock.On("CompleteTask", ctx, id)}
}

func (_c *MockTaskReporter_CompleteTask_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskReporter_CompleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskReporter_CompleteTask_Call) Return(err error) *MockTaskReporter_CompleteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskReporter_CompleteTask_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockTaskReporter_CompleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// FailTask provides a mock function for the type MockTaskReporter
func (_mock *MockTaskReporter) FailTask(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FailTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskReporter_FailTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailTask'
type MockTaskReporter_FailTask_Call struct {
	*mock.Call
}

// FailTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTaskReporter_Expecter) FailTask(ctx interface{}, id interface{}) *MockTaskReporter_FailTask_Call {
	return &MockTaskReporter_FailTask_Call{Call: _e.mock.On("FailTask", ctx, id)}
}

func (_c *MockTaskReporter_FailTask_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskReporter_FailTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskReporter_FailTask_Call) Return(err error) *MockTaskReporter_FailTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskReporter_FailTask_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockTaskReporter_FailTask_Call {
	_c.Call.Return(run)
	return _c
}
