// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/repo"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalysisRuns creates a new instance of MockAnalysisRuns. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalysisRuns(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalysisRuns {
	mock := &MockAnalysisRuns{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalysisRuns is an autogenerated mock type for the AnalysisRuns type
type MockAnalysisRuns struct {
	mock.Mock
}

type MockAnalysisRuns_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalysisRuns) EXPECT() *MockAnalysisRuns_Expecter {
	return &MockAnalysisRuns_Expecter{mock: &_m.Mock}
}

// CancelItems provides a mock function for the type MockAnalysisRuns
func (_mock *MockAnalysisRuns) CancelItems(ctx context.Context, fetchID uuid.UUID) error {
	ret := _mock.Called(ctx, fetchID)

	if len(ret) == 0 {
		panic("no return value specified for CancelItems")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, fetchID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnalysisRuns_CancelItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelItems'
type MockAnalysisRuns_CancelItems_Call struct {
	*mock.Call
}

// CancelItems is a helper method to define mock.On call
//   - ctx context.Context
//   - fetchID uuid.UUID
func (_e *MockAnalysisRuns_Expecter) CancelItems(ctx interface{}, fetchID interface{}) *MockAnalysisRuns_CancelItems_Call {
	return &MockAnalysisRuns_CancelItems_Call{Call: _e.mock.On("CancelItems", ctx, fetchID)}
}

func (_c *MockAnalysisRuns_CancelItems_Call) Run(run func(ctx context.Context, fetchID uuid.UUID)) *MockAnalysisRuns_CancelItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalysisRuns_CancelItems_Call) Return(err error) *MockAnalysisRuns_CancelItems_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnalysisRuns_CancelItems_Call) RunAndReturn(run func(ctx context.Context, fetchID uuid.UUID) error) *MockAnalysisRuns_CancelItems_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockAnalysisRuns
func (_mock *MockAnalysisRuns) Create(ctx context.Context, arg repo.CreateAnalysisRunParams) (repo.AnalysisRun, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 repo.AnalysisRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateAnalysisRunParams) (repo.AnalysisRun, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateAnalysisRunParams) repo.AnalysisRun); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.AnalysisRun)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.CreateAnalysisRunParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalysisRuns_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAnalysisRuns_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.CreateAnalysisRunParams
func (_e *MockAnalysisRuns_Expecter) Create(ctx interface{}, arg interface{}) *MockAnalysisRuns_Create_Call {
	return &MockAnalysisRuns_Create_Call{Call: _e.mock.On("Create", ctx, arg)}
}

func (_c *MockAnalysisRuns_Create_Call) Run(run func(ctx context.Context, arg repo.CreateAnalysisRunParams)) *MockAnalysisRuns_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.CreateAnalysisRunParams
		if args[1] != nil {
			arg1 = args[1].(repo.CreateAnalysisRunParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalysisRuns_Create_Call) Return(analysisRun repo.AnalysisRun, err error) *MockAnalysisRuns_Create_Call {
	_c.Call.Return(analysisRun, err)
	return _c
}

func (_c *MockAnalysisRuns_Create_Call) RunAndReturn(run func(ctx context.Context, arg repo.CreateAnalysisRunParams) (repo.AnalysisRun, error)) *MockAnalysisRuns_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function for the type MockAnalysisRuns
func (_mock *MockAnalysisRuns) CreateSession(ctx context.Context, arg repo.CreateAnalysisSessionParams) (repo.AnalysisRun, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 repo.AnalysisRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateAnalysisSessionParams) (repo.AnalysisRun, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateAnalysisSessionParams) repo.AnalysisRun); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.AnalysisRun)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.CreateAnalysisSessionParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalysisRuns_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockAnalysisRuns_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.CreateAnalysisSessionParams
func (_e *MockAnalysisRuns_Expecter) CreateSession(ctx interface{}, arg interface{}) *MockAnalysisRuns_CreateSession_Call {
	return &MockAnalysisRuns_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, arg)}
}

func (_c *MockAnalysisRuns_CreateSession_Call) Run(run func(ctx context.Context, arg repo.CreateAnalysisSessionParams)) *MockAnalysisRuns_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.CreateAnalysisSessionParams
		if args[1] != nil {
			arg1 = args[1].(repo.CreateAnalysisSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalysisRuns_CreateSession_Call) Return(analysisRun repo.AnalysisRun, err error) *MockAnalysisRuns_CreateSession_Call {
	_c.Call.Return(analysisRun, err)
	return _c
}

func (_c *MockAnalysisRuns_CreateSession_Call) RunAndReturn(run func(ctx context.Context, arg repo.CreateAnalysisSessionParams) (repo.AnalysisRun, error)) *MockAnalysisRuns_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetByFetchID provides a mock function for the type MockAnalysisRuns
func (_mock *MockAnalysisRuns) GetByFetchID(ctx context.Context, fetchID uuid.UUID) (repo.AnalysisRun, error) {
	ret := _mock.Called(ctx, fetchID)

	if len(ret) == 0 {
		panic("no return value specified for GetByFetchID")
	}

	var r0 repo.AnalysisRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repo.AnalysisRun, error)); ok {
		return returnFunc(ctx, fetchID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repo.AnalysisRun); ok {
		r0 = returnFunc(ctx, fetchID)
	} else {
		r0 = ret.Get(0).(repo.AnalysisRun)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, fetchID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalysisRuns_GetByFetchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByFetchID'
type MockAnalysisRuns_GetByFetchID_Call struct {
	*mock.Call
}

// GetByFetchID is a helper method to define mock.On call
//   - ctx context.Context
//   - fetchID uuid.UUID
func (_e *MockAnalysisRuns_Expecter) GetByFetchID(ctx interface{}, fetchID interface{}) *MockAnalysisRuns_GetByFetchID_Call {
	return &MockAnalysisRuns_GetByFetchID_Call{Call: _e.mock.On("GetByFetchID", ctx, fetchID)}
}

func (_c *MockAnalysisRuns_GetByFetchID_Call) Run(run func(ctx context.Context, fetchID uuid.UUID)) *MockAnalysisRuns_GetByFetchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalysisRuns_GetByFetchID_Call) Return(analysisRun repo.AnalysisRun, err error) *MockAnalysisRuns_GetByFetchID_Call {
	_c.Call.Return(analysisRun, err)
	return _c
}

func (_c *MockAnalysisRuns_GetByFetchID_Call) RunAndReturn(run func(ctx context.Context, fetchID uuid.UUID) (repo.AnalysisRun, error)) *MockAnalysisRuns_GetByFetchID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAnalysisRuns
func (_mock *MockAnalysisRuns) GetByID(ctx context.Context, id uuid.UUID) (repo.AnalysisRun, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 repo.AnalysisRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repo.AnalysisRun, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repo.AnalysisRun); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repo.AnalysisRun)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalysisRuns_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAnalysisRuns_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAnalysisRuns_Expecter) GetByID(ctx interface{}, id interface{}) *MockAnalysisRuns_GetByID_Call {
	return &MockAnalysisRuns_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAnalysisRuns_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAnalysisRuns_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalysisRuns_GetByID_Call) Return(analysisRun repo.AnalysisRun, err error) *MockAnalysisRuns_GetByID_Call {
	_c.Call.Return(analysisRun, err)
	return _c
}

func (_c *MockAnalysisRuns_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (repo.AnalysisRun, error)) *MockAnalysisRuns_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListItems provides a mock function for the type MockAnalysisRuns
func (_mock *MockAnalysisRuns) ListItems(ctx context.Context, fetchID uuid.UUID) ([]repo.AnalysisRunItem, error) {
	ret := _mock.Called(ctx, fetchID)

	if len(ret) == 0 {
		panic("no return value specified for ListItems")
	}

	var r0 []repo.AnalysisRunItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repo.AnalysisRunItem, error)); ok {
		return returnFunc(ctx, fetchID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repo.AnalysisRunItem); ok {
		r0 = returnFunc(ctx, fetchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.AnalysisRunItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, fetchID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalysisRuns_ListItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItems'
type MockAnalysisRuns_ListItems_Call struct {
	*mock.Call
}

// ListItems is a helper method to define mock.On call
//   - ctx context.Context
//   - fetchID uuid.UUID
func (_e *MockAnalysisRuns_Expecter) ListItems(ctx interface{}, fetchID interface{}) *MockAnalysisRuns_ListItems_Call {
	return &MockAnalysisRuns_ListItems_Call{Call: _e.mock.On("ListItems", ctx, fetchID)}
}

func (_c *MockAnalysisRuns_ListItems_Call) Run(run func(ctx context.Context, fetchID uuid.UUID)) *MockAnalysisRuns_ListItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalysisRuns_ListItems_Call) Return(analysisRunItems []repo.AnalysisRunItem, err error) *MockAnalysisRuns_ListItems_Call {
	_c.Call.Return(analysisRunItems, err)
	return _c
}

func (_c *MockAnalysisRuns_ListItems_Call) RunAndReturn(run func(ctx context.Context, fetchID uuid.UUID) ([]repo.AnalysisRunItem, error)) *MockAnalysisRuns_ListItems_Call {
	_c.Call.Return(run)
	return _c
}

// SetExecution provides a mock function for the type MockAnalysisRuns
func (_mock *MockAnalysisRuns) SetExecution(ctx context.Context, id uuid.UUID, executionID uuid.UUID) (repo.AnalysisRun, error) {
	ret := _mock.Called(ctx, id, executionID)

	if len(ret) == 0 {
		panic("no return value specified for SetExecution")
	}

	var r0 repo.AnalysisRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (repo.AnalysisRun, error)); ok {
		return returnFunc(ctx, id, executionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) repo.AnalysisRun); ok {
		r0 = returnFunc(ctx, id, executionID)
	} else {
		r0 = ret.Get(0).(repo.AnalysisRun)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, executionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalysisRuns_SetExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExecution'
type MockAnalysisRuns_SetExecution_Call struct {
	*mock.Call
}

// SetExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - executionID uuid.UUID
func (_e *MockAnalysisRuns_Expecter) SetExecution(ctx interface{}, id interface{}, executionID interface{}) *MockAnalysisRuns_SetExecution_Call {
	return &MockAnalysisRuns_SetExecution_Call{Call: _e.mock.On("SetExecution", ctx, id, executionID)}
}

func (_c *MockAnalysisRuns_SetExecution_Call) Run(run func(ctx context.Context, id uuid.UUID, executionID uuid.UUID)) *MockAnalysisRuns_SetExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalysisRuns_SetExecution_Call) Return(analysisRun repo.AnalysisRun, err error) *MockAnalysisRuns_SetExecution_Call {
	_c.Call.Return(analysisRun, err)
	return _c
}

func (_c *MockAnalysisRuns_SetExecution_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, executionID uuid.UUID) (repo.AnalysisRun, error)) *MockAnalysisRuns_SetExecution_Call {
	_c.Call.Return(run)
	return _c
}

// SetManifest provides a mock function for the type MockAnalysisRuns
func (_mock *MockAnalysisRuns) SetManifest(ctx context.Context, arg repo.SetAnalysisRunManifestParams) (repo.AnalysisRun, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SetManifest")
	}

	var r0 repo.AnalysisRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.SetAnalysisRunManifestParams) (repo.AnalysisRun, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.SetAnalysisRunManifestParams) repo.AnalysisRun); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.AnalysisRun)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.SetAnalysisRunManifestParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalysisRuns_SetManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetManifest'
type MockAnalysisRuns_SetManifest_Call struct {
	*mock.Call
}

// SetManifest is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.SetAnalysisRunManifestParams
func (_e *MockAnalysisRuns_Expecter) SetManifest(ctx interface{}, arg interface{}) *MockAnalysisRuns_SetManifest_Call {
	return &MockAnalysisRuns_SetManifest_Call{Call: _e.mock.On("SetManifest", ctx, arg)}
}

func (_c *MockAnalysisRuns_SetManifest_Call) Run(run func(ctx context.Context, arg repo.SetAnalysisRunManifestParams)) *MockAnalysisRuns_SetManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.SetAnalysisRunManifestParams
		if args[1] != nil {
			arg1 = args[1].(repo.SetAnalysisRunManifestParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalysisRuns_SetManifest_Call) Return(analysisRun repo.AnalysisRun, err error) *MockAnalysisRuns_SetManifest_Call {
	_c.Call.Return(analysisRun, err)
	return _c
}

func (_c *MockAnalysisRuns_SetManifest_Call) RunAndReturn(run func(ctx context.Context, arg repo.SetAnalysisRunManifestParams) (repo.AnalysisRun, error)) *MockAnalysisRuns_SetManifest_Call {
	_c.Call.Return(run)
	return _c
}

// SetRoot provides a mock function for the type MockAnalysisRuns
func (_mock *MockAnalysisRuns) SetRoot(ctx context.Context, id uuid.UUID, rootBatchID uuid.UUID) (repo.AnalysisRun, error) {
	ret := _mock.Called(ctx, id, rootBatchID)

	if len(ret) == 0 {
		panic("no return value specified for SetRoot")
	}

	var r0 repo.AnalysisRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (repo.AnalysisRun, error)); ok {
		return returnFunc(ctx, id, rootBatchID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) repo.AnalysisRun); ok {
		r0 = returnFunc(ctx, id, rootBatchID)
	} else {
		r0 = ret.Get(0).(repo.AnalysisRun)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, rootBatchID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalysisRuns_SetRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRoot'
type MockAnalysisRuns_SetRoot_Call struct {
	*mock.Call
}

// SetRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - rootBatchID uuid.UUID
func (_e *MockAnalysisRuns_Expecter) SetRoot(ctx interface{}, id interface{}, rootBatchID interface{}) *MockAnalysisRuns_SetRoot_Call {
	return &MockAnalysisRuns_SetRoot_Call{Call: _e.mock.On("SetRoot", ctx, id, rootBatchID)}
}

func (_c *MockAnalysisRuns_SetRoot_Call) Run(run func(ctx context.Context, id uuid.UUID, rootBatchID uuid.UUID)) *MockAnalysisRuns_SetRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalysisRuns_SetRoot_Call) Return(analysisRun repo.AnalysisRun, err error) *MockAnalysisRuns_SetRoot_Call {
	_c.Call.Return(analysisRun, err)
	return _c
}

func (_c *MockAnalysisRuns_SetRoot_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, rootBatchID uuid.UUID) (repo.AnalysisRun, error)) *MockAnalysisRuns_SetRoot_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function for the type MockAnalysisRuns
func (_mock *MockAnalysisRuns) SetStatus(ctx context.Context, arg repo.SetAnalysisRunStatusParams) (repo.AnalysisRun, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 repo.AnalysisRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.SetAnalysisRunStatusParams) (repo.AnalysisRun, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.SetAnalysisRunStatusParams) repo.AnalysisRun); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.AnalysisRun)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.SetAnalysisRunStatusParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalysisRuns_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockAnalysisRuns_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.SetAnalysisRunStatusParams
func (_e *MockAnalysisRuns_Expecter) SetStatus(ctx interface{}, arg interface{}) *MockAnalysisRuns_SetStatus_Call {
	return &MockAnalysisRuns_SetStatus_Call{Call: _e.mock.On("SetStatus", ctx, arg)}
}

func (_c *MockAnalysisRuns_SetStatus_Call) Run(run func(ctx context.Context, arg repo.SetAnalysisRunStatusParams)) *MockAnalysisRuns_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.SetAnalysisRunStatusParams
		if args[1] != nil {
			arg1 = args[1].(repo.SetAnalysisRunStatusParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalysisRuns_SetStatus_Call) Return(analysisRun repo.AnalysisRun, err error) *MockAnalysisRuns_SetStatus_Call {
	_c.Call.Return(analysisRun, err)
	return _c
}

func (_c *MockAnalysisRuns_SetStatus_Call) RunAndReturn(run func(ctx context.Context, arg repo.SetAnalysisRunStatusParams) (repo.AnalysisRun, error)) *MockAnalysisRuns_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}
