// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/repo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScout creates a new instance of MockScout. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScout(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScout {
	mock := &MockScout{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScout is an autogenerated mock type for the Scout type
type MockScout struct {
	mock.Mock
}

type MockScout_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScout) EXPECT() *MockScout_Expecter {
	return &MockScout_Expecter{mock: &_m.Mock}
}

// CreateCandidate provides a mock function for the type MockScout
func (_mock *MockScout) CreateCandidate(ctx context.Context, arg repo.CreateCandidateParams) (repo.Candidate, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateCandidate")
	}

	var r0 repo.Candidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateCandidateParams) (repo.Candidate, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateCandidateParams) repo.Candidate); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Candidate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.CreateCandidateParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScout_CreateCandidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCandidate'
type MockScout_CreateCandidate_Call struct {
	*mock.Call
}

// CreateCandidate is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.CreateCandidateParams
func (_e *MockScout_Expecter) CreateCandidate(ctx interface{}, arg interface{}) *MockScout_CreateCandidate_Call {
	return &MockScout_CreateCandidate_Call{Call: _e.mock.On("CreateCandidate", ctx, arg)}
}

func (_c *MockScout_CreateCandidate_Call) Run(run func(ctx context.Context, arg repo.CreateCandidateParams)) *MockScout_CreateCandidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.CreateCandidateParams
		if args[1] != nil {
			arg1 = args[1].(repo.CreateCandidateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScout_CreateCandidate_Call) Return(candidate repo.Candidate, err error) *MockScout_CreateCandidate_Call {
	_c.Call.Return(candidate, err)
	return _c
}

func (_c *MockScout_CreateCandidate_Call) RunAndReturn(run func(ctx context.Context, arg repo.CreateCandidateParams) (repo.Candidate, error)) *MockScout_CreateCandidate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCandidateByFingerprint provides a mock function for the type MockScout
func (_mock *MockScout) GetCandidateByFingerprint(ctx context.Context, fingerprint string) (repo.Candidate, error) {
	ret := _mock.Called(ctx, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for GetCandidateByFingerprint")
	}

	var r0 repo.Candidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repo.Candidate, error)); ok {
		return returnFunc(ctx, fingerprint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repo.Candidate); ok {
		r0 = returnFunc(ctx, fingerprint)
	} else {
		r0 = ret.Get(0).(repo.Candidate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fingerprint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScout_GetCandidateByFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCandidateByFingerprint'
type MockScout_GetCandidateByFingerprint_Call struct {
	*mock.Call
}

// GetCandidateByFingerprint is a helper method to define mock.On call
//   - ctx context.Context
//   - fingerprint string
func (_e *MockScout_Expecter) GetCandidateByFingerprint(ctx interface{}, fingerprint interface{}) *MockScout_GetCandidateByFingerprint_Call {
	return &MockScout_GetCandidateByFingerprint_Call{Call: _e.mock.On("GetCandidateByFingerprint", ctx, fingerprint)}
}

func (_c *MockScout_GetCandidateByFingerprint_Call) Run(run func(ctx context.Context, fingerprint string)) *MockScout_GetCandidateByFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScout_GetCandidateByFingerprint_Call) Return(candidate repo.Candidate, err error) *MockScout_GetCandidateByFingerprint_Call {
	_c.Call.Return(candidate, err)
	return _c
}

func (_c *MockScout_GetCandidateByFingerprint_Call) RunAndReturn(run func(ctx context.Context, fingerprint string) (repo.Candidate, error)) *MockScout_GetCandidateByFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// GetSourceByID provides a mock function for the type MockScout
func (_mock *MockScout) GetSourceByID(ctx context.Context, id int32) (repo.Source, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSourceByID")
	}

	var r0 repo.Source
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (repo.Source, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) repo.Source); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repo.Source)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScout_GetSourceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSourceByID'
type MockScout_GetSourceByID_Call struct {
	*mock.Call
}

// GetSourceByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockScout_Expecter) GetSourceByID(ctx interface{}, id interface{}) *MockScout_GetSourceByID_Call {
	return &MockScout_GetSourceByID_Call{Call: _e.mock.On("GetSourceByID", ctx, id)}
}

func (_c *MockScout_GetSourceByID_Call) Run(run func(ctx context.Context, id int32)) *MockScout_GetSourceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScout_GetSourceByID_Call) Return(source repo.Source, err error) *MockScout_GetSourceByID_Call {
	_c.Call.Return(source, err)
	return _c
}

func (_c *MockScout_GetSourceByID_Call) RunAndReturn(run func(ctx context.Context, id int32) (repo.Source, error)) *MockScout_GetSourceByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertCandidate provides a mock function for the type MockScout
func (_mock *MockScout) UpsertCandidate(ctx context.Context, arg repo.UpsertCandidateParams) (repo.Candidate, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertCandidate")
	}

	var r0 repo.Candidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.UpsertCandidateParams) (repo.Candidate, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.UpsertCandidateParams) repo.Candidate); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Candidate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.UpsertCandidateParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScout_UpsertCandidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertCandidate'
type MockScout_UpsertCandidate_Call struct {
	*mock.Call
}

// UpsertCandidate is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.UpsertCandidateParams
func (_e *MockScout_Expecter) UpsertCandidate(ctx interface{}, arg interface{}) *MockScout_UpsertCandidate_Call {
	return &MockScout_UpsertCandidate_Call{Call: _e.mock.On("UpsertCandidate", ctx, arg)}
}

func (_c *MockScout_UpsertCandidate_Call) Run(run func(ctx context.Context, arg repo.UpsertCandidateParams)) *MockScout_UpsertCandidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.UpsertCandidateParams
		if args[1] != nil {
			arg1 = args[1].(repo.UpsertCandidateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScout_UpsertCandidate_Call) Return(candidate repo.Candidate, err error) *MockScout_UpsertCandidate_Call {
	_c.Call.Return(candidate, err)
	return _c
}

func (_c *MockScout_UpsertCandidate_Call) RunAndReturn(run func(ctx context.Context, arg repo.UpsertCandidateParams) (repo.Candidate, error)) *MockScout_UpsertCandidate_Call {
	_c.Call.Return(run)
	return _c
}
