// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/repo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSources creates a new instance of MockSources. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSources(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSources {
	mock := &MockSources{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSources is an autogenerated mock type for the Sources type
type MockSources struct {
	mock.Mock
}

type MockSources_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSources) EXPECT() *MockSources_Expecter {
	return &MockSources_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSources
func (_mock *MockSources) Create(ctx context.Context, arg repo.CreateSourceParams) (repo.Source, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 repo.Source
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateSourceParams) (repo.Source, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateSourceParams) repo.Source); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Source)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.CreateSourceParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSources_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSources_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.CreateSourceParams
func (_e *MockSources_Expecter) Create(ctx interface{}, arg interface{}) *MockSources_Create_Call {
	return &MockSources_Create_Call{Call: _e.mock.On("Create", ctx, arg)}
}

func (_c *MockSources_Create_Call) Run(run func(ctx context.Context, arg repo.CreateSourceParams)) *MockSources_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.CreateSourceParams
		if args[1] != nil {
			arg1 = args[1].(repo.CreateSourceParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSources_Create_Call) Return(source repo.Source, err error) *MockSources_Create_Call {
	_c.Call.Return(source, err)
	return _c
}

func (_c *MockSources_Create_Call) RunAndReturn(run func(ctx context.Context, arg repo.CreateSourceParams) (repo.Source, error)) *MockSources_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSources
func (_mock *MockSources) Delete(ctx context.Context, abbr string) (repo.Source, error) {
	ret := _mock.Called(ctx, abbr)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 repo.Source
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repo.Source, error)); ok {
		return returnFunc(ctx, abbr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repo.Source); ok {
		r0 = returnFunc(ctx, abbr)
	} else {
		r0 = ret.Get(0).(repo.Source)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, abbr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSources_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSources_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - abbr string
func (_e *MockSources_Expecter) Delete(ctx interface{}, abbr interface{}) *MockSources_Delete_Call {
	return &MockSources_Delete_Call{Call: _e.mock.On("Delete", ctx, abbr)}
}

func (_c *MockSources_Delete_Call) Run(run func(ctx context.Context, abbr string)) *MockSources_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSources_Delete_Call) Return(source repo.Source, err error) *MockSources_Delete_Call {
	_c.Call.Return(source, err)
	return _c
}

func (_c *MockSources_Delete_Call) RunAndReturn(run func(ctx context.Context, abbr string) (repo.Source, error)) *MockSources_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type MockSources
func (_mock *MockSources) Restore(ctx context.Context, abbr string) (repo.Source, error) {
	ret := _mock.Called(ctx, abbr)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 repo.Source
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repo.Source, error)); ok {
		return returnFunc(ctx, abbr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repo.Source); ok {
		r0 = returnFunc(ctx, abbr)
	} else {
		r0 = ret.Get(0).(repo.Source)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, abbr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSources_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockSources_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - abbr string
func (_e *MockSources_Expecter) Restore(ctx interface{}, abbr interface{}) *MockSources_Restore_Call {
	return &MockSources_Restore_Call{Call: _e.mock.On("Restore", ctx, abbr)}
}

func (_c *MockSources_Restore_Call) Run(run func(ctx context.Context, abbr string)) *MockSources_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSources_Restore_Call) Return(source repo.Source, err error) *MockSources_Restore_Call {
	_c.Call.Return(source, err)
	return _c
}

func (_c *MockSources_Restore_Call) RunAndReturn(run func(ctx context.Context, abbr string) (repo.Source, error)) *MockSources_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSources
func (_mock *MockSources) Update(ctx context.Context, arg repo.UpdateSourceParams) (repo.Source, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 repo.Source
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.UpdateSourceParams) (repo.Source, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.UpdateSourceParams) repo.Source); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Source)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.UpdateSourceParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSources_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSources_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.UpdateSourceParams
func (_e *MockSources_Expecter) Update(ctx interface{}, arg interface{}) *MockSources_Update_Call {
	return &MockSources_Update_Call{Call: _e.mock.On("Update", ctx, arg)}
}

func (_c *MockSources_Update_Call) Run(run func(ctx context.Context, arg repo.UpdateSourceParams)) *MockSources_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.UpdateSourceParams
		if args[1] != nil {
			arg1 = args[1].(repo.UpdateSourceParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSources_Update_Call) Return(source repo.Source, err error) *MockSources_Update_Call {
	_c.Call.Return(source, err)
	return _c
}

func (_c *MockSources_Update_Call) RunAndReturn(run func(ctx context.Context, arg repo.UpdateSourceParams) (repo.Source, error)) *MockSources_Update_Call {
	_c.Call.Return(run)
	return _c
}
