// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ChiaYuChang/prism/internal/repo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Analysis provides a mock function for the type MockRepository
func (_mock *MockRepository) Analysis() repo.Analysis {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Analysis")
	}

	var r0 repo.Analysis
	if returnFunc, ok := ret.Get(0).(func() repo.Analysis); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Analysis)
		}
	}
	return r0
}

// MockRepository_Analysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Analysis'
type MockRepository_Analysis_Call struct {
	*mock.Call
}

// Analysis is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Analysis() *MockRepository_Analysis_Call {
	return &MockRepository_Analysis_Call{Call: _e.mock.On("Analysis")}
}

func (_c *MockRepository_Analysis_Call) Run(run func()) *MockRepository_Analysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Analysis_Call) Return(analysis repo.Analysis) *MockRepository_Analysis_Call {
	_c.Call.Return(analysis)
	return _c
}

func (_c *MockRepository_Analysis_Call) RunAndReturn(run func() repo.Analysis) *MockRepository_Analysis_Call {
	_c.Call.Return(run)
	return _c
}

// BatchTrigger provides a mock function for the type MockRepository
func (_mock *MockRepository) BatchTrigger() repo.BatchTrigger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BatchTrigger")
	}

	var r0 repo.BatchTrigger
	if returnFunc, ok := ret.Get(0).(func() repo.BatchTrigger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.BatchTrigger)
		}
	}
	return r0
}

// MockRepository_BatchTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchTrigger'
type MockRepository_BatchTrigger_Call struct {
	*mock.Call
}

// BatchTrigger is a helper method to define mock.On call
func (_e *MockRepository_Expecter) BatchTrigger() *MockRepository_BatchTrigger_Call {
	return &MockRepository_BatchTrigger_Call{Call: _e.mock.On("BatchTrigger")}
}

func (_c *MockRepository_BatchTrigger_Call) Run(run func()) *MockRepository_BatchTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_BatchTrigger_Call) Return(batchTrigger repo.BatchTrigger) *MockRepository_BatchTrigger_Call {
	_c.Call.Return(batchTrigger)
	return _c
}

func (_c *MockRepository_BatchTrigger_Call) RunAndReturn(run func() repo.BatchTrigger) *MockRepository_BatchTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// Embedding provides a mock function for the type MockRepository
func (_mock *MockRepository) Embedding() repo.Embeddings {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Embedding")
	}

	var r0 repo.Embeddings
	if returnFunc, ok := ret.Get(0).(func() repo.Embeddings); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Embeddings)
		}
	}
	return r0
}

// MockRepository_Embedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embedding'
type MockRepository_Embedding_Call struct {
	*mock.Call
}

// Embedding is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Embedding() *MockRepository_Embedding_Call {
	return &MockRepository_Embedding_Call{Call: _e.mock.On("Embedding")}
}

func (_c *MockRepository_Embedding_Call) Run(run func()) *MockRepository_Embedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Embedding_Call) Return(embeddings repo.Embeddings) *MockRepository_Embedding_Call {
	_c.Call.Return(embeddings)
	return _c
}

func (_c *MockRepository_Embedding_Call) RunAndReturn(run func() repo.Embeddings) *MockRepository_Embedding_Call {
	_c.Call.Return(run)
	return _c
}

// Operator provides a mock function for the type MockRepository
func (_mock *MockRepository) Operator() repo.Operator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operator")
	}

	var r0 repo.Operator
	if returnFunc, ok := ret.Get(0).(func() repo.Operator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Operator)
		}
	}
	return r0
}

// MockRepository_Operator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operator'
type MockRepository_Operator_Call struct {
	*mock.Call
}

// Operator is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Operator() *MockRepository_Operator_Call {
	return &MockRepository_Operator_Call{Call: _e.mock.On("Operator")}
}

func (_c *MockRepository_Operator_Call) Run(run func()) *MockRepository_Operator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Operator_Call) Return(operator repo.Operator) *MockRepository_Operator_Call {
	_c.Call.Return(operator)
	return _c
}

func (_c *MockRepository_Operator_Call) RunAndReturn(run func() repo.Operator) *MockRepository_Operator_Call {
	_c.Call.Return(run)
	return _c
}

// Pipeline provides a mock function for the type MockRepository
func (_mock *MockRepository) Pipeline() repo.Pipeline {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pipeline")
	}

	var r0 repo.Pipeline
	if returnFunc, ok := ret.Get(0).(func() repo.Pipeline); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Pipeline)
		}
	}
	return r0
}

// MockRepository_Pipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pipeline'
type MockRepository_Pipeline_Call struct {
	*mock.Call
}

// Pipeline is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Pipeline() *MockRepository_Pipeline_Call {
	return &MockRepository_Pipeline_Call{Call: _e.mock.On("Pipeline")}
}

func (_c *MockRepository_Pipeline_Call) Run(run func()) *MockRepository_Pipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Pipeline_Call) Return(pipeline repo.Pipeline) *MockRepository_Pipeline_Call {
	_c.Call.Return(pipeline)
	return _c
}

func (_c *MockRepository_Pipeline_Call) RunAndReturn(run func() repo.Pipeline) *MockRepository_Pipeline_Call {
	_c.Call.Return(run)
	return _c
}

// Planner provides a mock function for the type MockRepository
func (_mock *MockRepository) Planner() repo.PlannerResults {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Planner")
	}

	var r0 repo.PlannerResults
	if returnFunc, ok := ret.Get(0).(func() repo.PlannerResults); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.PlannerResults)
		}
	}
	return r0
}

// MockRepository_Planner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Planner'
type MockRepository_Planner_Call struct {
	*mock.Call
}

// Planner is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Planner() *MockRepository_Planner_Call {
	return &MockRepository_Planner_Call{Call: _e.mock.On("Planner")}
}

func (_c *MockRepository_Planner_Call) Run(run func()) *MockRepository_Planner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Planner_Call) Return(plannerResults repo.PlannerResults) *MockRepository_Planner_Call {
	_c.Call.Return(plannerResults)
	return _c
}

func (_c *MockRepository_Planner_Call) RunAndReturn(run func() repo.PlannerResults) *MockRepository_Planner_Call {
	_c.Call.Return(run)
	return _c
}

// Prompts provides a mock function for the type MockRepository
func (_mock *MockRepository) Prompts() repo.Prompts {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Prompts")
	}

	var r0 repo.Prompts
	if returnFunc, ok := ret.Get(0).(func() repo.Prompts); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Prompts)
		}
	}
	return r0
}

// MockRepository_Prompts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prompts'
type MockRepository_Prompts_Call struct {
	*mock.Call
}

// Prompts is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Prompts() *MockRepository_Prompts_Call {
	return &MockRepository_Prompts_Call{Call: _e.mock.On("Prompts")}
}

func (_c *MockRepository_Prompts_Call) Run(run func()) *MockRepository_Prompts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Prompts_Call) Return(prompts repo.Prompts) *MockRepository_Prompts_Call {
	_c.Call.Return(prompts)
	return _c
}

func (_c *MockRepository_Prompts_Call) RunAndReturn(run func() repo.Prompts) *MockRepository_Prompts_Call {
	_c.Call.Return(run)
	return _c
}

// Scheduler provides a mock function for the type MockRepository
func (_mock *MockRepository) Scheduler() repo.Scheduler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Scheduler")
	}

	var r0 repo.Scheduler
	if returnFunc, ok := ret.Get(0).(func() repo.Scheduler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Scheduler)
		}
	}
	return r0
}

// MockRepository_Scheduler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scheduler'
type MockRepository_Scheduler_Call struct {
	*mock.Call
}

// Scheduler is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Scheduler() *MockRepository_Scheduler_Call {
	return &MockRepository_Scheduler_Call{Call: _e.mock.On("Scheduler")}
}

func (_c *MockRepository_Scheduler_Call) Run(run func()) *MockRepository_Scheduler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Scheduler_Call) Return(scheduler repo.Scheduler) *MockRepository_Scheduler_Call {
	_c.Call.Return(scheduler)
	return _c
}

func (_c *MockRepository_Scheduler_Call) RunAndReturn(run func() repo.Scheduler) *MockRepository_Scheduler_Call {
	_c.Call.Return(run)
	return _c
}

// Schedules provides a mock function for the type MockRepository
func (_mock *MockRepository) Schedules() repo.Schedules {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Schedules")
	}

	var r0 repo.Schedules
	if returnFunc, ok := ret.Get(0).(func() repo.Schedules); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Schedules)
		}
	}
	return r0
}

// MockRepository_Schedules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schedules'
type MockRepository_Schedules_Call struct {
	*mock.Call
}

// Schedules is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Schedules() *MockRepository_Schedules_Call {
	return &MockRepository_Schedules_Call{Call: _e.mock.On("Schedules")}
}

func (_c *MockRepository_Schedules_Call) Run(run func()) *MockRepository_Schedules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Schedules_Call) Return(schedules repo.Schedules) *MockRepository_Schedules_Call {
	_c.Call.Return(schedules)
	return _c
}

func (_c *MockRepository_Schedules_Call) RunAndReturn(run func() repo.Schedules) *MockRepository_Schedules_Call {
	_c.Call.Return(run)
	return _c
}

// Scout provides a mock function for the type MockRepository
func (_mock *MockRepository) Scout() repo.Scout {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Scout")
	}

	var r0 repo.Scout
	if returnFunc, ok := ret.Get(0).(func() repo.Scout); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Scout)
		}
	}
	return r0
}

// MockRepository_Scout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scout'
type MockRepository_Scout_Call struct {
	*mock.Call
}

// Scout is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Scout() *MockRepository_Scout_Call {
	return &MockRepository_Scout_Call{Call: _e.mock.On("Scout")}
}

func (_c *MockRepository_Scout_Call) Run(run func()) *MockRepository_Scout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Scout_Call) Return(scout repo.Scout) *MockRepository_Scout_Call {
	_c.Call.Return(scout)
	return _c
}

func (_c *MockRepository_Scout_Call) RunAndReturn(run func() repo.Scout) *MockRepository_Scout_Call {
	_c.Call.Return(run)
	return _c
}

// Sources provides a mock function for the type MockRepository
func (_mock *MockRepository) Sources() repo.Sources {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sources")
	}

	var r0 repo.Sources
	if returnFunc, ok := ret.Get(0).(func() repo.Sources); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Sources)
		}
	}
	return r0
}

// MockRepository_Sources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sources'
type MockRepository_Sources_Call struct {
	*mock.Call
}

// Sources is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Sources() *MockRepository_Sources_Call {
	return &MockRepository_Sources_Call{Call: _e.mock.On("Sources")}
}

func (_c *MockRepository_Sources_Call) Run(run func()) *MockRepository_Sources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Sources_Call) Return(sources repo.Sources) *MockRepository_Sources_Call {
	_c.Call.Return(sources)
	return _c
}

func (_c *MockRepository_Sources_Call) RunAndReturn(run func() repo.Sources) *MockRepository_Sources_Call {
	_c.Call.Return(run)
	return _c
}

// Tasks provides a mock function for the type MockRepository
func (_mock *MockRepository) Tasks() repo.Tasks {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tasks")
	}

	var r0 repo.Tasks
	if returnFunc, ok := ret.Get(0).(func() repo.Tasks); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Tasks)
		}
	}
	return r0
}

// MockRepository_Tasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tasks'
type MockRepository_Tasks_Call struct {
	*mock.Call
}

// Tasks is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Tasks() *MockRepository_Tasks_Call {
	return &MockRepository_Tasks_Call{Call: _e.mock.On("Tasks")}
}

func (_c *MockRepository_Tasks_Call) Run(run func()) *MockRepository_Tasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Tasks_Call) Return(tasks repo.Tasks) *MockRepository_Tasks_Call {
	_c.Call.Return(tasks)
	return _c
}

func (_c *MockRepository_Tasks_Call) RunAndReturn(run func() repo.Tasks) *MockRepository_Tasks_Call {
	_c.Call.Return(run)
	return _c
}

// Tokens provides a mock function for the type MockRepository
func (_mock *MockRepository) Tokens() repo.Tokens {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tokens")
	}

	var r0 repo.Tokens
	if returnFunc, ok := ret.Get(0).(func() repo.Tokens); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Tokens)
		}
	}
	return r0
}

// MockRepository_Tokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tokens'
type MockRepository_Tokens_Call struct {
	*mock.Call
}

// Tokens is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Tokens() *MockRepository_Tokens_Call {
	return &MockRepository_Tokens_Call{Call: _e.mock.On("Tokens")}
}

func (_c *MockRepository_Tokens_Call) Run(run func()) *MockRepository_Tokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Tokens_Call) Return(tokens repo.Tokens) *MockRepository_Tokens_Call {
	_c.Call.Return(tokens)
	return _c
}

func (_c *MockRepository_Tokens_Call) RunAndReturn(run func() repo.Tokens) *MockRepository_Tokens_Call {
	_c.Call.Return(run)
	return _c
}

// UserFetches provides a mock function for the type MockRepository
func (_mock *MockRepository) UserFetches() repo.UserFetches {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserFetches")
	}

	var r0 repo.UserFetches
	if returnFunc, ok := ret.Get(0).(func() repo.UserFetches); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.UserFetches)
		}
	}
	return r0
}

// MockRepository_UserFetches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserFetches'
type MockRepository_UserFetches_Call struct {
	*mock.Call
}

// UserFetches is a helper method to define mock.On call
func (_e *MockRepository_Expecter) UserFetches() *MockRepository_UserFetches_Call {
	return &MockRepository_UserFetches_Call{Call: _e.mock.On("UserFetches")}
}

func (_c *MockRepository_UserFetches_Call) Run(run func()) *MockRepository_UserFetches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_UserFetches_Call) Return(userFetches repo.UserFetches) *MockRepository_UserFetches_Call {
	_c.Call.Return(userFetches)
	return _c
}

func (_c *MockRepository_UserFetches_Call) RunAndReturn(run func() repo.UserFetches) *MockRepository_UserFetches_Call {
	_c.Call.Return(run)
	return _c
}
