// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/repo"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPipelineRuntime creates a new instance of MockPipelineRuntime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPipelineRuntime(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPipelineRuntime {
	mock := &MockPipelineRuntime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPipelineRuntime is an autogenerated mock type for the PipelineRuntime type
type MockPipelineRuntime struct {
	mock.Mock
}

type MockPipelineRuntime_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPipelineRuntime) EXPECT() *MockPipelineRuntime_Expecter {
	return &MockPipelineRuntime_Expecter{mock: &_m.Mock}
}

// FindFinishedBatches provides a mock function for the type MockPipelineRuntime
func (_mock *MockPipelineRuntime) FindFinishedBatches(ctx context.Context, limit int32) ([]repo.Batch, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindFinishedBatches")
	}

	var r0 []repo.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]repo.Batch, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []repo.Batch); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Batch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPipelineRuntime_FindFinishedBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFinishedBatches'
type MockPipelineRuntime_FindFinishedBatches_Call struct {
	*mock.Call
}

// FindFinishedBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
func (_e *MockPipelineRuntime_Expecter) FindFinishedBatches(ctx interface{}, limit interface{}) *MockPipelineRuntime_FindFinishedBatches_Call {
	return &MockPipelineRuntime_FindFinishedBatches_Call{Call: _e.mock.On("FindFinishedBatches", ctx, limit)}
}

func (_c *MockPipelineRuntime_FindFinishedBatches_Call) Run(run func(ctx context.Context, limit int32)) *MockPipelineRuntime_FindFinishedBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPipelineRuntime_FindFinishedBatches_Call) Return(batchs []repo.Batch, err error) *MockPipelineRuntime_FindFinishedBatches_Call {
	_c.Call.Return(batchs, err)
	return _c
}

func (_c *MockPipelineRuntime_FindFinishedBatches_Call) RunAndReturn(run func(ctx context.Context, limit int32) ([]repo.Batch, error)) *MockPipelineRuntime_FindFinishedBatches_Call {
	_c.Call.Return(run)
	return _c
}

// MarkBatchFinished provides a mock function for the type MockPipelineRuntime
func (_mock *MockPipelineRuntime) MarkBatchFinished(ctx context.Context, batchID uuid.UUID, succeeded bool, traceID string) (int64, error) {
	ret := _mock.Called(ctx, batchID, succeeded, traceID)

	if len(ret) == 0 {
		panic("no return value specified for MarkBatchFinished")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool, string) (int64, error)); ok {
		return returnFunc(ctx, batchID, succeeded, traceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool, string) int64); ok {
		r0 = returnFunc(ctx, batchID, succeeded, traceID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool, string) error); ok {
		r1 = returnFunc(ctx, batchID, succeeded, traceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPipelineRuntime_MarkBatchFinished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkBatchFinished'
type MockPipelineRuntime_MarkBatchFinished_Call struct {
	*mock.Call
}

// MarkBatchFinished is a helper method to define mock.On call
//   - ctx context.Context
//   - batchID uuid.UUID
//   - succeeded bool
//   - traceID string
func (_e *MockPipelineRuntime_Expecter) MarkBatchFinished(ctx interface{}, batchID interface{}, succeeded interface{}, traceID interface{}) *MockPipelineRuntime_MarkBatchFinished_Call {
	return &MockPipelineRuntime_MarkBatchFinished_Call{Call: _e.mock.On("MarkBatchFinished", ctx, batchID, succeeded, traceID)}
}

func (_c *MockPipelineRuntime_MarkBatchFinished_Call) Run(run func(ctx context.Context, batchID uuid.UUID, succeeded bool, traceID string)) *MockPipelineRuntime_MarkBatchFinished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPipelineRuntime_MarkBatchFinished_Call) Return(n int64, err error) *MockPipelineRuntime_MarkBatchFinished_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPipelineRuntime_MarkBatchFinished_Call) RunAndReturn(run func(ctx context.Context, batchID uuid.UUID, succeeded bool, traceID string) (int64, error)) *MockPipelineRuntime_MarkBatchFinished_Call {
	_c.Call.Return(run)
	return _c
}

// SetNSubtasks provides a mock function for the type MockPipelineRuntime
func (_mock *MockPipelineRuntime) SetNSubtasks(ctx context.Context, batchID uuid.UUID, count int32) (repo.Batch, error) {
	ret := _mock.Called(ctx, batchID, count)

	if len(ret) == 0 {
		panic("no return value specified for SetNSubtasks")
	}

	var r0 repo.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32) (repo.Batch, error)); ok {
		return returnFunc(ctx, batchID, count)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32) repo.Batch); ok {
		r0 = returnFunc(ctx, batchID, count)
	} else {
		r0 = ret.Get(0).(repo.Batch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32) error); ok {
		r1 = returnFunc(ctx, batchID, count)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPipelineRuntime_SetNSubtasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNSubtasks'
type MockPipelineRuntime_SetNSubtasks_Call struct {
	*mock.Call
}

// SetNSubtasks is a helper method to define mock.On call
//   - ctx context.Context
//   - batchID uuid.UUID
//   - count int32
func (_e *MockPipelineRuntime_Expecter) SetNSubtasks(ctx interface{}, batchID interface{}, count interface{}) *MockPipelineRuntime_SetNSubtasks_Call {
	return &MockPipelineRuntime_SetNSubtasks_Call{Call: _e.mock.On("SetNSubtasks", ctx, batchID, count)}
}

func (_c *MockPipelineRuntime_SetNSubtasks_Call) Run(run func(ctx context.Context, batchID uuid.UUID, count int32)) *MockPipelineRuntime_SetNSubtasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPipelineRuntime_SetNSubtasks_Call) Return(batch repo.Batch, err error) *MockPipelineRuntime_SetNSubtasks_Call {
	_c.Call.Return(batch, err)
	return _c
}

func (_c *MockPipelineRuntime_SetNSubtasks_Call) RunAndReturn(run func(ctx context.Context, batchID uuid.UUID, count int32) (repo.Batch, error)) *MockPipelineRuntime_SetNSubtasks_Call {
	_c.Call.Return(run)
	return _c
}
