// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/repo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRootControl creates a new instance of MockRootControl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRootControl(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRootControl {
	mock := &MockRootControl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRootControl is an autogenerated mock type for the RootControl type
type MockRootControl struct {
	mock.Mock
}

type MockRootControl_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRootControl) EXPECT() *MockRootControl_Expecter {
	return &MockRootControl_Expecter{mock: &_m.Mock}
}

// CheckRoot provides a mock function for the type MockRootControl
func (_mock *MockRootControl) CheckRoot(ctx context.Context, arg repo.RootAuthParams) (bool, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CheckRoot")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.RootAuthParams) (bool, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.RootAuthParams) bool); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.RootAuthParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRootControl_CheckRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckRoot'
type MockRootControl_CheckRoot_Call struct {
	*mock.Call
}

// CheckRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.RootAuthParams
func (_e *MockRootControl_Expecter) CheckRoot(ctx interface{}, arg interface{}) *MockRootControl_CheckRoot_Call {
	return &MockRootControl_CheckRoot_Call{Call: _e.mock.On("CheckRoot", ctx, arg)}
}

func (_c *MockRootControl_CheckRoot_Call) Run(run func(ctx context.Context, arg repo.RootAuthParams)) *MockRootControl_CheckRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.RootAuthParams
		if args[1] != nil {
			arg1 = args[1].(repo.RootAuthParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRootControl_CheckRoot_Call) Return(b bool, err error) *MockRootControl_CheckRoot_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRootControl_CheckRoot_Call) RunAndReturn(run func(ctx context.Context, arg repo.RootAuthParams) (bool, error)) *MockRootControl_CheckRoot_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAdmin provides a mock function for the type MockRootControl
func (_mock *MockRootControl) CreateAdmin(ctx context.Context, arg repo.CreateRootAdminParams) (repo.Token, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateAdmin")
	}

	var r0 repo.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateRootAdminParams) (repo.Token, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateRootAdminParams) repo.Token); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.CreateRootAdminParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRootControl_CreateAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAdmin'
type MockRootControl_CreateAdmin_Call struct {
	*mock.Call
}

// CreateAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.CreateRootAdminParams
func (_e *MockRootControl_Expecter) CreateAdmin(ctx interface{}, arg interface{}) *MockRootControl_CreateAdmin_Call {
	return &MockRootControl_CreateAdmin_Call{Call: _e.mock.On("CreateAdmin", ctx, arg)}
}

func (_c *MockRootControl_CreateAdmin_Call) Run(run func(ctx context.Context, arg repo.CreateRootAdminParams)) *MockRootControl_CreateAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.CreateRootAdminParams
		if args[1] != nil {
			arg1 = args[1].(repo.CreateRootAdminParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRootControl_CreateAdmin_Call) Return(token repo.Token, err error) *MockRootControl_CreateAdmin_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockRootControl_CreateAdmin_Call) RunAndReturn(run func(ctx context.Context, arg repo.CreateRootAdminParams) (repo.Token, error)) *MockRootControl_CreateAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// InitRoot provides a mock function for the type MockRootControl
func (_mock *MockRootControl) InitRoot(ctx context.Context, arg repo.CreateRootControlParams) (repo.Token, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InitRoot")
	}

	var r0 repo.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateRootControlParams) (repo.Token, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateRootControlParams) repo.Token); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.CreateRootControlParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRootControl_InitRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitRoot'
type MockRootControl_InitRoot_Call struct {
	*mock.Call
}

// InitRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.CreateRootControlParams
func (_e *MockRootControl_Expecter) InitRoot(ctx interface{}, arg interface{}) *MockRootControl_InitRoot_Call {
	return &MockRootControl_InitRoot_Call{Call: _e.mock.On("InitRoot", ctx, arg)}
}

func (_c *MockRootControl_InitRoot_Call) Run(run func(ctx context.Context, arg repo.CreateRootControlParams)) *MockRootControl_InitRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.CreateRootControlParams
		if args[1] != nil {
			arg1 = args[1].(repo.CreateRootControlParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRootControl_InitRoot_Call) Return(token repo.Token, err error) *MockRootControl_InitRoot_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockRootControl_InitRoot_Call) RunAndReturn(run func(ctx context.Context, arg repo.CreateRootControlParams) (repo.Token, error)) *MockRootControl_InitRoot_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAll provides a mock function for the type MockRootControl
func (_mock *MockRootControl) RevokeAll(ctx context.Context, arg repo.RootAuthParams) (int64, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAll")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.RootAuthParams) (int64, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.RootAuthParams) int64); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.RootAuthParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRootControl_RevokeAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAll'
type MockRootControl_RevokeAll_Call struct {
	*mock.Call
}

// RevokeAll is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.RootAuthParams
func (_e *MockRootControl_Expecter) RevokeAll(ctx interface{}, arg interface{}) *MockRootControl_RevokeAll_Call {
	return &MockRootControl_RevokeAll_Call{Call: _e.mock.On("RevokeAll", ctx, arg)}
}

func (_c *MockRootControl_RevokeAll_Call) Run(run func(ctx context.Context, arg repo.RootAuthParams)) *MockRootControl_RevokeAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.RootAuthParams
		if args[1] != nil {
			arg1 = args[1].(repo.RootAuthParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRootControl_RevokeAll_Call) Return(n int64, err error) *MockRootControl_RevokeAll_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRootControl_RevokeAll_Call) RunAndReturn(run func(ctx context.Context, arg repo.RootAuthParams) (int64, error)) *MockRootControl_RevokeAll_Call {
	_c.Call.Return(run)
	return _c
}
