// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContentRepository creates a new instance of MockContentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentRepository {
	mock := &MockContentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContentRepository is an autogenerated mock type for the ContentRepository type
type MockContentRepository struct {
	mock.Mock
}

type MockContentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentRepository) EXPECT() *MockContentRepository_Expecter {
	return &MockContentRepository_Expecter{mock: &_m.Mock}
}

// CreateContent provides a mock function for the type MockContentRepository
func (_mock *MockContentRepository) CreateContent(ctx context.Context, article model.ArticleContent) (string, error) {
	ret := _mock.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for CreateContent")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ArticleContent) (string, error)); ok {
		return returnFunc(ctx, article)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ArticleContent) string); ok {
		r0 = returnFunc(ctx, article)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ArticleContent) error); ok {
		r1 = returnFunc(ctx, article)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentRepository_CreateContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateContent'
type MockContentRepository_CreateContent_Call struct {
	*mock.Call
}

// CreateContent is a helper method to define mock.On call
//   - ctx context.Context
//   - article model.ArticleContent
func (_e *MockContentRepository_Expecter) CreateContent(ctx interface{}, article interface{}) *MockContentRepository_CreateContent_Call {
	return &MockContentRepository_CreateContent_Call{Call: _e.mock.On("CreateContent", ctx, article)}
}

func (_c *MockContentRepository_CreateContent_Call) Run(run func(ctx context.Context, article model.ArticleContent)) *MockContentRepository_CreateContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ArticleContent
		if args[1] != nil {
			arg1 = args[1].(model.ArticleContent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContentRepository_CreateContent_Call) Return(s string, err error) *MockContentRepository_CreateContent_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockContentRepository_CreateContent_Call) RunAndReturn(run func(ctx context.Context, article model.ArticleContent) (string, error)) *MockContentRepository_CreateContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetContentByID provides a mock function for the type MockContentRepository
func (_mock *MockContentRepository) GetContentByID(ctx context.Context, id string) (*model.ArticleContent, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetContentByID")
	}

	var r0 *model.ArticleContent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ArticleContent, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ArticleContent); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ArticleContent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentRepository_GetContentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContentByID'
type MockContentRepository_GetContentByID_Call struct {
	*mock.Call
}

// GetContentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockContentRepository_Expecter) GetContentByID(ctx interface{}, id interface{}) *MockContentRepository_GetContentByID_Call {
	return &MockContentRepository_GetContentByID_Call{Call: _e.mock.On("GetContentByID", ctx, id)}
}

func (_c *MockContentRepository_GetContentByID_Call) Run(run func(ctx context.Context, id string)) *MockContentRepository_GetContentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContentRepository_GetContentByID_Call) Return(articleContent *model.ArticleContent, err error) *MockContentRepository_GetContentByID_Call {
	_c.Call.Return(articleContent, err)
	return _c
}

func (_c *MockContentRepository_GetContentByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.ArticleContent, error)) *MockContentRepository_GetContentByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertSource provides a mock function for the type MockContentRepository
func (_mock *MockContentRepository) UpsertSource(ctx context.Context, source model.Source) (int, error) {
	ret := _mock.Called(ctx, source)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSource")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Source) (int, error)); ok {
		return returnFunc(ctx, source)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Source) int); ok {
		r0 = returnFunc(ctx, source)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Source) error); ok {
		r1 = returnFunc(ctx, source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentRepository_UpsertSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertSource'
type MockContentRepository_UpsertSource_Call struct {
	*mock.Call
}

// UpsertSource is a helper method to define mock.On call
//   - ctx context.Context
//   - source model.Source
func (_e *MockContentRepository_Expecter) UpsertSource(ctx interface{}, source interface{}) *MockContentRepository_UpsertSource_Call {
	return &MockContentRepository_UpsertSource_Call{Call: _e.mock.On("UpsertSource", ctx, source)}
}

func (_c *MockContentRepository_UpsertSource_Call) Run(run func(ctx context.Context, source model.Source)) *MockContentRepository_UpsertSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Source
		if args[1] != nil {
			arg1 = args[1].(model.Source)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContentRepository_UpsertSource_Call) Return(n int, err error) *MockContentRepository_UpsertSource_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockContentRepository_UpsertSource_Call) RunAndReturn(run func(ctx context.Context, source model.Source) (int, error)) *MockContentRepository_UpsertSource_Call {
	_c.Call.Return(run)
	return _c
}
