// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/repo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmbeddings creates a new instance of MockEmbeddings. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddings(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddings {
	mock := &MockEmbeddings{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmbeddings is an autogenerated mock type for the Embeddings type
type MockEmbeddings struct {
	mock.Mock
}

type MockEmbeddings_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddings) EXPECT() *MockEmbeddings_Expecter {
	return &MockEmbeddings_Expecter{mock: &_m.Mock}
}

// CreateCandidateEmbedding provides a mock function for the type MockEmbeddings
func (_mock *MockEmbeddings) CreateCandidateEmbedding(ctx context.Context, arg repo.CreateCandidateEmbeddingParams) (repo.CandidateEmbedding, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateCandidateEmbedding")
	}

	var r0 repo.CandidateEmbedding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateCandidateEmbeddingParams) (repo.CandidateEmbedding, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateCandidateEmbeddingParams) repo.CandidateEmbedding); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.CandidateEmbedding)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.CreateCandidateEmbeddingParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddings_CreateCandidateEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCandidateEmbedding'
type MockEmbeddings_CreateCandidateEmbedding_Call struct {
	*mock.Call
}

// CreateCandidateEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.CreateCandidateEmbeddingParams
func (_e *MockEmbeddings_Expecter) CreateCandidateEmbedding(ctx interface{}, arg interface{}) *MockEmbeddings_CreateCandidateEmbedding_Call {
	return &MockEmbeddings_CreateCandidateEmbedding_Call{Call: _e.mock.On("CreateCandidateEmbedding", ctx, arg)}
}

func (_c *MockEmbeddings_CreateCandidateEmbedding_Call) Run(run func(ctx context.Context, arg repo.CreateCandidateEmbeddingParams)) *MockEmbeddings_CreateCandidateEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.CreateCandidateEmbeddingParams
		if args[1] != nil {
			arg1 = args[1].(repo.CreateCandidateEmbeddingParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddings_CreateCandidateEmbedding_Call) Return(candidateEmbedding repo.CandidateEmbedding, err error) *MockEmbeddings_CreateCandidateEmbedding_Call {
	_c.Call.Return(candidateEmbedding, err)
	return _c
}

func (_c *MockEmbeddings_CreateCandidateEmbedding_Call) RunAndReturn(run func(ctx context.Context, arg repo.CreateCandidateEmbeddingParams) (repo.CandidateEmbedding, error)) *MockEmbeddings_CreateCandidateEmbedding_Call {
	_c.Call.Return(run)
	return _c
}

// CreateContentEmbedding provides a mock function for the type MockEmbeddings
func (_mock *MockEmbeddings) CreateContentEmbedding(ctx context.Context, arg repo.CreateContentEmbeddingParams) (repo.ContentEmbedding, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateContentEmbedding")
	}

	var r0 repo.ContentEmbedding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateContentEmbeddingParams) (repo.ContentEmbedding, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.CreateContentEmbeddingParams) repo.ContentEmbedding); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.ContentEmbedding)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.CreateContentEmbeddingParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddings_CreateContentEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateContentEmbedding'
type MockEmbeddings_CreateContentEmbedding_Call struct {
	*mock.Call
}

// CreateContentEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.CreateContentEmbeddingParams
func (_e *MockEmbeddings_Expecter) CreateContentEmbedding(ctx interface{}, arg interface{}) *MockEmbeddings_CreateContentEmbedding_Call {
	return &MockEmbeddings_CreateContentEmbedding_Call{Call: _e.mock.On("CreateContentEmbedding", ctx, arg)}
}

func (_c *MockEmbeddings_CreateContentEmbedding_Call) Run(run func(ctx context.Context, arg repo.CreateContentEmbeddingParams)) *MockEmbeddings_CreateContentEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.CreateContentEmbeddingParams
		if args[1] != nil {
			arg1 = args[1].(repo.CreateContentEmbeddingParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddings_CreateContentEmbedding_Call) Return(contentEmbedding repo.ContentEmbedding, err error) *MockEmbeddings_CreateContentEmbedding_Call {
	_c.Call.Return(contentEmbedding, err)
	return _c
}

func (_c *MockEmbeddings_CreateContentEmbedding_Call) RunAndReturn(run func(ctx context.Context, arg repo.CreateContentEmbeddingParams) (repo.ContentEmbedding, error)) *MockEmbeddings_CreateContentEmbedding_Call {
	_c.Call.Return(run)
	return _c
}

// GetModelByID provides a mock function for the type MockEmbeddings
func (_mock *MockEmbeddings) GetModelByID(ctx context.Context, id int16) (repo.Model, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetModelByID")
	}

	var r0 repo.Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) (repo.Model, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) repo.Model); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repo.Model)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int16) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddings_GetModelByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModelByID'
type MockEmbeddings_GetModelByID_Call struct {
	*mock.Call
}

// GetModelByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int16
func (_e *MockEmbeddings_Expecter) GetModelByID(ctx interface{}, id interface{}) *MockEmbeddings_GetModelByID_Call {
	return &MockEmbeddings_GetModelByID_Call{Call: _e.mock.On("GetModelByID", ctx, id)}
}

func (_c *MockEmbeddings_GetModelByID_Call) Run(run func(ctx context.Context, id int16)) *MockEmbeddings_GetModelByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int16
		if args[1] != nil {
			arg1 = args[1].(int16)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddings_GetModelByID_Call) Return(model repo.Model, err error) *MockEmbeddings_GetModelByID_Call {
	_c.Call.Return(model, err)
	return _c
}

func (_c *MockEmbeddings_GetModelByID_Call) RunAndReturn(run func(ctx context.Context, id int16) (repo.Model, error)) *MockEmbeddings_GetModelByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetModelByNameAndType provides a mock function for the type MockEmbeddings
func (_mock *MockEmbeddings) GetModelByNameAndType(ctx context.Context, name string, modelType string) (repo.Model, error) {
	ret := _mock.Called(ctx, name, modelType)

	if len(ret) == 0 {
		panic("no return value specified for GetModelByNameAndType")
	}

	var r0 repo.Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (repo.Model, error)); ok {
		return returnFunc(ctx, name, modelType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) repo.Model); ok {
		r0 = returnFunc(ctx, name, modelType)
	} else {
		r0 = ret.Get(0).(repo.Model)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, modelType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddings_GetModelByNameAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModelByNameAndType'
type MockEmbeddings_GetModelByNameAndType_Call struct {
	*mock.Call
}

// GetModelByNameAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - modelType string
func (_e *MockEmbeddings_Expecter) GetModelByNameAndType(ctx interface{}, name interface{}, modelType interface{}) *MockEmbeddings_GetModelByNameAndType_Call {
	return &MockEmbeddings_GetModelByNameAndType_Call{Call: _e.mock.On("GetModelByNameAndType", ctx, name, modelType)}
}

func (_c *MockEmbeddings_GetModelByNameAndType_Call) Run(run func(ctx context.Context, name string, modelType string)) *MockEmbeddings_GetModelByNameAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbeddings_GetModelByNameAndType_Call) Return(model repo.Model, err error) *MockEmbeddings_GetModelByNameAndType_Call {
	_c.Call.Return(model, err)
	return _c
}

func (_c *MockEmbeddings_GetModelByNameAndType_Call) RunAndReturn(run func(ctx context.Context, name string, modelType string) (repo.Model, error)) *MockEmbeddings_GetModelByNameAndType_Call {
	_c.Call.Return(run)
	return _c
}
