// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDiscoveryRepository creates a new instance of MockDiscoveryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDiscoveryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDiscoveryRepository {
	mock := &MockDiscoveryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDiscoveryRepository is an autogenerated mock type for the DiscoveryRepository type
type MockDiscoveryRepository struct {
	mock.Mock
}

type MockDiscoveryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDiscoveryRepository) EXPECT() *MockDiscoveryRepository_Expecter {
	return &MockDiscoveryRepository_Expecter{mock: &_m.Mock}
}

// IsURLProcessed provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) IsURLProcessed(ctx context.Context, url string) (bool, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for IsURLProcessed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, url)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiscoveryRepository_IsURLProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsURLProcessed'
type MockDiscoveryRepository_IsURLProcessed_Call struct {
	*mock.Call
}

// IsURLProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockDiscoveryRepository_Expecter) IsURLProcessed(ctx interface{}, url interface{}) *MockDiscoveryRepository_IsURLProcessed_Call {
	return &MockDiscoveryRepository_IsURLProcessed_Call{Call: _e.mock.On("IsURLProcessed", ctx, url)}
}

func (_c *MockDiscoveryRepository_IsURLProcessed_Call) Run(run func(ctx context.Context, url string)) *MockDiscoveryRepository_IsURLProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_IsURLProcessed_Call) Return(b bool, err error) *MockDiscoveryRepository_IsURLProcessed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDiscoveryRepository_IsURLProcessed_Call) RunAndReturn(run func(ctx context.Context, url string) (bool, error)) *MockDiscoveryRepository_IsURLProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// SaveActiveSearchTask provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) SaveActiveSearchTask(ctx context.Context, task model.Task) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for SaveActiveSearchTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Task) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDiscoveryRepository_SaveActiveSearchTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveActiveSearchTask'
type MockDiscoveryRepository_SaveActiveSearchTask_Call struct {
	*mock.Call
}

// SaveActiveSearchTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task model.SearchTask
func (_e *MockDiscoveryRepository_Expecter) SaveActiveSearchTask(ctx interface{}, task interface{}) *MockDiscoveryRepository_SaveActiveSearchTask_Call {
	return &MockDiscoveryRepository_SaveActiveSearchTask_Call{Call: _e.mock.On("SaveActiveSearchTask", ctx, task)}
}

func (_c *MockDiscoveryRepository_SaveActiveSearchTask_Call) Run(run func(ctx context.Context, task model.Task)) *MockDiscoveryRepository_SaveActiveSearchTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Task
		if args[1] != nil {
			arg1 = args[1].(model.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_SaveActiveSearchTask_Call) Return(err error) *MockDiscoveryRepository_SaveActiveSearchTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDiscoveryRepository_SaveActiveSearchTask_Call) RunAndReturn(run func(ctx context.Context, task model.Task) error) *MockDiscoveryRepository_SaveActiveSearchTask_Call {
	_c.Call.Return(run)
	return _c
}

// StoreDiscoveryResult provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) StoreDiscoveryResult(ctx context.Context, buffer model.Candidates) error {
	ret := _mock.Called(ctx, buffer)

	if len(ret) == 0 {
		panic("no return value specified for StoreDiscoveryResult")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Candidates) error); ok {
		r0 = returnFunc(ctx, buffer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDiscoveryRepository_StoreDiscoveryResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreDiscoveryResult'
type MockDiscoveryRepository_StoreDiscoveryResult_Call struct {
	*mock.Call
}

// StoreDiscoveryResult is a helper method to define mock.On call
//   - ctx context.Context
//   - buffer model.Candidates
func (_e *MockDiscoveryRepository_Expecter) StoreDiscoveryResult(ctx interface{}, buffer interface{}) *MockDiscoveryRepository_StoreDiscoveryResult_Call {
	return &MockDiscoveryRepository_StoreDiscoveryResult_Call{Call: _e.mock.On("StoreDiscoveryResult", ctx, buffer)}
}

func (_c *MockDiscoveryRepository_StoreDiscoveryResult_Call) Run(run func(ctx context.Context, buffer model.Candidates)) *MockDiscoveryRepository_StoreDiscoveryResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Candidates
		if args[1] != nil {
			arg1 = args[1].(model.Candidates)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_StoreDiscoveryResult_Call) Return(err error) *MockDiscoveryRepository_StoreDiscoveryResult_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDiscoveryRepository_StoreDiscoveryResult_Call) RunAndReturn(run func(ctx context.Context, buffer model.Candidates) error) *MockDiscoveryRepository_StoreDiscoveryResult_Call {
	_c.Call.Return(run)
	return _c
}
