// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/repo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockModels creates a new instance of MockModels. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModels(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModels {
	mock := &MockModels{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockModels is an autogenerated mock type for the Models type
type MockModels struct {
	mock.Mock
}

type MockModels_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModels) EXPECT() *MockModels_Expecter {
	return &MockModels_Expecter{mock: &_m.Mock}
}

// GetAnalyzerByName provides a mock function for the type MockModels
func (_mock *MockModels) GetAnalyzerByName(ctx context.Context, name string) (repo.Model, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalyzerByName")
	}

	var r0 repo.Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repo.Model, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repo.Model); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(repo.Model)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockModels_GetAnalyzerByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnalyzerByName'
type MockModels_GetAnalyzerByName_Call struct {
	*mock.Call
}

// GetAnalyzerByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockModels_Expecter) GetAnalyzerByName(ctx interface{}, name interface{}) *MockModels_GetAnalyzerByName_Call {
	return &MockModels_GetAnalyzerByName_Call{Call: _e.mock.On("GetAnalyzerByName", ctx, name)}
}

func (_c *MockModels_GetAnalyzerByName_Call) Run(run func(ctx context.Context, name string)) *MockModels_GetAnalyzerByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockModels_GetAnalyzerByName_Call) Return(model repo.Model, err error) *MockModels_GetAnalyzerByName_Call {
	_c.Call.Return(model, err)
	return _c
}

func (_c *MockModels_GetAnalyzerByName_Call) RunAndReturn(run func(ctx context.Context, name string) (repo.Model, error)) *MockModels_GetAnalyzerByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmbedderByName provides a mock function for the type MockModels
func (_mock *MockModels) GetEmbedderByName(ctx context.Context, name string) (repo.Model, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetEmbedderByName")
	}

	var r0 repo.Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repo.Model, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repo.Model); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(repo.Model)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockModels_GetEmbedderByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbedderByName'
type MockModels_GetEmbedderByName_Call struct {
	*mock.Call
}

// GetEmbedderByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockModels_Expecter) GetEmbedderByName(ctx interface{}, name interface{}) *MockModels_GetEmbedderByName_Call {
	return &MockModels_GetEmbedderByName_Call{Call: _e.mock.On("GetEmbedderByName", ctx, name)}
}

func (_c *MockModels_GetEmbedderByName_Call) Run(run func(ctx context.Context, name string)) *MockModels_GetEmbedderByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockModels_GetEmbedderByName_Call) Return(model repo.Model, err error) *MockModels_GetEmbedderByName_Call {
	_c.Call.Return(model, err)
	return _c
}

func (_c *MockModels_GetEmbedderByName_Call) RunAndReturn(run func(ctx context.Context, name string) (repo.Model, error)) *MockModels_GetEmbedderByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetExtractorByName provides a mock function for the type MockModels
func (_mock *MockModels) GetExtractorByName(ctx context.Context, name string) (repo.Model, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetExtractorByName")
	}

	var r0 repo.Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repo.Model, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repo.Model); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(repo.Model)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockModels_GetExtractorByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExtractorByName'
type MockModels_GetExtractorByName_Call struct {
	*mock.Call
}

// GetExtractorByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockModels_Expecter) GetExtractorByName(ctx interface{}, name interface{}) *MockModels_GetExtractorByName_Call {
	return &MockModels_GetExtractorByName_Call{Call: _e.mock.On("GetExtractorByName", ctx, name)}
}

func (_c *MockModels_GetExtractorByName_Call) Run(run func(ctx context.Context, name string)) *MockModels_GetExtractorByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockModels_GetExtractorByName_Call) Return(model repo.Model, err error) *MockModels_GetExtractorByName_Call {
	_c.Call.Return(model, err)
	return _c
}

func (_c *MockModels_GetExtractorByName_Call) RunAndReturn(run func(ctx context.Context, name string) (repo.Model, error)) *MockModels_GetExtractorByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetModelByID provides a mock function for the type MockModels
func (_mock *MockModels) GetModelByID(ctx context.Context, id int16) (repo.Model, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetModelByID")
	}

	var r0 repo.Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) (repo.Model, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) repo.Model); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repo.Model)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int16) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockModels_GetModelByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModelByID'
type MockModels_GetModelByID_Call struct {
	*mock.Call
}

// GetModelByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int16
func (_e *MockModels_Expecter) GetModelByID(ctx interface{}, id interface{}) *MockModels_GetModelByID_Call {
	return &MockModels_GetModelByID_Call{Call: _e.mock.On("GetModelByID", ctx, id)}
}

func (_c *MockModels_GetModelByID_Call) Run(run func(ctx context.Context, id int16)) *MockModels_GetModelByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int16
		if args[1] != nil {
			arg1 = args[1].(int16)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockModels_GetModelByID_Call) Return(model repo.Model, err error) *MockModels_GetModelByID_Call {
	_c.Call.Return(model, err)
	return _c
}

func (_c *MockModels_GetModelByID_Call) RunAndReturn(run func(ctx context.Context, id int16) (repo.Model, error)) *MockModels_GetModelByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetModelByNameAndType provides a mock function for the type MockModels
func (_mock *MockModels) GetModelByNameAndType(ctx context.Context, name string, modelType string) (repo.Model, error) {
	ret := _mock.Called(ctx, name, modelType)

	if len(ret) == 0 {
		panic("no return value specified for GetModelByNameAndType")
	}

	var r0 repo.Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (repo.Model, error)); ok {
		return returnFunc(ctx, name, modelType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) repo.Model); ok {
		r0 = returnFunc(ctx, name, modelType)
	} else {
		r0 = ret.Get(0).(repo.Model)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, modelType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockModels_GetModelByNameAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModelByNameAndType'
type MockModels_GetModelByNameAndType_Call struct {
	*mock.Call
}

// GetModelByNameAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - modelType string
func (_e *MockModels_Expecter) GetModelByNameAndType(ctx interface{}, name interface{}, modelType interface{}) *MockModels_GetModelByNameAndType_Call {
	return &MockModels_GetModelByNameAndType_Call{Call: _e.mock.On("GetModelByNameAndType", ctx, name, modelType)}
}

func (_c *MockModels_GetModelByNameAndType_Call) Run(run func(ctx context.Context, name string, modelType string)) *MockModels_GetModelByNameAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockModels_GetModelByNameAndType_Call) Return(model repo.Model, err error) *MockModels_GetModelByNameAndType_Call {
	_c.Call.Return(model, err)
	return _c
}

func (_c *MockModels_GetModelByNameAndType_Call) RunAndReturn(run func(ctx context.Context, name string, modelType string) (repo.Model, error)) *MockModels_GetModelByNameAndType_Call {
	_c.Call.Return(run)
	return _c
}
