// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/repo"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReports creates a new instance of MockReports. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReports(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReports {
	mock := &MockReports{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReports is an autogenerated mock type for the Reports type
type MockReports struct {
	mock.Mock
}

type MockReports_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReports) EXPECT() *MockReports_Expecter {
	return &MockReports_Expecter{mock: &_m.Mock}
}

// BeginRemoval provides a mock function for the type MockReports
func (_mock *MockReports) BeginRemoval(ctx context.Context, arg repo.BeginReportRemovalParams) (repo.Report, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for BeginRemoval")
	}

	var r0 repo.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.BeginReportRemovalParams) (repo.Report, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.BeginReportRemovalParams) repo.Report); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.BeginReportRemovalParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReports_BeginRemoval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginRemoval'
type MockReports_BeginRemoval_Call struct {
	*mock.Call
}

// BeginRemoval is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.BeginReportRemovalParams
func (_e *MockReports_Expecter) BeginRemoval(ctx interface{}, arg interface{}) *MockReports_BeginRemoval_Call {
	return &MockReports_BeginRemoval_Call{Call: _e.mock.On("BeginRemoval", ctx, arg)}
}

func (_c *MockReports_BeginRemoval_Call) Run(run func(ctx context.Context, arg repo.BeginReportRemovalParams)) *MockReports_BeginRemoval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.BeginReportRemovalParams
		if args[1] != nil {
			arg1 = args[1].(repo.BeginReportRemovalParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReports_BeginRemoval_Call) Return(report repo.Report, err error) *MockReports_BeginRemoval_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockReports_BeginRemoval_Call) RunAndReturn(run func(ctx context.Context, arg repo.BeginReportRemovalParams) (repo.Report, error)) *MockReports_BeginRemoval_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureExecution provides a mock function for the type MockReports
func (_mock *MockReports) EnsureExecution(ctx context.Context, id uuid.UUID, fingerprint string) error {
	ret := _mock.Called(ctx, id, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for EnsureExecution")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, fingerprint)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReports_EnsureExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureExecution'
type MockReports_EnsureExecution_Call struct {
	*mock.Call
}

// EnsureExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - fingerprint string
func (_e *MockReports_Expecter) EnsureExecution(ctx interface{}, id interface{}, fingerprint interface{}) *MockReports_EnsureExecution_Call {
	return &MockReports_EnsureExecution_Call{Call: _e.mock.On("EnsureExecution", ctx, id, fingerprint)}
}

func (_c *MockReports_EnsureExecution_Call) Run(run func(ctx context.Context, id uuid.UUID, fingerprint string)) *MockReports_EnsureExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReports_EnsureExecution_Call) Return(err error) *MockReports_EnsureExecution_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReports_EnsureExecution_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, fingerprint string) error) *MockReports_EnsureExecution_Call {
	_c.Call.Return(run)
	return _c
}

// FindCacheHit provides a mock function for the type MockReports
func (_mock *MockReports) FindCacheHit(ctx context.Context, id uuid.UUID) (repo.Report, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindCacheHit")
	}

	var r0 repo.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repo.Report, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repo.Report); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repo.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReports_FindCacheHit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCacheHit'
type MockReports_FindCacheHit_Call struct {
	*mock.Call
}

// FindCacheHit is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockReports_Expecter) FindCacheHit(ctx interface{}, id interface{}) *MockReports_FindCacheHit_Call {
	return &MockReports_FindCacheHit_Call{Call: _e.mock.On("FindCacheHit", ctx, id)}
}

func (_c *MockReports_FindCacheHit_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockReports_FindCacheHit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReports_FindCacheHit_Call) Return(report repo.Report, err error) *MockReports_FindCacheHit_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockReports_FindCacheHit_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (repo.Report, error)) *MockReports_FindCacheHit_Call {
	_c.Call.Return(run)
	return _c
}

// GetByExecutionID provides a mock function for the type MockReports
func (_mock *MockReports) GetByExecutionID(ctx context.Context, id uuid.UUID) (repo.Report, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByExecutionID")
	}

	var r0 repo.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repo.Report, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repo.Report); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repo.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReports_GetByExecutionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByExecutionID'
type MockReports_GetByExecutionID_Call struct {
	*mock.Call
}

// GetByExecutionID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockReports_Expecter) GetByExecutionID(ctx interface{}, id interface{}) *MockReports_GetByExecutionID_Call {
	return &MockReports_GetByExecutionID_Call{Call: _e.mock.On("GetByExecutionID", ctx, id)}
}

func (_c *MockReports_GetByExecutionID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockReports_GetByExecutionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReports_GetByExecutionID_Call) Return(report repo.Report, err error) *MockReports_GetByExecutionID_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockReports_GetByExecutionID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (repo.Report, error)) *MockReports_GetByExecutionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockReports
func (_mock *MockReports) GetByID(ctx context.Context, id uuid.UUID) (repo.Report, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 repo.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repo.Report, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repo.Report); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repo.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReports_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockReports_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockReports_Expecter) GetByID(ctx interface{}, id interface{}) *MockReports_GetByID_Call {
	return &MockReports_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockReports_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockReports_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReports_GetByID_Call) Return(report repo.Report, err error) *MockReports_GetByID_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockReports_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (repo.Report, error)) *MockReports_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCorrupt provides a mock function for the type MockReports
func (_mock *MockReports) MarkCorrupt(ctx context.Context, arg repo.MarkReportCorruptParams) (bool, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for MarkCorrupt")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.MarkReportCorruptParams) (bool, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.MarkReportCorruptParams) bool); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.MarkReportCorruptParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReports_MarkCorrupt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCorrupt'
type MockReports_MarkCorrupt_Call struct {
	*mock.Call
}

// MarkCorrupt is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.MarkReportCorruptParams
func (_e *MockReports_Expecter) MarkCorrupt(ctx interface{}, arg interface{}) *MockReports_MarkCorrupt_Call {
	return &MockReports_MarkCorrupt_Call{Call: _e.mock.On("MarkCorrupt", ctx, arg)}
}

func (_c *MockReports_MarkCorrupt_Call) Run(run func(ctx context.Context, arg repo.MarkReportCorruptParams)) *MockReports_MarkCorrupt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.MarkReportCorruptParams
		if args[1] != nil {
			arg1 = args[1].(repo.MarkReportCorruptParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReports_MarkCorrupt_Call) Return(b bool, err error) *MockReports_MarkCorrupt_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockReports_MarkCorrupt_Call) RunAndReturn(run func(ctx context.Context, arg repo.MarkReportCorruptParams) (bool, error)) *MockReports_MarkCorrupt_Call {
	_c.Call.Return(run)
	return _c
}

// MarkMissing provides a mock function for the type MockReports
func (_mock *MockReports) MarkMissing(ctx context.Context, id uuid.UUID, requestID *string) (bool, error) {
	ret := _mock.Called(ctx, id, requestID)

	if len(ret) == 0 {
		panic("no return value specified for MarkMissing")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string) (bool, error)); ok {
		return returnFunc(ctx, id, requestID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string) bool); ok {
		r0 = returnFunc(ctx, id, requestID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string) error); ok {
		r1 = returnFunc(ctx, id, requestID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReports_MarkMissing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkMissing'
type MockReports_MarkMissing_Call struct {
	*mock.Call
}

// MarkMissing is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - requestID *string
func (_e *MockReports_Expecter) MarkMissing(ctx interface{}, id interface{}, requestID interface{}) *MockReports_MarkMissing_Call {
	return &MockReports_MarkMissing_Call{Call: _e.mock.On("MarkMissing", ctx, id, requestID)}
}

func (_c *MockReports_MarkMissing_Call) Run(run func(ctx context.Context, id uuid.UUID, requestID *string)) *MockReports_MarkMissing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReports_MarkMissing_Call) Return(b bool, err error) *MockReports_MarkMissing_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockReports_MarkMissing_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, requestID *string) (bool, error)) *MockReports_MarkMissing_Call {
	_c.Call.Return(run)
	return _c
}

// RecordAuditEvent provides a mock function for the type MockReports
func (_mock *MockReports) RecordAuditEvent(ctx context.Context, arg repo.ReportAuditEventParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for RecordAuditEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.ReportAuditEventParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReports_RecordAuditEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordAuditEvent'
type MockReports_RecordAuditEvent_Call struct {
	*mock.Call
}

// RecordAuditEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.ReportAuditEventParams
func (_e *MockReports_Expecter) RecordAuditEvent(ctx interface{}, arg interface{}) *MockReports_RecordAuditEvent_Call {
	return &MockReports_RecordAuditEvent_Call{Call: _e.mock.On("RecordAuditEvent", ctx, arg)}
}

func (_c *MockReports_RecordAuditEvent_Call) Run(run func(ctx context.Context, arg repo.ReportAuditEventParams)) *MockReports_RecordAuditEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.ReportAuditEventParams
		if args[1] != nil {
			arg1 = args[1].(repo.ReportAuditEventParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReports_RecordAuditEvent_Call) Return(err error) *MockReports_RecordAuditEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReports_RecordAuditEvent_Call) RunAndReturn(run func(ctx context.Context, arg repo.ReportAuditEventParams) error) *MockReports_RecordAuditEvent_Call {
	_c.Call.Return(run)
	return _c
}
