interval: 3s
health-port: 8091
batch-size: 100
kinds:
  - PAGE_FETCH
lock-key: prism:scheduler:PAGE_FETCH:lock
media-quota: 30
buffer: 10
rate-limit-config: /app/assets/scheduler/ratelimits/scheduler.yaml
messenger-type: nats
nats-host: nats
nats-port: 4222
postgres:
  host: postgres
  port: 5432
  username: prism
  db: prism
  sslmode: disable
valkey:
  host: valkey
  port: 6379
  username: prism
  db: 0
telemetry:
  enabled: true
  service-name: prism.scheduler.fast
  environment: local
  endpoint: otel-collector:4317
  insecure: true
  sample-ratio: 1
  timeout: 10s
logger:
  level: info
  console:
    enable: true
  file:
    enable: true
    file: /logs/scheduler-fast.json
  otel:
    url: otel-collector:4317
    insecure: true
    timeout: 10s
