interval: 1m
health-port: 8090
batch-size: 100
kinds:
  - DIRECTORY_FETCH
  - KEYWORD_SEARCH
lock-key: prism:scheduler:DIRECTORY_FETCH+KEYWORD_SEARCH:lock
buffer: 10
rate-limit-config: /app/assets/scheduler/ratelimits/scheduler.yaml
messenger-type: nats
nats-host: nats
nats-port: 4222
postgres:
  host: '{{ env "POSTGRES_HOST" "postgres" }}'
  port: {{ env "POSTGRES_PORT" "5432" }}
  username: '{{ env "POSTGRES_APP_USER" "prism" }}'
  db: '{{ env "POSTGRES_APP_DB" "prism" }}'
  sslmode: disable
  metrics-enabled: true
valkey:
  host: '{{ env "VALKEY_HOST" "valkey" }}'
  port: {{ env "VALKEY_PORT" "6379" }}
  username: '{{ env "VALKEY_APP_USER" "prism" }}'
  db: 0
telemetry:
  enabled: {{ env "PRISM_WORKER_OTEL_ENABLED" "true" }}
  service-name: prism.scheduler.slow
  environment: local
  endpoint: '{{ env "OTEL_COLLECTOR_ENDPOINT" "otel-collector:4317" }}'
  insecure: true
  sample-ratio: 1
  timeout: 10s
logger:
  level: info
  console:
    enable: true
  file:
    enable: true
    file: /logs/app.log
    max-size: 10MiB
    max-files: 5
  otel:
    url: '{{ env "OTEL_COLLECTOR_ENDPOINT" "otel-collector:4317" }}'
    insecure: true
    timeout: 10s
