// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis_runs.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAnalysisRunItems = `-- name: CancelAnalysisRunItems :exec
UPDATE fetch_items
SET snapshot_status = 'CANCELLED'
WHERE fetch_id = $1
  AND snapshot_status IS DISTINCT FROM 'CANCELLED'
`

func (q *Queries) CancelAnalysisRunItems(ctx context.Context, fetchID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelAnalysisRunItems, fetchID)
	return err
}

const createAnalysisRun = `-- name: CreateAnalysisRun :one
INSERT INTO analysis_runs (
    id,
    user_id,
    fetch_id,
    topic,
    brief,
    fetch_failure_policy,
    status,
    original_selected_candidate_ids,
    unavailable_candidate_ids
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, user_id, fetch_id, topic, brief, fetch_failure_policy, status, original_selected_candidate_ids, unavailable_candidate_ids, ready_candidate_ids, ready_content_ids, failed_candidate_ids, root_batch_id, failure_code, confirmed_at, created_at, updated_at, execution_id, report_id
`

type CreateAnalysisRunParams struct {
	ID                           uuid.UUID   `db:"id" json:"id"`
	UserID                       pgtype.UUID `db:"user_id" json:"user_id"`
	FetchID                      uuid.UUID   `db:"fetch_id" json:"fetch_id"`
	Topic                        string      `db:"topic" json:"topic"`
	Brief                        string      `db:"brief" json:"brief"`
	FetchFailurePolicy           string      `db:"fetch_failure_policy" json:"fetch_failure_policy"`
	Status                       string      `db:"status" json:"status"`
	OriginalSelectedCandidateIds []uuid.UUID `db:"original_selected_candidate_ids" json:"original_selected_candidate_ids"`
	UnavailableCandidateIds      []uuid.UUID `db:"unavailable_candidate_ids" json:"unavailable_candidate_ids"`
}

func (q *Queries) CreateAnalysisRun(ctx context.Context, arg CreateAnalysisRunParams) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, createAnalysisRun,
		arg.ID,
		arg.UserID,
		arg.FetchID,
		arg.Topic,
		arg.Brief,
		arg.FetchFailurePolicy,
		arg.Status,
		arg.OriginalSelectedCandidateIds,
		arg.UnavailableCandidateIds,
	)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FetchID,
		&i.Topic,
		&i.Brief,
		&i.FetchFailurePolicy,
		&i.Status,
		&i.OriginalSelectedCandidateIds,
		&i.UnavailableCandidateIds,
		&i.ReadyCandidateIds,
		&i.ReadyContentIds,
		&i.FailedCandidateIds,
		&i.RootBatchID,
		&i.FailureCode,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionID,
		&i.ReportID,
	)
	return i, err
}

const getAnalysisRunByFetchID = `-- name: GetAnalysisRunByFetchID :one
SELECT id, user_id, fetch_id, topic, brief, fetch_failure_policy, status, original_selected_candidate_ids, unavailable_candidate_ids, ready_candidate_ids, ready_content_ids, failed_candidate_ids, root_batch_id, failure_code, confirmed_at, created_at, updated_at, execution_id, report_id FROM analysis_runs WHERE fetch_id = $1
`

func (q *Queries) GetAnalysisRunByFetchID(ctx context.Context, fetchID uuid.UUID) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, getAnalysisRunByFetchID, fetchID)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FetchID,
		&i.Topic,
		&i.Brief,
		&i.FetchFailurePolicy,
		&i.Status,
		&i.OriginalSelectedCandidateIds,
		&i.UnavailableCandidateIds,
		&i.ReadyCandidateIds,
		&i.ReadyContentIds,
		&i.FailedCandidateIds,
		&i.RootBatchID,
		&i.FailureCode,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionID,
		&i.ReportID,
	)
	return i, err
}

const getAnalysisRunByID = `-- name: GetAnalysisRunByID :one
SELECT id, user_id, fetch_id, topic, brief, fetch_failure_policy, status, original_selected_candidate_ids, unavailable_candidate_ids, ready_candidate_ids, ready_content_ids, failed_candidate_ids, root_batch_id, failure_code, confirmed_at, created_at, updated_at, execution_id, report_id FROM analysis_runs WHERE id = $1
`

func (q *Queries) GetAnalysisRunByID(ctx context.Context, id uuid.UUID) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, getAnalysisRunByID, id)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FetchID,
		&i.Topic,
		&i.Brief,
		&i.FetchFailurePolicy,
		&i.Status,
		&i.OriginalSelectedCandidateIds,
		&i.UnavailableCandidateIds,
		&i.ReadyCandidateIds,
		&i.ReadyContentIds,
		&i.FailedCandidateIds,
		&i.RootBatchID,
		&i.FailureCode,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionID,
		&i.ReportID,
	)
	return i, err
}

const listAnalysisRunItems = `-- name: ListAnalysisRunItems :many
SELECT
    i.candidate_id,
    i.task_id,
    i.snapshot_status,
    COALESCE(t.status::text, '') AS task_status,
    c.id AS content_id
FROM fetch_items i
LEFT JOIN tasks t ON t.id = i.task_id
LEFT JOIN contents c ON c.candidate_id = i.candidate_id AND c.deleted_at IS NULL
WHERE i.fetch_id = $1
  AND i.snapshot_status IS DISTINCT FROM 'CANCELLED'
ORDER BY i.created_at ASC
`

type ListAnalysisRunItemsRow struct {
	CandidateID    uuid.UUID   `db:"candidate_id" json:"candidate_id"`
	TaskID         pgtype.UUID `db:"task_id" json:"task_id"`
	SnapshotStatus pgtype.Text `db:"snapshot_status" json:"snapshot_status"`
	TaskStatus     interface{} `db:"task_status" json:"task_status"`
	ContentID      pgtype.UUID `db:"content_id" json:"content_id"`
}

func (q *Queries) ListAnalysisRunItems(ctx context.Context, fetchID uuid.UUID) ([]ListAnalysisRunItemsRow, error) {
	rows, err := q.db.Query(ctx, listAnalysisRunItems, fetchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalysisRunItemsRow
	for rows.Next() {
		var i ListAnalysisRunItemsRow
		if err := rows.Scan(
			&i.CandidateID,
			&i.TaskID,
			&i.SnapshotStatus,
			&i.TaskStatus,
			&i.ContentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAnalysisRunExecution = `-- name: SetAnalysisRunExecution :one
UPDATE analysis_runs
SET execution_id = COALESCE(execution_id, $1),
    updated_at = clock_timestamp()
WHERE id = $2
  AND (execution_id IS NULL OR execution_id = $1)
RETURNING id, user_id, fetch_id, topic, brief, fetch_failure_policy, status, original_selected_candidate_ids, unavailable_candidate_ids, ready_candidate_ids, ready_content_ids, failed_candidate_ids, root_batch_id, failure_code, confirmed_at, created_at, updated_at, execution_id, report_id
`

type SetAnalysisRunExecutionParams struct {
	ExecutionID pgtype.UUID `db:"execution_id" json:"execution_id"`
	ID          uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) SetAnalysisRunExecution(ctx context.Context, arg SetAnalysisRunExecutionParams) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, setAnalysisRunExecution, arg.ExecutionID, arg.ID)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FetchID,
		&i.Topic,
		&i.Brief,
		&i.FetchFailurePolicy,
		&i.Status,
		&i.OriginalSelectedCandidateIds,
		&i.UnavailableCandidateIds,
		&i.ReadyCandidateIds,
		&i.ReadyContentIds,
		&i.FailedCandidateIds,
		&i.RootBatchID,
		&i.FailureCode,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionID,
		&i.ReportID,
	)
	return i, err
}

const setAnalysisRunManifest = `-- name: SetAnalysisRunManifest :one
UPDATE analysis_runs
SET status = 'READY_TO_ANALYZE',
    ready_candidate_ids = $1,
    ready_content_ids = $2,
    failed_candidate_ids = $3,
    confirmed_at = NOW(),
    failure_code = NULL,
    updated_at = NOW()
WHERE id = $4
  AND status IN ('FETCHING', 'AWAITING_RESOLUTION')
RETURNING id, user_id, fetch_id, topic, brief, fetch_failure_policy, status, original_selected_candidate_ids, unavailable_candidate_ids, ready_candidate_ids, ready_content_ids, failed_candidate_ids, root_batch_id, failure_code, confirmed_at, created_at, updated_at, execution_id, report_id
`

type SetAnalysisRunManifestParams struct {
	ReadyCandidateIds  []uuid.UUID `db:"ready_candidate_ids" json:"ready_candidate_ids"`
	ReadyContentIds    []uuid.UUID `db:"ready_content_ids" json:"ready_content_ids"`
	FailedCandidateIds []uuid.UUID `db:"failed_candidate_ids" json:"failed_candidate_ids"`
	ID                 uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) SetAnalysisRunManifest(ctx context.Context, arg SetAnalysisRunManifestParams) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, setAnalysisRunManifest,
		arg.ReadyCandidateIds,
		arg.ReadyContentIds,
		arg.FailedCandidateIds,
		arg.ID,
	)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FetchID,
		&i.Topic,
		&i.Brief,
		&i.FetchFailurePolicy,
		&i.Status,
		&i.OriginalSelectedCandidateIds,
		&i.UnavailableCandidateIds,
		&i.ReadyCandidateIds,
		&i.ReadyContentIds,
		&i.FailedCandidateIds,
		&i.RootBatchID,
		&i.FailureCode,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionID,
		&i.ReportID,
	)
	return i, err
}

const setAnalysisRunRoot = `-- name: SetAnalysisRunRoot :one
UPDATE analysis_runs
SET root_batch_id = $1,
    status = 'ANALYZING',
    updated_at = NOW()
WHERE id = $2
RETURNING id, user_id, fetch_id, topic, brief, fetch_failure_policy, status, original_selected_candidate_ids, unavailable_candidate_ids, ready_candidate_ids, ready_content_ids, failed_candidate_ids, root_batch_id, failure_code, confirmed_at, created_at, updated_at, execution_id, report_id
`

type SetAnalysisRunRootParams struct {
	RootBatchID pgtype.UUID `db:"root_batch_id" json:"root_batch_id"`
	ID          uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) SetAnalysisRunRoot(ctx context.Context, arg SetAnalysisRunRootParams) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, setAnalysisRunRoot, arg.RootBatchID, arg.ID)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FetchID,
		&i.Topic,
		&i.Brief,
		&i.FetchFailurePolicy,
		&i.Status,
		&i.OriginalSelectedCandidateIds,
		&i.UnavailableCandidateIds,
		&i.ReadyCandidateIds,
		&i.ReadyContentIds,
		&i.FailedCandidateIds,
		&i.RootBatchID,
		&i.FailureCode,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionID,
		&i.ReportID,
	)
	return i, err
}

const setAnalysisRunStatus = `-- name: SetAnalysisRunStatus :one
UPDATE analysis_runs
SET status = $1,
    failed_candidate_ids = $2,
    failure_code = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, user_id, fetch_id, topic, brief, fetch_failure_policy, status, original_selected_candidate_ids, unavailable_candidate_ids, ready_candidate_ids, ready_content_ids, failed_candidate_ids, root_batch_id, failure_code, confirmed_at, created_at, updated_at, execution_id, report_id
`

type SetAnalysisRunStatusParams struct {
	Status             string      `db:"status" json:"status"`
	FailedCandidateIds []uuid.UUID `db:"failed_candidate_ids" json:"failed_candidate_ids"`
	FailureCode        pgtype.Text `db:"failure_code" json:"failure_code"`
	ID                 uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) SetAnalysisRunStatus(ctx context.Context, arg SetAnalysisRunStatusParams) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, setAnalysisRunStatus,
		arg.Status,
		arg.FailedCandidateIds,
		arg.FailureCode,
		arg.ID,
	)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FetchID,
		&i.Topic,
		&i.Brief,
		&i.FetchFailurePolicy,
		&i.Status,
		&i.OriginalSelectedCandidateIds,
		&i.UnavailableCandidateIds,
		&i.ReadyCandidateIds,
		&i.ReadyContentIds,
		&i.FailedCandidateIds,
		&i.RootBatchID,
		&i.FailureCode,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionID,
		&i.ReportID,
	)
	return i, err
}
