// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batches.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensurePipelineChildBatch = `-- name: EnsurePipelineChildBatch :one
INSERT INTO batches (id, source_type, trace_id, parent_id, parent_task_id, purpose)
VALUES ($1, $2, $3, $4, $5, 'ANALYZER_PIPELINE_STAGE')
ON CONFLICT (parent_task_id) WHERE parent_task_id IS NOT NULL DO UPDATE
SET updated_at = batches.updated_at
RETURNING id
`

type EnsurePipelineChildBatchParams struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	SourceType   SourceType  `db:"source_type" json:"source_type"`
	TraceID      pgtype.Text `db:"trace_id" json:"trace_id"`
	ParentID     pgtype.UUID `db:"parent_id" json:"parent_id"`
	ParentTaskID pgtype.UUID `db:"parent_task_id" json:"parent_task_id"`
}

func (q *Queries) EnsurePipelineChildBatch(ctx context.Context, arg EnsurePipelineChildBatchParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, ensurePipelineChildBatch,
		arg.ID,
		arg.SourceType,
		arg.TraceID,
		arg.ParentID,
		arg.ParentTaskID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const ensurePipelineRoot = `-- name: EnsurePipelineRoot :exec
INSERT INTO batches (
    id, source_type, trace_id, parent_id, purpose,
    pipeline_definition_hash, pipeline_idempotency_key, pipeline_request_fingerprint
)
VALUES (
    $1, $2, $3, $4,
    'ANALYZER_PIPELINE_ROOT', $5,
    $6, $7
)
ON CONFLICT (id) DO UPDATE
SET parent_id = COALESCE(batches.parent_id, EXCLUDED.parent_id),
    purpose = COALESCE(batches.purpose, EXCLUDED.purpose),
    pipeline_definition_hash = COALESCE(batches.pipeline_definition_hash, EXCLUDED.pipeline_definition_hash),
    pipeline_idempotency_key = COALESCE(batches.pipeline_idempotency_key, EXCLUDED.pipeline_idempotency_key),
    pipeline_request_fingerprint = COALESCE(batches.pipeline_request_fingerprint, EXCLUDED.pipeline_request_fingerprint)
`

type EnsurePipelineRootParams struct {
	ID                 uuid.UUID   `db:"id" json:"id"`
	SourceType         SourceType  `db:"source_type" json:"source_type"`
	TraceID            pgtype.Text `db:"trace_id" json:"trace_id"`
	ParentID           pgtype.UUID `db:"parent_id" json:"parent_id"`
	DefinitionHash     pgtype.Text `db:"definition_hash" json:"definition_hash"`
	IdempotencyKey     pgtype.Text `db:"idempotency_key" json:"idempotency_key"`
	RequestFingerprint pgtype.Text `db:"request_fingerprint" json:"request_fingerprint"`
}

func (q *Queries) EnsurePipelineRoot(ctx context.Context, arg EnsurePipelineRootParams) error {
	_, err := q.db.Exec(ctx, ensurePipelineRoot,
		arg.ID,
		arg.SourceType,
		arg.TraceID,
		arg.ParentID,
		arg.DefinitionHash,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
	)
	return err
}

const findFinishedPipelineBatches = `-- name: FindFinishedPipelineBatches :many
SELECT b.id, b.source_type, b.trace_id, b.created_at, b.updated_at, b.completed_at, b.published_at, b.last_publish_attempt_at, b.publish_retry_count, b.publish_error, b.stalled_at, b.n_subtasks, b.parent_id, b.parent_task_id, b.succeeded, b.pipeline_published_at, b.pipeline_publish_retry_count, b.pipeline_publish_error, b.purpose, b.pipeline_definition_hash, b.pipeline_idempotency_key, b.pipeline_request_fingerprint, b.pipeline_input_snapshot_at,
       COUNT(t.id) FILTER (WHERE t.status IN ('FAILED', 'CANCELLED')) = 0 AS completion_succeeded
FROM batches b
LEFT JOIN tasks t ON t.batch_id = b.id
WHERE b.completed_at IS NULL
  AND b.n_subtasks IS NOT NULL
  AND b.purpose = 'ANALYZER_PIPELINE_STAGE'
  AND b.parent_task_id IS NOT NULL
GROUP BY b.id
HAVING COUNT(t.id) = b.n_subtasks
   AND COUNT(t.id) FILTER (WHERE t.status IN ('COMPLETED', 'FAILED', 'CANCELLED')) = b.n_subtasks
ORDER BY b.created_at ASC
LIMIT $1
`

type FindFinishedPipelineBatchesRow struct {
	ID                         uuid.UUID          `db:"id" json:"id"`
	SourceType                 SourceType         `db:"source_type" json:"source_type"`
	TraceID                    pgtype.Text        `db:"trace_id" json:"trace_id"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt                pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	PublishedAt                pgtype.Timestamptz `db:"published_at" json:"published_at"`
	LastPublishAttemptAt       pgtype.Timestamptz `db:"last_publish_attempt_at" json:"last_publish_attempt_at"`
	PublishRetryCount          int32              `db:"publish_retry_count" json:"publish_retry_count"`
	PublishError               pgtype.Text        `db:"publish_error" json:"publish_error"`
	StalledAt                  pgtype.Timestamptz `db:"stalled_at" json:"stalled_at"`
	NSubtasks                  pgtype.Int4        `db:"n_subtasks" json:"n_subtasks"`
	ParentID                   pgtype.UUID        `db:"parent_id" json:"parent_id"`
	ParentTaskID               pgtype.UUID        `db:"parent_task_id" json:"parent_task_id"`
	Succeeded                  pgtype.Bool        `db:"succeeded" json:"succeeded"`
	PipelinePublishedAt        pgtype.Timestamptz `db:"pipeline_published_at" json:"pipeline_published_at"`
	PipelinePublishRetryCount  int32              `db:"pipeline_publish_retry_count" json:"pipeline_publish_retry_count"`
	PipelinePublishError       pgtype.Text        `db:"pipeline_publish_error" json:"pipeline_publish_error"`
	Purpose                    BatchPurpose       `db:"purpose" json:"purpose"`
	PipelineDefinitionHash     pgtype.Text        `db:"pipeline_definition_hash" json:"pipeline_definition_hash"`
	PipelineIdempotencyKey     pgtype.Text        `db:"pipeline_idempotency_key" json:"pipeline_idempotency_key"`
	PipelineRequestFingerprint pgtype.Text        `db:"pipeline_request_fingerprint" json:"pipeline_request_fingerprint"`
	PipelineInputSnapshotAt    pgtype.Timestamptz `db:"pipeline_input_snapshot_at" json:"pipeline_input_snapshot_at"`
	CompletionSucceeded        bool               `db:"completion_succeeded" json:"completion_succeeded"`
}

func (q *Queries) FindFinishedPipelineBatches(ctx context.Context, limit int32) ([]FindFinishedPipelineBatchesRow, error) {
	rows, err := q.db.Query(ctx, findFinishedPipelineBatches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindFinishedPipelineBatchesRow
	for rows.Next() {
		var i FindFinishedPipelineBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.PublishedAt,
			&i.LastPublishAttemptAt,
			&i.PublishRetryCount,
			&i.PublishError,
			&i.StalledAt,
			&i.NSubtasks,
			&i.ParentID,
			&i.ParentTaskID,
			&i.Succeeded,
			&i.PipelinePublishedAt,
			&i.PipelinePublishRetryCount,
			&i.PipelinePublishError,
			&i.Purpose,
			&i.PipelineDefinitionHash,
			&i.PipelineIdempotencyKey,
			&i.PipelineRequestFingerprint,
			&i.PipelineInputSnapshotAt,
			&i.CompletionSucceeded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFinishedPipelineRootBatches = `-- name: FindFinishedPipelineRootBatches :many
SELECT b.id, b.source_type, b.trace_id, b.created_at, b.updated_at, b.completed_at, b.published_at, b.last_publish_attempt_at, b.publish_retry_count, b.publish_error, b.stalled_at, b.n_subtasks, b.parent_id, b.parent_task_id, b.succeeded, b.pipeline_published_at, b.pipeline_publish_retry_count, b.pipeline_publish_error, b.purpose, b.pipeline_definition_hash, b.pipeline_idempotency_key, b.pipeline_request_fingerprint, b.pipeline_input_snapshot_at,
       COUNT(t.id) FILTER (WHERE t.status IN ('FAILED', 'CANCELLED')) = 0 AS completion_succeeded
FROM batches b
LEFT JOIN tasks t ON t.batch_id = b.id
WHERE b.completed_at IS NULL
  AND b.n_subtasks IS NOT NULL
  AND b.purpose = 'ANALYZER_PIPELINE_ROOT'
  AND b.parent_id IS NOT NULL
  AND b.parent_task_id IS NULL
GROUP BY b.id
HAVING COUNT(t.id) = b.n_subtasks
   AND COUNT(t.id) FILTER (WHERE t.status IN ('COMPLETED', 'FAILED', 'CANCELLED')) = b.n_subtasks
ORDER BY b.created_at ASC
LIMIT $1
`

type FindFinishedPipelineRootBatchesRow struct {
	ID                         uuid.UUID          `db:"id" json:"id"`
	SourceType                 SourceType         `db:"source_type" json:"source_type"`
	TraceID                    pgtype.Text        `db:"trace_id" json:"trace_id"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt                pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	PublishedAt                pgtype.Timestamptz `db:"published_at" json:"published_at"`
	LastPublishAttemptAt       pgtype.Timestamptz `db:"last_publish_attempt_at" json:"last_publish_attempt_at"`
	PublishRetryCount          int32              `db:"publish_retry_count" json:"publish_retry_count"`
	PublishError               pgtype.Text        `db:"publish_error" json:"publish_error"`
	StalledAt                  pgtype.Timestamptz `db:"stalled_at" json:"stalled_at"`
	NSubtasks                  pgtype.Int4        `db:"n_subtasks" json:"n_subtasks"`
	ParentID                   pgtype.UUID        `db:"parent_id" json:"parent_id"`
	ParentTaskID               pgtype.UUID        `db:"parent_task_id" json:"parent_task_id"`
	Succeeded                  pgtype.Bool        `db:"succeeded" json:"succeeded"`
	PipelinePublishedAt        pgtype.Timestamptz `db:"pipeline_published_at" json:"pipeline_published_at"`
	PipelinePublishRetryCount  int32              `db:"pipeline_publish_retry_count" json:"pipeline_publish_retry_count"`
	PipelinePublishError       pgtype.Text        `db:"pipeline_publish_error" json:"pipeline_publish_error"`
	Purpose                    BatchPurpose       `db:"purpose" json:"purpose"`
	PipelineDefinitionHash     pgtype.Text        `db:"pipeline_definition_hash" json:"pipeline_definition_hash"`
	PipelineIdempotencyKey     pgtype.Text        `db:"pipeline_idempotency_key" json:"pipeline_idempotency_key"`
	PipelineRequestFingerprint pgtype.Text        `db:"pipeline_request_fingerprint" json:"pipeline_request_fingerprint"`
	PipelineInputSnapshotAt    pgtype.Timestamptz `db:"pipeline_input_snapshot_at" json:"pipeline_input_snapshot_at"`
	CompletionSucceeded        bool               `db:"completion_succeeded" json:"completion_succeeded"`
}

func (q *Queries) FindFinishedPipelineRootBatches(ctx context.Context, limit int32) ([]FindFinishedPipelineRootBatchesRow, error) {
	rows, err := q.db.Query(ctx, findFinishedPipelineRootBatches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindFinishedPipelineRootBatchesRow
	for rows.Next() {
		var i FindFinishedPipelineRootBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.PublishedAt,
			&i.LastPublishAttemptAt,
			&i.PublishRetryCount,
			&i.PublishError,
			&i.StalledAt,
			&i.NSubtasks,
			&i.ParentID,
			&i.ParentTaskID,
			&i.Succeeded,
			&i.PipelinePublishedAt,
			&i.PipelinePublishRetryCount,
			&i.PipelinePublishError,
			&i.Purpose,
			&i.PipelineDefinitionHash,
			&i.PipelineIdempotencyKey,
			&i.PipelineRequestFingerprint,
			&i.PipelineInputSnapshotAt,
			&i.CompletionSucceeded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNewlyCompletedBatches = `-- name: FindNewlyCompletedBatches :many
SELECT id, source_type, trace_id
FROM batches b
WHERE b.completed_at IS NULL 
  AND b.source_type = $1
  AND b.purpose = 'COLLECTION'
  AND EXISTS (SELECT 1 FROM tasks t WHERE t.batch_id = b.id)
  AND NOT EXISTS (
      SELECT 1 FROM tasks t
      WHERE t.batch_id = b.id
        AND t.status NOT IN ('COMPLETED', 'FAILED', 'CANCELLED')
  )
   AND (
       EXISTS (
           SELECT 1 FROM tasks t
           WHERE t.batch_id = b.id
             AND t.status IN ('FAILED', 'CANCELLED')
       )
       OR (SELECT COUNT(*) FROM candidates c WHERE c.batch_id = b.id) = 0
       OR (SELECT COUNT(*) FROM candidates c WHERE c.batch_id = b.id)
           <= (SELECT COUNT(*) FROM contents ct WHERE ct.batch_id = b.id)
   )
ORDER BY b.created_at ASC
LIMIT $2
`

type FindNewlyCompletedBatchesParams struct {
	SourceType SourceType `db:"source_type" json:"source_type"`
	Limit      int32      `db:"limit" json:"limit"`
}

type FindNewlyCompletedBatchesRow struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	SourceType SourceType  `db:"source_type" json:"source_type"`
	TraceID    pgtype.Text `db:"trace_id" json:"trace_id"`
}

// Finds batches where all tasks are completed and all candidates are promoted to contents.
func (q *Queries) FindNewlyCompletedBatches(ctx context.Context, arg FindNewlyCompletedBatchesParams) ([]FindNewlyCompletedBatchesRow, error) {
	rows, err := q.db.Query(ctx, findNewlyCompletedBatches, arg.SourceType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNewlyCompletedBatchesRow
	for rows.Next() {
		var i FindNewlyCompletedBatchesRow
		if err := rows.Scan(&i.ID, &i.SourceType, &i.TraceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchByID = `-- name: GetBatchByID :one
SELECT id, source_type, trace_id, created_at, updated_at, completed_at, published_at, last_publish_attempt_at, publish_retry_count, publish_error, stalled_at, n_subtasks, parent_id, parent_task_id, succeeded, pipeline_published_at, pipeline_publish_retry_count, pipeline_publish_error, purpose, pipeline_definition_hash, pipeline_idempotency_key, pipeline_request_fingerprint, pipeline_input_snapshot_at
FROM batches
WHERE id = $1
`

func (q *Queries) GetBatchByID(ctx context.Context, id uuid.UUID) (Batch, error) {
	row := q.db.QueryRow(ctx, getBatchByID, id)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PublishedAt,
		&i.LastPublishAttemptAt,
		&i.PublishRetryCount,
		&i.PublishError,
		&i.StalledAt,
		&i.NSubtasks,
		&i.ParentID,
		&i.ParentTaskID,
		&i.Succeeded,
		&i.PipelinePublishedAt,
		&i.PipelinePublishRetryCount,
		&i.PipelinePublishError,
		&i.Purpose,
		&i.PipelineDefinitionHash,
		&i.PipelineIdempotencyKey,
		&i.PipelineRequestFingerprint,
		&i.PipelineInputSnapshotAt,
	)
	return i, err
}

const getPipelineRootByIdempotency = `-- name: GetPipelineRootByIdempotency :one
SELECT id, source_type, trace_id, created_at, updated_at, completed_at, published_at, last_publish_attempt_at, publish_retry_count, publish_error, stalled_at, n_subtasks, parent_id, parent_task_id, succeeded, pipeline_published_at, pipeline_publish_retry_count, pipeline_publish_error, purpose, pipeline_definition_hash, pipeline_idempotency_key, pipeline_request_fingerprint, pipeline_input_snapshot_at
FROM batches
WHERE parent_id = $1
  AND purpose = 'ANALYZER_PIPELINE_ROOT'
  AND pipeline_idempotency_key = $2
FOR UPDATE
`

type GetPipelineRootByIdempotencyParams struct {
	ParentID       pgtype.UUID `db:"parent_id" json:"parent_id"`
	IdempotencyKey pgtype.Text `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetPipelineRootByIdempotency(ctx context.Context, arg GetPipelineRootByIdempotencyParams) (Batch, error) {
	row := q.db.QueryRow(ctx, getPipelineRootByIdempotency, arg.ParentID, arg.IdempotencyKey)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PublishedAt,
		&i.LastPublishAttemptAt,
		&i.PublishRetryCount,
		&i.PublishError,
		&i.StalledAt,
		&i.NSubtasks,
		&i.ParentID,
		&i.ParentTaskID,
		&i.Succeeded,
		&i.PipelinePublishedAt,
		&i.PipelinePublishRetryCount,
		&i.PipelinePublishError,
		&i.Purpose,
		&i.PipelineDefinitionHash,
		&i.PipelineIdempotencyKey,
		&i.PipelineRequestFingerprint,
		&i.PipelineInputSnapshotAt,
	)
	return i, err
}

const listBatches = `-- name: ListBatches :many
SELECT id, source_type, trace_id, created_at, updated_at, completed_at, published_at, last_publish_attempt_at, publish_retry_count, publish_error, stalled_at, n_subtasks, parent_id, parent_task_id, succeeded, pipeline_published_at, pipeline_publish_retry_count, pipeline_publish_error, purpose, pipeline_definition_hash, pipeline_idempotency_key, pipeline_request_fingerprint, pipeline_input_snapshot_at
FROM batches
ORDER BY created_at DESC, id DESC
LIMIT $2
OFFSET $1
`

type ListBatchesParams struct {
	Off int32 `db:"off" json:"off"`
	Lim int32 `db:"lim" json:"lim"`
}

func (q *Queries) ListBatches(ctx context.Context, arg ListBatchesParams) ([]Batch, error) {
	rows, err := q.db.Query(ctx, listBatches, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Batch
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.PublishedAt,
			&i.LastPublishAttemptAt,
			&i.PublishRetryCount,
			&i.PublishError,
			&i.StalledAt,
			&i.NSubtasks,
			&i.ParentID,
			&i.ParentTaskID,
			&i.Succeeded,
			&i.PipelinePublishedAt,
			&i.PipelinePublishRetryCount,
			&i.PipelinePublishError,
			&i.Purpose,
			&i.PipelineDefinitionHash,
			&i.PipelineIdempotencyKey,
			&i.PipelineRequestFingerprint,
			&i.PipelineInputSnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildBatchesByParentID = `-- name: ListChildBatchesByParentID :many
SELECT id, source_type, trace_id, created_at, updated_at, completed_at, published_at, last_publish_attempt_at, publish_retry_count, publish_error, stalled_at, n_subtasks, parent_id, parent_task_id, succeeded, pipeline_published_at, pipeline_publish_retry_count, pipeline_publish_error, purpose, pipeline_definition_hash, pipeline_idempotency_key, pipeline_request_fingerprint, pipeline_input_snapshot_at
FROM batches
WHERE parent_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListChildBatchesByParentID(ctx context.Context, parentID pgtype.UUID) ([]Batch, error) {
	rows, err := q.db.Query(ctx, listChildBatchesByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Batch
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.PublishedAt,
			&i.LastPublishAttemptAt,
			&i.PublishRetryCount,
			&i.PublishError,
			&i.StalledAt,
			&i.NSubtasks,
			&i.ParentID,
			&i.ParentTaskID,
			&i.Succeeded,
			&i.PipelinePublishedAt,
			&i.PipelinePublishRetryCount,
			&i.PipelinePublishError,
			&i.Purpose,
			&i.PipelineDefinitionHash,
			&i.PipelineIdempotencyKey,
			&i.PipelineRequestFingerprint,
			&i.PipelineInputSnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCompletionBatches = `-- name: ListPendingCompletionBatches :many
SELECT id, source_type, trace_id, created_at, updated_at, completed_at, published_at, last_publish_attempt_at, publish_retry_count, publish_error, stalled_at, n_subtasks, parent_id, parent_task_id, succeeded, pipeline_published_at, pipeline_publish_retry_count, pipeline_publish_error, purpose, pipeline_definition_hash, pipeline_idempotency_key, pipeline_request_fingerprint, pipeline_input_snapshot_at
FROM batches
WHERE completed_at IS NULL
  AND source_type = $1
  AND purpose = 'COLLECTION'
ORDER BY created_at ASC
LIMIT $2
`

type ListPendingCompletionBatchesParams struct {
	SourceType SourceType `db:"source_type" json:"source_type"`
	Limit      int32      `db:"limit" json:"limit"`
}

func (q *Queries) ListPendingCompletionBatches(ctx context.Context, arg ListPendingCompletionBatchesParams) ([]Batch, error) {
	rows, err := q.db.Query(ctx, listPendingCompletionBatches, arg.SourceType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Batch
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.PublishedAt,
			&i.LastPublishAttemptAt,
			&i.PublishRetryCount,
			&i.PublishError,
			&i.StalledAt,
			&i.NSubtasks,
			&i.ParentID,
			&i.ParentTaskID,
			&i.Succeeded,
			&i.PipelinePublishedAt,
			&i.PipelinePublishRetryCount,
			&i.PipelinePublishError,
			&i.Purpose,
			&i.PipelineDefinitionHash,
			&i.PipelineIdempotencyKey,
			&i.PipelineRequestFingerprint,
			&i.PipelineInputSnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelineInputCandidates = `-- name: ListPipelineInputCandidates :many
SELECT candidate_id, batch_id, fingerprint, source_abbr, title, url, description,
       published_at, discovered_at, trace_id, ingestion_method::text AS ingestion_method, metadata, created_at
FROM pipeline_input_candidates
WHERE root_batch_id = $1
ORDER BY candidate_id
`

type ListPipelineInputCandidatesRow struct {
	CandidateID     uuid.UUID          `db:"candidate_id" json:"candidate_id"`
	BatchID         uuid.UUID          `db:"batch_id" json:"batch_id"`
	Fingerprint     string             `db:"fingerprint" json:"fingerprint"`
	SourceAbbr      string             `db:"source_abbr" json:"source_abbr"`
	Title           string             `db:"title" json:"title"`
	Url             string             `db:"url" json:"url"`
	Description     pgtype.Text        `db:"description" json:"description"`
	PublishedAt     pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DiscoveredAt    pgtype.Timestamptz `db:"discovered_at" json:"discovered_at"`
	TraceID         string             `db:"trace_id" json:"trace_id"`
	IngestionMethod string             `db:"ingestion_method" json:"ingestion_method"`
	Metadata        []byte             `db:"metadata" json:"metadata"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListPipelineInputCandidates(ctx context.Context, rootBatchID uuid.UUID) ([]ListPipelineInputCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listPipelineInputCandidates, rootBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPipelineInputCandidatesRow
	for rows.Next() {
		var i ListPipelineInputCandidatesRow
		if err := rows.Scan(
			&i.CandidateID,
			&i.BatchID,
			&i.Fingerprint,
			&i.SourceAbbr,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.DiscoveredAt,
			&i.TraceID,
			&i.IngestionMethod,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelineInputContents = `-- name: ListPipelineInputContents :many
SELECT content_id, batch_id, type, source_abbr, candidate_id, url, title, content,
       author, trace_id, published_at, fetched_at, created_at, deleted_at, metadata
FROM pipeline_input_contents
WHERE root_batch_id = $1
ORDER BY content_id
`

type ListPipelineInputContentsRow struct {
	ContentID   uuid.UUID          `db:"content_id" json:"content_id"`
	BatchID     uuid.UUID          `db:"batch_id" json:"batch_id"`
	Type        ContentType        `db:"type" json:"type"`
	SourceAbbr  string             `db:"source_abbr" json:"source_abbr"`
	CandidateID pgtype.UUID        `db:"candidate_id" json:"candidate_id"`
	Url         string             `db:"url" json:"url"`
	Title       string             `db:"title" json:"title"`
	Content     string             `db:"content" json:"content"`
	Author      pgtype.Text        `db:"author" json:"author"`
	TraceID     string             `db:"trace_id" json:"trace_id"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	FetchedAt   pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
}

func (q *Queries) ListPipelineInputContents(ctx context.Context, rootBatchID uuid.UUID) ([]ListPipelineInputContentsRow, error) {
	rows, err := q.db.Query(ctx, listPipelineInputContents, rootBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPipelineInputContentsRow
	for rows.Next() {
		var i ListPipelineInputContentsRow
		if err := rows.Scan(
			&i.ContentID,
			&i.BatchID,
			&i.Type,
			&i.SourceAbbr,
			&i.CandidateID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.Author,
			&i.TraceID,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyPipelineBatches = `-- name: ListReadyPipelineBatches :many
SELECT id, source_type, trace_id, created_at, updated_at, completed_at, published_at, last_publish_attempt_at, publish_retry_count, publish_error, stalled_at, n_subtasks, parent_id, parent_task_id, succeeded, pipeline_published_at, pipeline_publish_retry_count, pipeline_publish_error, purpose, pipeline_definition_hash, pipeline_idempotency_key, pipeline_request_fingerprint, pipeline_input_snapshot_at
FROM batches
WHERE completed_at IS NOT NULL
  AND n_subtasks IS NOT NULL
  AND pipeline_published_at IS NULL
  AND purpose = 'ANALYZER_PIPELINE_STAGE'
  AND parent_task_id IS NOT NULL
ORDER BY completed_at ASC, created_at ASC
LIMIT $1
`

func (q *Queries) ListReadyPipelineBatches(ctx context.Context, limit int32) ([]Batch, error) {
	rows, err := q.db.Query(ctx, listReadyPipelineBatches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Batch
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.PublishedAt,
			&i.LastPublishAttemptAt,
			&i.PublishRetryCount,
			&i.PublishError,
			&i.StalledAt,
			&i.NSubtasks,
			&i.ParentID,
			&i.ParentTaskID,
			&i.Succeeded,
			&i.PipelinePublishedAt,
			&i.PipelinePublishRetryCount,
			&i.PipelinePublishError,
			&i.Purpose,
			&i.PipelineDefinitionHash,
			&i.PipelineIdempotencyKey,
			&i.PipelineRequestFingerprint,
			&i.PipelineInputSnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyToPublishBatches = `-- name: ListReadyToPublishBatches :many
SELECT id, source_type, trace_id, created_at, updated_at, completed_at, published_at, last_publish_attempt_at, publish_retry_count, publish_error, stalled_at, n_subtasks, parent_id, parent_task_id, succeeded, pipeline_published_at, pipeline_publish_retry_count, pipeline_publish_error, purpose, pipeline_definition_hash, pipeline_idempotency_key, pipeline_request_fingerprint, pipeline_input_snapshot_at
FROM batches
WHERE completed_at IS NOT NULL
  AND published_at IS NULL
  AND source_type = $1
  AND purpose = 'COLLECTION'
ORDER BY completed_at ASC, created_at ASC
LIMIT $2
`

type ListReadyToPublishBatchesParams struct {
	SourceType SourceType `db:"source_type" json:"source_type"`
	Limit      int32      `db:"limit" json:"limit"`
}

func (q *Queries) ListReadyToPublishBatches(ctx context.Context, arg ListReadyToPublishBatchesParams) ([]Batch, error) {
	rows, err := q.db.Query(ctx, listReadyToPublishBatches, arg.SourceType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Batch
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.PublishedAt,
			&i.LastPublishAttemptAt,
			&i.PublishRetryCount,
			&i.PublishError,
			&i.StalledAt,
			&i.NSubtasks,
			&i.ParentID,
			&i.ParentTaskID,
			&i.Succeeded,
			&i.PipelinePublishedAt,
			&i.PipelinePublishRetryCount,
			&i.PipelinePublishError,
			&i.Purpose,
			&i.PipelineDefinitionHash,
			&i.PipelineIdempotencyKey,
			&i.PipelineRequestFingerprint,
			&i.PipelineInputSnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBatchForTaskInsert = `-- name: LockBatchForTaskInsert :one
SELECT id, n_subtasks, completed_at, succeeded
FROM batches
WHERE id = $1
FOR UPDATE
`

type LockBatchForTaskInsertRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	NSubtasks   pgtype.Int4        `db:"n_subtasks" json:"n_subtasks"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	Succeeded   pgtype.Bool        `db:"succeeded" json:"succeeded"`
}

func (q *Queries) LockBatchForTaskInsert(ctx context.Context, id uuid.UUID) (LockBatchForTaskInsertRow, error) {
	row := q.db.QueryRow(ctx, lockBatchForTaskInsert, id)
	var i LockBatchForTaskInsertRow
	err := row.Scan(
		&i.ID,
		&i.NSubtasks,
		&i.CompletedAt,
		&i.Succeeded,
	)
	return i, err
}

const markBatchCompleted = `-- name: MarkBatchCompleted :execrows
UPDATE batches
SET completed_at = NOW(),
    updated_at = NOW(),
    trace_id = COALESCE(NULLIF(trace_id, ''), NULLIF($2, '')),
    succeeded = NOT EXISTS (
        SELECT 1 FROM tasks t
        WHERE t.batch_id = batches.id
          AND t.status IN ('FAILED', 'CANCELLED')
    )
WHERE batches.id = $1
  AND batches.purpose = 'COLLECTION'
  AND batches.completed_at IS NULL
`

type MarkBatchCompletedParams struct {
	ID      uuid.UUID   `db:"id" json:"id"`
	TraceID interface{} `db:"trace_id" json:"trace_id"`
}

// Optimistic-concurrency claim: returns rows-affected so the caller can
// distinguish the winner (1) from a loser racing against another instance
// (0). Only the winner should publish the batch.completed signal.
func (q *Queries) MarkBatchCompleted(ctx context.Context, arg MarkBatchCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBatchCompleted, arg.ID, arg.TraceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markBatchPublished = `-- name: MarkBatchPublished :exec
UPDATE batches
SET published_at = NOW(),
    updated_at = NOW(),
    publish_error = NULL
WHERE id = $1
  AND published_at IS NULL
`

func (q *Queries) MarkBatchPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBatchPublished, id)
	return err
}

const markPipelineBatchFinished = `-- name: MarkPipelineBatchFinished :execrows
UPDATE batches
SET completed_at = NOW(),
    succeeded = $1,
    updated_at = NOW(),
    trace_id = COALESCE(NULLIF(trace_id, ''), NULLIF($2, ''))
WHERE batches.id = $3
  AND purpose = 'ANALYZER_PIPELINE_STAGE'
  AND completed_at IS NULL
  AND n_subtasks IS NOT NULL
  AND (SELECT COUNT(*) FROM tasks t WHERE t.batch_id = batches.id) = n_subtasks
  AND (SELECT COUNT(*) FROM tasks t WHERE t.batch_id = batches.id AND t.status IN ('COMPLETED', 'FAILED', 'CANCELLED')) = n_subtasks
`

type MarkPipelineBatchFinishedParams struct {
	Succeeded pgtype.Bool `db:"succeeded" json:"succeeded"`
	TraceID   interface{} `db:"trace_id" json:"trace_id"`
	BatchID   uuid.UUID   `db:"batch_id" json:"batch_id"`
}

func (q *Queries) MarkPipelineBatchFinished(ctx context.Context, arg MarkPipelineBatchFinishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPipelineBatchFinished, arg.Succeeded, arg.TraceID, arg.BatchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPipelineInputSnapshot = `-- name: MarkPipelineInputSnapshot :execrows
UPDATE batches
SET pipeline_input_snapshot_at = NOW(), updated_at = NOW()
WHERE id = $1
  AND purpose = 'ANALYZER_PIPELINE_ROOT'
  AND pipeline_input_snapshot_at IS NULL
`

func (q *Queries) MarkPipelineInputSnapshot(ctx context.Context, rootBatchID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markPipelineInputSnapshot, rootBatchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPipelinePublished = `-- name: MarkPipelinePublished :exec
UPDATE batches
SET pipeline_published_at = NOW(),
    pipeline_publish_error = NULL,
    updated_at = NOW()
WHERE id = $1
  AND pipeline_published_at IS NULL
`

func (q *Queries) MarkPipelinePublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPipelinePublished, id)
	return err
}

const markPipelineRootFinished = `-- name: MarkPipelineRootFinished :execrows
UPDATE batches
SET completed_at = NOW(),
    succeeded = $1,
    updated_at = NOW(),
    trace_id = COALESCE(NULLIF(trace_id, ''), NULLIF($2, ''))
WHERE batches.id = $3
  AND purpose = 'ANALYZER_PIPELINE_ROOT'
  AND parent_task_id IS NULL
  AND completed_at IS NULL
  AND n_subtasks IS NOT NULL
  AND (SELECT COUNT(*) FROM tasks t WHERE t.batch_id = batches.id) = n_subtasks
  AND (SELECT COUNT(*) FROM tasks t WHERE t.batch_id = batches.id AND t.status IN ('COMPLETED', 'FAILED', 'CANCELLED')) = n_subtasks
`

type MarkPipelineRootFinishedParams struct {
	Succeeded pgtype.Bool `db:"succeeded" json:"succeeded"`
	TraceID   interface{} `db:"trace_id" json:"trace_id"`
	BatchID   uuid.UUID   `db:"batch_id" json:"batch_id"`
}

func (q *Queries) MarkPipelineRootFinished(ctx context.Context, arg MarkPipelineRootFinishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPipelineRootFinished, arg.Succeeded, arg.TraceID, arg.BatchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordBatchPublishFailure = `-- name: RecordBatchPublishFailure :exec
UPDATE batches
SET last_publish_attempt_at = NOW(),
    publish_retry_count = publish_retry_count + 1,
    publish_error = $2,
    updated_at = NOW()
WHERE id = $1
`

type RecordBatchPublishFailureParams struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	PublishError pgtype.Text `db:"publish_error" json:"publish_error"`
}

func (q *Queries) RecordBatchPublishFailure(ctx context.Context, arg RecordBatchPublishFailureParams) error {
	_, err := q.db.Exec(ctx, recordBatchPublishFailure, arg.ID, arg.PublishError)
	return err
}

const recordPipelinePublishFailure = `-- name: RecordPipelinePublishFailure :exec
UPDATE batches
SET pipeline_publish_retry_count = pipeline_publish_retry_count + 1,
    pipeline_publish_error = $2,
    updated_at = NOW()
WHERE id = $1
`

type RecordPipelinePublishFailureParams struct {
	ID                   uuid.UUID   `db:"id" json:"id"`
	PipelinePublishError pgtype.Text `db:"pipeline_publish_error" json:"pipeline_publish_error"`
}

func (q *Queries) RecordPipelinePublishFailure(ctx context.Context, arg RecordPipelinePublishFailureParams) error {
	_, err := q.db.Exec(ctx, recordPipelinePublishFailure, arg.ID, arg.PipelinePublishError)
	return err
}

const setBatchNSubtasks = `-- name: SetBatchNSubtasks :one
WITH locked AS (
    SELECT id, n_subtasks, completed_at
    FROM batches
    WHERE batches.id = $1
    FOR UPDATE
), updated AS (
    UPDATE batches b
    SET n_subtasks = $2, updated_at = NOW()
    FROM locked
    WHERE b.id = locked.id
      AND locked.completed_at IS NULL
      AND (locked.n_subtasks IS NULL OR locked.n_subtasks = $2)
      AND (SELECT COUNT(*) FROM tasks t WHERE t.batch_id = b.id) <= $2
    RETURNING b.id, b.source_type, b.trace_id, b.created_at, b.updated_at, b.completed_at, b.published_at, b.last_publish_attempt_at, b.publish_retry_count, b.publish_error, b.stalled_at, b.n_subtasks, b.parent_id, b.parent_task_id, b.succeeded, b.pipeline_published_at, b.pipeline_publish_retry_count, b.pipeline_publish_error, b.purpose, b.pipeline_definition_hash, b.pipeline_idempotency_key, b.pipeline_request_fingerprint, b.pipeline_input_snapshot_at
)
SELECT id, source_type, trace_id, created_at, updated_at, completed_at, published_at, last_publish_attempt_at, publish_retry_count, publish_error, stalled_at, n_subtasks, parent_id, parent_task_id, succeeded, pipeline_published_at, pipeline_publish_retry_count, pipeline_publish_error, purpose, pipeline_definition_hash, pipeline_idempotency_key, pipeline_request_fingerprint, pipeline_input_snapshot_at FROM updated
`

type SetBatchNSubtasksParams struct {
	BatchID   uuid.UUID   `db:"batch_id" json:"batch_id"`
	NSubtasks pgtype.Int4 `db:"n_subtasks" json:"n_subtasks"`
}

type SetBatchNSubtasksRow struct {
	ID                         uuid.UUID          `db:"id" json:"id"`
	SourceType                 SourceType         `db:"source_type" json:"source_type"`
	TraceID                    pgtype.Text        `db:"trace_id" json:"trace_id"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt                pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	PublishedAt                pgtype.Timestamptz `db:"published_at" json:"published_at"`
	LastPublishAttemptAt       pgtype.Timestamptz `db:"last_publish_attempt_at" json:"last_publish_attempt_at"`
	PublishRetryCount          int32              `db:"publish_retry_count" json:"publish_retry_count"`
	PublishError               pgtype.Text        `db:"publish_error" json:"publish_error"`
	StalledAt                  pgtype.Timestamptz `db:"stalled_at" json:"stalled_at"`
	NSubtasks                  pgtype.Int4        `db:"n_subtasks" json:"n_subtasks"`
	ParentID                   pgtype.UUID        `db:"parent_id" json:"parent_id"`
	ParentTaskID               pgtype.UUID        `db:"parent_task_id" json:"parent_task_id"`
	Succeeded                  pgtype.Bool        `db:"succeeded" json:"succeeded"`
	PipelinePublishedAt        pgtype.Timestamptz `db:"pipeline_published_at" json:"pipeline_published_at"`
	PipelinePublishRetryCount  int32              `db:"pipeline_publish_retry_count" json:"pipeline_publish_retry_count"`
	PipelinePublishError       pgtype.Text        `db:"pipeline_publish_error" json:"pipeline_publish_error"`
	Purpose                    BatchPurpose       `db:"purpose" json:"purpose"`
	PipelineDefinitionHash     pgtype.Text        `db:"pipeline_definition_hash" json:"pipeline_definition_hash"`
	PipelineIdempotencyKey     pgtype.Text        `db:"pipeline_idempotency_key" json:"pipeline_idempotency_key"`
	PipelineRequestFingerprint pgtype.Text        `db:"pipeline_request_fingerprint" json:"pipeline_request_fingerprint"`
	PipelineInputSnapshotAt    pgtype.Timestamptz `db:"pipeline_input_snapshot_at" json:"pipeline_input_snapshot_at"`
}

func (q *Queries) SetBatchNSubtasks(ctx context.Context, arg SetBatchNSubtasksParams) (SetBatchNSubtasksRow, error) {
	row := q.db.QueryRow(ctx, setBatchNSubtasks, arg.BatchID, arg.NSubtasks)
	var i SetBatchNSubtasksRow
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PublishedAt,
		&i.LastPublishAttemptAt,
		&i.PublishRetryCount,
		&i.PublishError,
		&i.StalledAt,
		&i.NSubtasks,
		&i.ParentID,
		&i.ParentTaskID,
		&i.Succeeded,
		&i.PipelinePublishedAt,
		&i.PipelinePublishRetryCount,
		&i.PipelinePublishError,
		&i.Purpose,
		&i.PipelineDefinitionHash,
		&i.PipelineIdempotencyKey,
		&i.PipelineRequestFingerprint,
		&i.PipelineInputSnapshotAt,
	)
	return i, err
}

const setPipelineRootFailure = `-- name: SetPipelineRootFailure :exec
UPDATE batches
SET n_subtasks = COALESCE(n_subtasks, 1),
    updated_at = NOW()
WHERE id = $1
  AND purpose = 'ANALYZER_PIPELINE_ROOT'
  AND parent_task_id IS NULL
`

func (q *Queries) SetPipelineRootFailure(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setPipelineRootFailure, id)
	return err
}

const snapshotPipelineCandidates = `-- name: SnapshotPipelineCandidates :exec
INSERT INTO pipeline_input_candidates (
    root_batch_id, candidate_id, batch_id, fingerprint, source_abbr, title, url,
    description, published_at, discovered_at, trace_id, ingestion_method, metadata, created_at
)
SELECT
    $1, c.id, c.batch_id, c.fingerprint, c.source_abbr, c.title, c.url,
    c.description, c.published_at, c.discovered_at, c.trace_id, c.ingestion_method, c.metadata, c.created_at
FROM candidates c
WHERE c.batch_id = $2
ON CONFLICT (root_batch_id, candidate_id) DO NOTHING
`

type SnapshotPipelineCandidatesParams struct {
	RootBatchID  uuid.UUID   `db:"root_batch_id" json:"root_batch_id"`
	InputBatchID pgtype.UUID `db:"input_batch_id" json:"input_batch_id"`
}

func (q *Queries) SnapshotPipelineCandidates(ctx context.Context, arg SnapshotPipelineCandidatesParams) error {
	_, err := q.db.Exec(ctx, snapshotPipelineCandidates, arg.RootBatchID, arg.InputBatchID)
	return err
}

const snapshotPipelineContents = `-- name: SnapshotPipelineContents :exec
INSERT INTO pipeline_input_contents (
    root_batch_id, content_id, batch_id, type, source_abbr, candidate_id, url, title,
    content, author, trace_id, published_at, fetched_at, created_at, deleted_at, metadata
)
SELECT
    $1, c.id, c.batch_id, c.type, c.source_abbr, c.candidate_id, c.url, c.title,
    c.content, c.author, c.trace_id, c.published_at, c.fetched_at, c.created_at, c.deleted_at, c.metadata
FROM contents c
WHERE c.batch_id = $2
  AND c.deleted_at IS NULL
ON CONFLICT (root_batch_id, content_id) DO NOTHING
`

type SnapshotPipelineContentsParams struct {
	RootBatchID  uuid.UUID   `db:"root_batch_id" json:"root_batch_id"`
	InputBatchID pgtype.UUID `db:"input_batch_id" json:"input_batch_id"`
}

func (q *Queries) SnapshotPipelineContents(ctx context.Context, arg SnapshotPipelineContentsParams) error {
	_, err := q.db.Exec(ctx, snapshotPipelineContents, arg.RootBatchID, arg.InputBatchID)
	return err
}
