// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candidates.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCandidatesByBatchID = `-- name: CountCandidatesByBatchID :one
SELECT COUNT(*)
FROM candidates
WHERE batch_id = $1
`

func (q *Queries) CountCandidatesByBatchID(ctx context.Context, batchID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCandidatesByBatchID, batchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCandidate = `-- name: CreateCandidate :one
INSERT INTO candidates (
    batch_id,
    fingerprint,
    source_id,
    title,
    url,
    description,
    published_at,
    trace_id,
    ingestion_method,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, batch_id, source_id, trace_id, fingerprint, url, title, description, ingestion_method, metadata, published_at, discovered_at, created_at
`

type CreateCandidateParams struct {
	BatchID         pgtype.UUID              `db:"batch_id" json:"batch_id"`
	Fingerprint     string                   `db:"fingerprint" json:"fingerprint"`
	SourceID        int32                    `db:"source_id" json:"source_id"`
	Title           string                   `db:"title" json:"title"`
	Url             string                   `db:"url" json:"url"`
	Description     pgtype.Text              `db:"description" json:"description"`
	PublishedAt     pgtype.Timestamptz       `db:"published_at" json:"published_at"`
	TraceID         string                   `db:"trace_id" json:"trace_id"`
	IngestionMethod CandidateIngestionMethod `db:"ingestion_method" json:"ingestion_method"`
	Metadata        []byte                   `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, createCandidate,
		arg.BatchID,
		arg.Fingerprint,
		arg.SourceID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.TraceID,
		arg.IngestionMethod,
		arg.Metadata,
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.SourceID,
		&i.TraceID,
		&i.Fingerprint,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.IngestionMethod,
		&i.Metadata,
		&i.PublishedAt,
		&i.DiscoveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCandidateByFingerprint = `-- name: GetCandidateByFingerprint :one
SELECT id, batch_id, source_id, trace_id, fingerprint, url, title, description, ingestion_method, metadata, published_at, discovered_at, created_at
FROM candidates
WHERE fingerprint = $1
LIMIT 1
`

func (q *Queries) GetCandidateByFingerprint(ctx context.Context, fingerprint string) (Candidate, error) {
	row := q.db.QueryRow(ctx, getCandidateByFingerprint, fingerprint)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.SourceID,
		&i.TraceID,
		&i.Fingerprint,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.IngestionMethod,
		&i.Metadata,
		&i.PublishedAt,
		&i.DiscoveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCandidateByID = `-- name: GetCandidateByID :one
SELECT id, batch_id, source_id, trace_id, fingerprint, url, title, description, ingestion_method, metadata, published_at, discovered_at, created_at
FROM candidates
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCandidateByID(ctx context.Context, id uuid.UUID) (Candidate, error) {
	row := q.db.QueryRow(ctx, getCandidateByID, id)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.SourceID,
		&i.TraceID,
		&i.Fingerprint,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.IngestionMethod,
		&i.Metadata,
		&i.PublishedAt,
		&i.DiscoveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCandidatesForAnalysis = `-- name: ListCandidatesForAnalysis :many
SELECT id, batch_id, source_id, trace_id, fingerprint, url, title, description, ingestion_method, metadata, published_at, discovered_at, created_at
FROM candidates
ORDER BY published_at DESC NULLS LAST, discovered_at DESC, created_at DESC
LIMIT $1
OFFSET $2
`

type ListCandidatesForAnalysisParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListCandidatesForAnalysis(ctx context.Context, arg ListCandidatesForAnalysisParams) ([]Candidate, error) {
	rows, err := q.db.Query(ctx, listCandidatesForAnalysis, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candidate
	for rows.Next() {
		var i Candidate
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.SourceID,
			&i.TraceID,
			&i.Fingerprint,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.IngestionMethod,
			&i.Metadata,
			&i.PublishedAt,
			&i.DiscoveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCandidatesByText = `-- name: SearchCandidatesByText :many
SELECT id, batch_id, source_id, trace_id, fingerprint, url, title, description, ingestion_method, metadata, published_at, discovered_at, created_at
FROM candidates
WHERE title ILIKE '%' || $1 || '%'
   OR COALESCE(description, '') ILIKE '%' || $1 || '%'
ORDER BY published_at DESC NULLS LAST, discovered_at DESC, created_at DESC
LIMIT $2
OFFSET $3
`

type SearchCandidatesByTextParams struct {
	Column1 pgtype.Text `db:"column_1" json:"column_1"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) SearchCandidatesByText(ctx context.Context, arg SearchCandidatesByTextParams) ([]Candidate, error) {
	rows, err := q.db.Query(ctx, searchCandidatesByText, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candidate
	for rows.Next() {
		var i Candidate
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.SourceID,
			&i.TraceID,
			&i.Fingerprint,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.IngestionMethod,
			&i.Metadata,
			&i.PublishedAt,
			&i.DiscoveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCandidate = `-- name: UpsertCandidate :one
INSERT INTO candidates (
    batch_id,
    fingerprint,
    source_id,
    title,
    url,
    description,
    published_at,
    trace_id,
    ingestion_method,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (fingerprint) DO UPDATE
SET discovered_at = NOW(),
    trace_id = EXCLUDED.trace_id
RETURNING id, batch_id, source_id, trace_id, fingerprint, url, title, description, ingestion_method, metadata, published_at, discovered_at, created_at
`

type UpsertCandidateParams struct {
	BatchID         pgtype.UUID              `db:"batch_id" json:"batch_id"`
	Fingerprint     string                   `db:"fingerprint" json:"fingerprint"`
	SourceID        int32                    `db:"source_id" json:"source_id"`
	Title           string                   `db:"title" json:"title"`
	Url             string                   `db:"url" json:"url"`
	Description     pgtype.Text              `db:"description" json:"description"`
	PublishedAt     pgtype.Timestamptz       `db:"published_at" json:"published_at"`
	TraceID         string                   `db:"trace_id" json:"trace_id"`
	IngestionMethod CandidateIngestionMethod `db:"ingestion_method" json:"ingestion_method"`
	Metadata        []byte                   `db:"metadata" json:"metadata"`
}

func (q *Queries) UpsertCandidate(ctx context.Context, arg UpsertCandidateParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, upsertCandidate,
		arg.BatchID,
		arg.Fingerprint,
		arg.SourceID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.TraceID,
		arg.IngestionMethod,
		arg.Metadata,
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.SourceID,
		&i.TraceID,
		&i.Fingerprint,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.IngestionMethod,
		&i.Metadata,
		&i.PublishedAt,
		&i.DiscoveredAt,
		&i.CreatedAt,
	)
	return i, err
}
