// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contents.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContent = `-- name: CreateContent :one
INSERT INTO contents (
    batch_id,
    type,
    source_id,
    candidate_id,
    url,
    title,
    content,
    author,
    trace_id,
    published_at,
    fetched_at,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, batch_id, type, source_id, candidate_id, url, title, content, author, trace_id, published_at, fetched_at, created_at, deleted_at, metadata
`

type CreateContentParams struct {
	BatchID     pgtype.UUID        `db:"batch_id" json:"batch_id"`
	Type        ContentType        `db:"type" json:"type"`
	SourceID    int32              `db:"source_id" json:"source_id"`
	CandidateID pgtype.UUID        `db:"candidate_id" json:"candidate_id"`
	Url         string             `db:"url" json:"url"`
	Title       string             `db:"title" json:"title"`
	Content     string             `db:"content" json:"content"`
	Author      pgtype.Text        `db:"author" json:"author"`
	TraceID     string             `db:"trace_id" json:"trace_id"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	FetchedAt   pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, createContent,
		arg.BatchID,
		arg.Type,
		arg.SourceID,
		arg.CandidateID,
		arg.Url,
		arg.Title,
		arg.Content,
		arg.Author,
		arg.TraceID,
		arg.PublishedAt,
		arg.FetchedAt,
		arg.Metadata,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Type,
		&i.SourceID,
		&i.CandidateID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.Author,
		&i.TraceID,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const getContentByCandidateID = `-- name: GetContentByCandidateID :one
SELECT id, batch_id, type, source_id, candidate_id, url, title, content, author, trace_id, published_at, fetched_at, created_at, deleted_at, metadata
FROM contents
WHERE candidate_id = $1
LIMIT 1
`

func (q *Queries) GetContentByCandidateID(ctx context.Context, candidateID pgtype.UUID) (Content, error) {
	row := q.db.QueryRow(ctx, getContentByCandidateID, candidateID)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Type,
		&i.SourceID,
		&i.CandidateID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.Author,
		&i.TraceID,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const getContentByID = `-- name: GetContentByID :one
SELECT id, batch_id, type, source_id, candidate_id, url, title, content, author, trace_id, published_at, fetched_at, created_at, deleted_at, metadata
FROM contents
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetContentByID(ctx context.Context, id uuid.UUID) (Content, error) {
	row := q.db.QueryRow(ctx, getContentByID, id)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Type,
		&i.SourceID,
		&i.CandidateID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.Author,
		&i.TraceID,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const getContentByURL = `-- name: GetContentByURL :one
SELECT id, batch_id, type, source_id, candidate_id, url, title, content, author, trace_id, published_at, fetched_at, created_at, deleted_at, metadata
FROM contents
WHERE url = $1
LIMIT 1
`

func (q *Queries) GetContentByURL(ctx context.Context, url string) (Content, error) {
	row := q.db.QueryRow(ctx, getContentByURL, url)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Type,
		&i.SourceID,
		&i.CandidateID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.Author,
		&i.TraceID,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const listContentsByBatchID = `-- name: ListContentsByBatchID :many
SELECT id, batch_id, type, source_id, candidate_id, url, title, content, author, trace_id, published_at, fetched_at, created_at, deleted_at, metadata
FROM contents
WHERE batch_id = $1
  AND deleted_at IS NULL
ORDER BY published_at ASC, created_at ASC
`

func (q *Queries) ListContentsByBatchID(ctx context.Context, batchID pgtype.UUID) ([]Content, error) {
	rows, err := q.db.Query(ctx, listContentsByBatchID, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Type,
			&i.SourceID,
			&i.CandidateID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.Author,
			&i.TraceID,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSeedContents = `-- name: ListRecentSeedContents :many
SELECT id, batch_id, type, source_id, candidate_id, url, title, content, author, trace_id, published_at, fetched_at, created_at, deleted_at, metadata
FROM contents
WHERE type = 'PARTY_RELEASE'
  AND deleted_at IS NULL
ORDER BY published_at DESC, created_at DESC
LIMIT $1
`

func (q *Queries) ListRecentSeedContents(ctx context.Context, limit int32) ([]Content, error) {
	rows, err := q.db.Query(ctx, listRecentSeedContents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Type,
			&i.SourceID,
			&i.CandidateID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.Author,
			&i.TraceID,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentMetadata = `-- name: UpdateContentMetadata :one
UPDATE contents
SET author = COALESCE($1, author),
    published_at = COALESCE($2, published_at),
    metadata = COALESCE($3, metadata)
WHERE id = $4
RETURNING id, batch_id, type, source_id, candidate_id, url, title, content, author, trace_id, published_at, fetched_at, created_at, deleted_at, metadata
`

type UpdateContentMetadataParams struct {
	Author      pgtype.Text        `db:"author" json:"author"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	ID          uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) UpdateContentMetadata(ctx context.Context, arg UpdateContentMetadataParams) (Content, error) {
	row := q.db.QueryRow(ctx, updateContentMetadata,
		arg.Author,
		arg.PublishedAt,
		arg.Metadata,
		arg.ID,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Type,
		&i.SourceID,
		&i.CandidateID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.Author,
		&i.TraceID,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}
