// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: extractions.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContentExtraction = `-- name: CreateContentExtraction :one
INSERT INTO content_extractions (
    content_id,
    model_id,
    prompt_id,
    schema_name,
    schema_version,
    title,
    summary,
    raw_result,
    trace_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, content_id, model_id, prompt_id, schema_name, schema_version, title, summary, raw_result, trace_id, created_at
`

type CreateContentExtractionParams struct {
	ContentID     uuid.UUID `db:"content_id" json:"content_id"`
	ModelID       int16     `db:"model_id" json:"model_id"`
	PromptID      uuid.UUID `db:"prompt_id" json:"prompt_id"`
	SchemaName    string    `db:"schema_name" json:"schema_name"`
	SchemaVersion int32     `db:"schema_version" json:"schema_version"`
	Title         string    `db:"title" json:"title"`
	Summary       string    `db:"summary" json:"summary"`
	RawResult     []byte    `db:"raw_result" json:"raw_result"`
	TraceID       string    `db:"trace_id" json:"trace_id"`
}

func (q *Queries) CreateContentExtraction(ctx context.Context, arg CreateContentExtractionParams) (ContentExtraction, error) {
	row := q.db.QueryRow(ctx, createContentExtraction,
		arg.ContentID,
		arg.ModelID,
		arg.PromptID,
		arg.SchemaName,
		arg.SchemaVersion,
		arg.Title,
		arg.Summary,
		arg.RawResult,
		arg.TraceID,
	)
	var i ContentExtraction
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.ModelID,
		&i.PromptID,
		&i.SchemaName,
		&i.SchemaVersion,
		&i.Title,
		&i.Summary,
		&i.RawResult,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const createContentExtractionEntity = `-- name: CreateContentExtractionEntity :exec
INSERT INTO content_extraction_entities (
    extraction_id,
    entity_id,
    surface,
    ordinal
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateContentExtractionEntityParams struct {
	ExtractionID uuid.UUID   `db:"extraction_id" json:"extraction_id"`
	EntityID     int32       `db:"entity_id" json:"entity_id"`
	Surface      string      `db:"surface" json:"surface"`
	Ordinal      pgtype.Int2 `db:"ordinal" json:"ordinal"`
}

func (q *Queries) CreateContentExtractionEntity(ctx context.Context, arg CreateContentExtractionEntityParams) error {
	_, err := q.db.Exec(ctx, createContentExtractionEntity,
		arg.ExtractionID,
		arg.EntityID,
		arg.Surface,
		arg.Ordinal,
	)
	return err
}

const getContentExtractionByID = `-- name: GetContentExtractionByID :one
SELECT id, content_id, model_id, prompt_id, schema_name, schema_version, title, summary, raw_result, trace_id, created_at
FROM content_extractions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetContentExtractionByID(ctx context.Context, id uuid.UUID) (ContentExtraction, error) {
	row := q.db.QueryRow(ctx, getContentExtractionByID, id)
	var i ContentExtraction
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.ModelID,
		&i.PromptID,
		&i.SchemaName,
		&i.SchemaVersion,
		&i.Title,
		&i.Summary,
		&i.RawResult,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const getContentExtractionSnapshot = `-- name: GetContentExtractionSnapshot :one
SELECT id, content_id, model_id, prompt_id, schema_name, schema_version, title, summary, raw_result, trace_id, created_at
FROM content_extractions
WHERE content_id = $1
  AND model_id = $2
  AND prompt_id = $3
  AND schema_version = $4
LIMIT 1
`

type GetContentExtractionSnapshotParams struct {
	ContentID     uuid.UUID `db:"content_id" json:"content_id"`
	ModelID       int16     `db:"model_id" json:"model_id"`
	PromptID      uuid.UUID `db:"prompt_id" json:"prompt_id"`
	SchemaVersion int32     `db:"schema_version" json:"schema_version"`
}

func (q *Queries) GetContentExtractionSnapshot(ctx context.Context, arg GetContentExtractionSnapshotParams) (ContentExtraction, error) {
	row := q.db.QueryRow(ctx, getContentExtractionSnapshot,
		arg.ContentID,
		arg.ModelID,
		arg.PromptID,
		arg.SchemaVersion,
	)
	var i ContentExtraction
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.ModelID,
		&i.PromptID,
		&i.SchemaName,
		&i.SchemaVersion,
		&i.Title,
		&i.Summary,
		&i.RawResult,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const getEntityByCanonicalAndType = `-- name: GetEntityByCanonicalAndType :one
SELECT id, canonical, type, created_at
FROM entities
WHERE canonical = $1
  AND type = $2
LIMIT 1
`

type GetEntityByCanonicalAndTypeParams struct {
	Canonical string     `db:"canonical" json:"canonical"`
	Type      EntityType `db:"type" json:"type"`
}

func (q *Queries) GetEntityByCanonicalAndType(ctx context.Context, arg GetEntityByCanonicalAndTypeParams) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByCanonicalAndType, arg.Canonical, arg.Type)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Canonical,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const replaceContentExtractionPhrases = `-- name: ReplaceContentExtractionPhrases :exec
WITH deleted AS (
    DELETE FROM content_extraction_phrases
    WHERE extraction_id = $1
)
INSERT INTO content_extraction_phrases (
    extraction_id,
    phrase,
    ordinal
)
SELECT
    $1,
    phrase,
    ordinality::smallint
FROM unnest($2::text[]) WITH ORDINALITY AS t(phrase, ordinality)
`

type ReplaceContentExtractionPhrasesParams struct {
	ExtractionID uuid.UUID `db:"extraction_id" json:"extraction_id"`
	Column2      []string  `db:"column_2" json:"column_2"`
}

func (q *Queries) ReplaceContentExtractionPhrases(ctx context.Context, arg ReplaceContentExtractionPhrasesParams) error {
	_, err := q.db.Exec(ctx, replaceContentExtractionPhrases, arg.ExtractionID, arg.Column2)
	return err
}

const replaceContentExtractionTopics = `-- name: ReplaceContentExtractionTopics :exec
WITH deleted AS (
    DELETE FROM content_extraction_topics
    WHERE extraction_id = $1
)
INSERT INTO content_extraction_topics (
    extraction_id,
    topic_text,
    ordinal
)
SELECT
    $1,
    topic_text,
    ordinality::smallint
FROM unnest($2::text[]) WITH ORDINALITY AS t(topic_text, ordinality)
`

type ReplaceContentExtractionTopicsParams struct {
	ExtractionID uuid.UUID `db:"extraction_id" json:"extraction_id"`
	Column2      []string  `db:"column_2" json:"column_2"`
}

func (q *Queries) ReplaceContentExtractionTopics(ctx context.Context, arg ReplaceContentExtractionTopicsParams) error {
	_, err := q.db.Exec(ctx, replaceContentExtractionTopics, arg.ExtractionID, arg.Column2)
	return err
}

const upsertEntity = `-- name: UpsertEntity :one
INSERT INTO entities (
    canonical,
    type
) VALUES (
    $1,
    $2
)
ON CONFLICT (canonical, type) DO UPDATE
SET canonical = EXCLUDED.canonical
RETURNING id, canonical, type, created_at
`

type UpsertEntityParams struct {
	Canonical string     `db:"canonical" json:"canonical"`
	Type      EntityType `db:"type" json:"type"`
}

func (q *Queries) UpsertEntity(ctx context.Context, arg UpsertEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, upsertEntity, arg.Canonical, arg.Type)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Canonical,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
