// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prompts.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPromptVersion = `-- name: CreatePromptVersion :one
WITH locked AS (
    SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
)
INSERT INTO prompts (name, version, hash, size_bytes)
SELECT $1, COALESCE(MAX(p.version), 0) + 1, $2, $3
FROM prompts AS p, locked
WHERE p.name = $1
RETURNING id, name AS key, version, hash, size_bytes, created_at
`

type CreatePromptVersionParams struct {
	Name      string `db:"name" json:"name"`
	Hash      string `db:"hash" json:"hash"`
	SizeBytes int64  `db:"size_bytes" json:"size_bytes"`
}

type CreatePromptVersionRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Key       string             `db:"key" json:"key"`
	Version   int32              `db:"version" json:"version"`
	Hash      string             `db:"hash" json:"hash"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) (CreatePromptVersionRow, error) {
	row := q.db.QueryRow(ctx, createPromptVersion, arg.Name, arg.Hash, arg.SizeBytes)
	var i CreatePromptVersionRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Version,
		&i.Hash,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPromptVersionByName = `-- name: GetLatestPromptVersionByName :one
SELECT id, name AS key, version, hash, size_bytes, created_at
FROM prompts
WHERE name = $1
ORDER BY version DESC
LIMIT 1
`

type GetLatestPromptVersionByNameRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Key       string             `db:"key" json:"key"`
	Version   int32              `db:"version" json:"version"`
	Hash      string             `db:"hash" json:"hash"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetLatestPromptVersionByName(ctx context.Context, name string) (GetLatestPromptVersionByNameRow, error) {
	row := q.db.QueryRow(ctx, getLatestPromptVersionByName, name)
	var i GetLatestPromptVersionByNameRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Version,
		&i.Hash,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptVersionByID = `-- name: GetPromptVersionByID :one
SELECT
    id,
    name AS key,
    version,
    hash,
    size_bytes,
    created_at
FROM prompts
WHERE id = $1
LIMIT 1
`

type GetPromptVersionByIDRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Key       string             `db:"key" json:"key"`
	Version   int32              `db:"version" json:"version"`
	Hash      string             `db:"hash" json:"hash"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetPromptVersionByID(ctx context.Context, id uuid.UUID) (GetPromptVersionByIDRow, error) {
	row := q.db.QueryRow(ctx, getPromptVersionByID, id)
	var i GetPromptVersionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Version,
		&i.Hash,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listPromptVersions = `-- name: ListPromptVersions :many
SELECT
    id,
    name AS key,
    version,
    hash,
    size_bytes,
    created_at
FROM prompts
ORDER BY name ASC, version DESC
LIMIT $2
OFFSET $1
`

type ListPromptVersionsParams struct {
	Off int32 `db:"off" json:"off"`
	Lim int32 `db:"lim" json:"lim"`
}

type ListPromptVersionsRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Key       string             `db:"key" json:"key"`
	Version   int32              `db:"version" json:"version"`
	Hash      string             `db:"hash" json:"hash"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListPromptVersions(ctx context.Context, arg ListPromptVersionsParams) ([]ListPromptVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPromptVersions, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromptVersionsRow
	for rows.Next() {
		var i ListPromptVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Version,
			&i.Hash,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptVersionsByKey = `-- name: ListPromptVersionsByKey :many
SELECT
    id,
    name AS key,
    version,
    hash,
    size_bytes,
    created_at
FROM prompts
WHERE name = $1
ORDER BY version DESC
LIMIT $3
OFFSET $2
`

type ListPromptVersionsByKeyParams struct {
	Key string `db:"key" json:"key"`
	Off int32  `db:"off" json:"off"`
	Lim int32  `db:"lim" json:"lim"`
}

type ListPromptVersionsByKeyRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Key       string             `db:"key" json:"key"`
	Version   int32              `db:"version" json:"version"`
	Hash      string             `db:"hash" json:"hash"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListPromptVersionsByKey(ctx context.Context, arg ListPromptVersionsByKeyParams) ([]ListPromptVersionsByKeyRow, error) {
	rows, err := q.db.Query(ctx, listPromptVersionsByKey, arg.Key, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromptVersionsByKeyRow
	for rows.Next() {
		var i ListPromptVersionsByKeyRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Version,
			&i.Hash,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
