// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prompts.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPromptVersionByID = `-- name: GetPromptVersionByID :one
SELECT
    pv.id,
    pk.id AS key_id,
    pk.key,
    pv.version,
    pv.hash,
    pv.path,
    pv.size_bytes,
    pv.created_at
FROM prompt_versions pv
JOIN prompt_keys pk ON pk.id = pv.key_id
WHERE pv.id = $1
LIMIT 1
`

type GetPromptVersionByIDRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	KeyID     uuid.UUID          `db:"key_id" json:"key_id"`
	Key       string             `db:"key" json:"key"`
	Version   int32              `db:"version" json:"version"`
	Hash      string             `db:"hash" json:"hash"`
	Path      string             `db:"path" json:"path"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetPromptVersionByID(ctx context.Context, id uuid.UUID) (GetPromptVersionByIDRow, error) {
	row := q.db.QueryRow(ctx, getPromptVersionByID, id)
	var i GetPromptVersionByIDRow
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.Key,
		&i.Version,
		&i.Hash,
		&i.Path,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listPromptVersions = `-- name: ListPromptVersions :many
SELECT
    pv.id,
    pk.id AS key_id,
    pk.key,
    pv.version,
    pv.hash,
    pv.path,
    pv.size_bytes,
    pv.created_at
FROM prompt_versions pv
JOIN prompt_keys pk ON pk.id = pv.key_id
ORDER BY pk.key ASC, pv.version DESC
LIMIT $2
OFFSET $1
`

type ListPromptVersionsParams struct {
	Off int32 `db:"off" json:"off"`
	Lim int32 `db:"lim" json:"lim"`
}

type ListPromptVersionsRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	KeyID     uuid.UUID          `db:"key_id" json:"key_id"`
	Key       string             `db:"key" json:"key"`
	Version   int32              `db:"version" json:"version"`
	Hash      string             `db:"hash" json:"hash"`
	Path      string             `db:"path" json:"path"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListPromptVersions(ctx context.Context, arg ListPromptVersionsParams) ([]ListPromptVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPromptVersions, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromptVersionsRow
	for rows.Next() {
		var i ListPromptVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.Key,
			&i.Version,
			&i.Hash,
			&i.Path,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptVersionsByKey = `-- name: ListPromptVersionsByKey :many
SELECT
    pv.id,
    pk.id AS key_id,
    pk.key,
    pv.version,
    pv.hash,
    pv.path,
    pv.size_bytes,
    pv.created_at
FROM prompt_versions pv
JOIN prompt_keys pk ON pk.id = pv.key_id
WHERE pk.key = $1
ORDER BY pv.version DESC
LIMIT $3
OFFSET $2
`

type ListPromptVersionsByKeyParams struct {
	Key string `db:"key" json:"key"`
	Off int32  `db:"off" json:"off"`
	Lim int32  `db:"lim" json:"lim"`
}

type ListPromptVersionsByKeyRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	KeyID     uuid.UUID          `db:"key_id" json:"key_id"`
	Key       string             `db:"key" json:"key"`
	Version   int32              `db:"version" json:"version"`
	Hash      string             `db:"hash" json:"hash"`
	Path      string             `db:"path" json:"path"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListPromptVersionsByKey(ctx context.Context, arg ListPromptVersionsByKeyParams) ([]ListPromptVersionsByKeyRow, error) {
	rows, err := q.db.Query(ctx, listPromptVersionsByKey, arg.Key, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromptVersionsByKeyRow
	for rows.Next() {
		var i ListPromptVersionsByKeyRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.Key,
			&i.Version,
			&i.Hash,
			&i.Path,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPromptVersion = `-- name: UpsertPromptVersion :one
WITH prompt_key AS (
    INSERT INTO prompt_keys (key)
    VALUES ($1)
    ON CONFLICT (key) DO UPDATE SET key = EXCLUDED.key
    RETURNING id, key
), existing AS (
    SELECT
        pv.id,
        pk.id AS key_id,
        pk.key,
        pv.version,
        pv.hash,
        pv.path,
        pv.size_bytes,
        pv.created_at
    FROM prompt_versions pv
    JOIN prompt_key pk ON pk.id = pv.key_id
    WHERE pv.hash = $2
), next_version AS (
    SELECT COALESCE(MAX(pv.version), 0) + 1 AS version
    FROM prompt_versions pv
    JOIN prompt_key pk ON pk.id = pv.key_id
), inserted AS (
    INSERT INTO prompt_versions (key_id, version, hash, path, size_bytes)
    SELECT pk.id, nv.version, $2, $3, $4
    FROM prompt_key pk
    CROSS JOIN next_version nv
    WHERE NOT EXISTS (SELECT 1 FROM existing)
    RETURNING id, key_id, version, hash, path, size_bytes, created_at
)
SELECT
    i.id,
    i.key_id,
    pk.key,
    i.version,
    i.hash,
    i.path,
    i.size_bytes,
    i.created_at
FROM inserted i
JOIN prompt_key pk ON pk.id = i.key_id
UNION ALL
SELECT id, key_id, key, version, hash, path, size_bytes, created_at FROM existing
LIMIT 1
`

type UpsertPromptVersionParams struct {
	Key       string `db:"key" json:"key"`
	Hash      string `db:"hash" json:"hash"`
	Path      string `db:"path" json:"path"`
	SizeBytes int64  `db:"size_bytes" json:"size_bytes"`
}

type UpsertPromptVersionRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	KeyID     uuid.UUID          `db:"key_id" json:"key_id"`
	Key       string             `db:"key" json:"key"`
	Version   int32              `db:"version" json:"version"`
	Hash      string             `db:"hash" json:"hash"`
	Path      string             `db:"path" json:"path"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertPromptVersion(ctx context.Context, arg UpsertPromptVersionParams) (UpsertPromptVersionRow, error) {
	row := q.db.QueryRow(ctx, upsertPromptVersion,
		arg.Key,
		arg.Hash,
		arg.Path,
		arg.SizeBytes,
	)
	var i UpsertPromptVersionRow
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.Key,
		&i.Version,
		&i.Hash,
		&i.Path,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}
