// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimTasks(ctx context.Context, arg ClaimTasksParams) ([]Task, error)
	CompleteTask(ctx context.Context, id uuid.UUID) error
	CountCandidatesByBatchID(ctx context.Context, batchID pgtype.UUID) (int64, error)
	CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error)
	CreateCandidateEmbeddingGemma2025(ctx context.Context, arg CreateCandidateEmbeddingGemma2025Params) (CandidateEmbeddingsGemma2025, error)
	CreateContent(ctx context.Context, arg CreateContentParams) (Content, error)
	CreateContentEmbeddingGemma2025(ctx context.Context, arg CreateContentEmbeddingGemma2025Params) (ContentEmbeddingsGemma2025, error)
	CreateContentExtraction(ctx context.Context, arg CreateContentExtractionParams) (ContentExtraction, error)
	CreateContentExtractionEntity(ctx context.Context, arg CreateContentExtractionEntityParams) error
	// Single-round-trip insert-or-recover. On unique-violation against either
	// uq_tasks_active_payload or uq_tasks_active_page_fetch, returns the
	// existing PENDING/RUNNING row with inserted=false. Adapter maps
	// inserted=false to repo.ErrTaskAlreadyActive while still surfacing the
	// recovered task fields, so callers that need the existing task_id (e.g.
	// the user-fetch handler) avoid a second SELECT.
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	CreateUserFetch(ctx context.Context, userID pgtype.UUID) (Fetch, error)
	CreateUserFetchItem(ctx context.Context, arg CreateUserFetchItemParams) (FetchItem, error)
	EnsureBatchExists(ctx context.Context, arg EnsureBatchExistsParams) error
	// Updates expires_at on an existing PENDING/RUNNING task identified by its dedup key.
	// Used when CreateTask returns ErrTaskAlreadyActive to refresh the task's lifetime.
	ExtendActiveTaskExpiry(ctx context.Context, arg ExtendActiveTaskExpiryParams) error
	FailTask(ctx context.Context, id uuid.UUID) error
	// Finds batches where all tasks are completed and all candidates are promoted to contents.
	FindNewlyCompletedBatches(ctx context.Context, arg FindNewlyCompletedBatchesParams) ([]FindNewlyCompletedBatchesRow, error)
	GetCandidateByFingerprint(ctx context.Context, fingerprint string) (Candidate, error)
	GetCandidateByID(ctx context.Context, id uuid.UUID) (Candidate, error)
	GetCandidatesByIDs(ctx context.Context, ids []uuid.UUID) ([]Candidate, error)
	GetContentByCandidateID(ctx context.Context, candidateID pgtype.UUID) (Content, error)
	GetContentByID(ctx context.Context, id uuid.UUID) (Content, error)
	GetContentByURL(ctx context.Context, url string) (Content, error)
	GetContentExtractionByID(ctx context.Context, id uuid.UUID) (ContentExtraction, error)
	GetContentExtractionSnapshot(ctx context.Context, arg GetContentExtractionSnapshotParams) (ContentExtraction, error)
	GetEntityByCanonicalAndType(ctx context.Context, arg GetEntityByCanonicalAndTypeParams) (Entity, error)
	GetModelByID(ctx context.Context, id int16) (Model, error)
	GetModelByNameAndType(ctx context.Context, arg GetModelByNameAndTypeParams) (Model, error)
	GetPromptByHash(ctx context.Context, hash string) (Prompt, error)
	GetPromptByID(ctx context.Context, id uuid.UUID) (Prompt, error)
	GetSourceByAbbr(ctx context.Context, abbr string) (Source, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	GetUserFetch(ctx context.Context, id uuid.UUID) (Fetch, error)
	// Aggregates item status using COALESCE(snapshot_status, tasks.status).
	// Returns counters plus a derived `terminal` flag (all items in COMPLETED /
	// FAILED / ALREADY_COMPLETE).
	GetUserFetchProgress(ctx context.Context, fetchID uuid.UUID) (GetUserFetchProgressRow, error)
	ListCandidateEmbeddingsByCandidateID(ctx context.Context, candidateID uuid.UUID) ([]CandidateEmbeddingsGemma2025, error)
	ListCandidates(ctx context.Context, arg ListCandidatesParams) ([]Candidate, error)
	ListCandidatesForAnalysis(ctx context.Context, arg ListCandidatesForAnalysisParams) ([]Candidate, error)
	ListContentEmbeddingsByContentID(ctx context.Context, contentID uuid.UUID) ([]ContentEmbeddingsGemma2025, error)
	ListContentsByBatchID(ctx context.Context, batchID pgtype.UUID) ([]Content, error)
	ListPendingCompletionBatches(ctx context.Context, arg ListPendingCompletionBatchesParams) ([]Batch, error)
	ListReadyToPublishBatches(ctx context.Context, arg ListReadyToPublishBatchesParams) ([]Batch, error)
	ListRecentSeedContents(ctx context.Context, limit int32) ([]Content, error)
	ListRunnableTasks(ctx context.Context, limit int32) ([]Task, error)
	ListSourcesByType(ctx context.Context, type_ SourceType) ([]Source, error)
	ListTasksByBatchID(ctx context.Context, batchID uuid.UUID) ([]Task, error)
	ListUserFetchItems(ctx context.Context, fetchID uuid.UUID) ([]ListUserFetchItemsRow, error)
	// Optimistic-concurrency claim: returns rows-affected so the caller can
	// distinguish the winner (1) from a loser racing against another instance
	// (0). Only the winner should publish the batch.completed signal.
	MarkBatchCompleted(ctx context.Context, arg MarkBatchCompletedParams) (int64, error)
	MarkBatchPublished(ctx context.Context, id uuid.UUID) error
	// Sets completed_at on transition to terminal. Idempotent (WHERE clause
	// guards against double-set). v1 callers may skip this — progress endpoint
	// computes terminal on-the-fly. Reserved for v2 notification dispatcher.
	MarkUserFetchCompleted(ctx context.Context, id uuid.UUID) error
	RecordBatchPublishFailure(ctx context.Context, arg RecordBatchPublishFailureParams) error
	// Resets RUNNING tasks back to PENDING in bulk, undoing the ClaimTasks
	// retry_count increment. Used when dispatch is skipped (e.g. rate-limited)
	// so tasks are retried on the next scheduler tick without consuming retry slots.
	ReleaseTasks(ctx context.Context, ids []uuid.UUID) error
	ReplaceContentExtractionPhrases(ctx context.Context, arg ReplaceContentExtractionPhrasesParams) error
	ReplaceContentExtractionTopics(ctx context.Context, arg ReplaceContentExtractionTopicsParams) error
	SearchCandidatesByText(ctx context.Context, arg SearchCandidatesByTextParams) ([]Candidate, error)
	SearchCandidatesByVector(ctx context.Context, arg SearchCandidatesByVectorParams) ([]SearchCandidatesByVectorRow, error)
	SearchContentsByVector(ctx context.Context, arg SearchContentsByVectorParams) ([]SearchContentsByVectorRow, error)
	UpdateContentMetadata(ctx context.Context, arg UpdateContentMetadataParams) (Content, error)
	UpsertCandidate(ctx context.Context, arg UpsertCandidateParams) (Candidate, error)
	UpsertEntity(ctx context.Context, arg UpsertEntityParams) (Entity, error)
	UpsertPrompt(ctx context.Context, arg UpsertPromptParams) (Prompt, error)
}

var _ Querier = (*Queries)(nil)
