// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry.sql

package pg

import (
	"context"

	"github.com/google/uuid"
)

const getModelByID = `-- name: GetModelByID :one
SELECT id, name, provider, type, publish_date, url, tag, created_at, deleted_at
FROM models
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetModelByID(ctx context.Context, id int16) (Model, error) {
	row := q.db.QueryRow(ctx, getModelByID, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Type,
		&i.PublishDate,
		&i.Url,
		&i.Tag,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getModelByNameAndType = `-- name: GetModelByNameAndType :one
SELECT id, name, provider, type, publish_date, url, tag, created_at, deleted_at
FROM models
WHERE name = $1
  AND type = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetModelByNameAndTypeParams struct {
	Name string    `db:"name" json:"name"`
	Type ModelType `db:"type" json:"type"`
}

func (q *Queries) GetModelByNameAndType(ctx context.Context, arg GetModelByNameAndTypeParams) (Model, error) {
	row := q.db.QueryRow(ctx, getModelByNameAndType, arg.Name, arg.Type)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Type,
		&i.PublishDate,
		&i.Url,
		&i.Tag,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPromptByHash = `-- name: GetPromptByHash :one
SELECT id, hash, path, created_at
FROM prompts
WHERE hash = $1
LIMIT 1
`

func (q *Queries) GetPromptByHash(ctx context.Context, hash string) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByHash, hash)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptByID = `-- name: GetPromptByID :one
SELECT id, hash, path, created_at
FROM prompts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPromptByID(ctx context.Context, id uuid.UUID) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByID, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceByAbbr = `-- name: GetSourceByAbbr :one
SELECT id, abbr, name, type, base_url, created_at, deleted_at
FROM sources
WHERE abbr = $1
LIMIT 1
`

func (q *Queries) GetSourceByAbbr(ctx context.Context, abbr string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByAbbr, abbr)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Abbr,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, abbr, name, type, base_url, created_at, deleted_at
FROM sources
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSourceByID(ctx context.Context, id int32) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Abbr,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSourcesByType = `-- name: ListSourcesByType :many
SELECT id, abbr, name, type, base_url, created_at, deleted_at
FROM sources
WHERE type = $1
  AND deleted_at IS NULL
ORDER BY abbr ASC
`

func (q *Queries) ListSourcesByType(ctx context.Context, type_ SourceType) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Abbr,
			&i.Name,
			&i.Type,
			&i.BaseUrl,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPrompt = `-- name: UpsertPrompt :one
INSERT INTO prompts (
    hash,
    path
) VALUES (
    $1,
    $2
)
ON CONFLICT (hash) DO UPDATE
SET path = EXCLUDED.path
RETURNING id, hash, path, created_at
`

type UpsertPromptParams struct {
	Hash string `db:"hash" json:"hash"`
	Path string `db:"path" json:"path"`
}

func (q *Queries) UpsertPrompt(ctx context.Context, arg UpsertPromptParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, upsertPrompt, arg.Hash, arg.Path)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}
