// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeReportTask = `-- name: CompleteReportTask :execrows
UPDATE tasks AS t
SET status = 'COMPLETED',
    failure_message = NULL,
    updated_at = clock_timestamp()
FROM batches AS b
WHERE t.id = $1
  AND t.batch_id = $2
  AND t.kind = 'PIPELINE_STAGE'
  AND t.url = 'pipeline://stage/generate_report'
  AND t.status = 'RUNNING'
  AND b.id = t.batch_id
  AND b.analysis_execution_id = $3
  AND b.completed_at IS NULL
  AND EXISTS (
      SELECT 1 FROM reports r
      WHERE r.analysis_execution_id = $3
        AND r.root_batch_id = t.batch_id
        AND r.storage_uri = $4
        AND r.byte_size = $5
        AND r.sha256 = $6
  )
`

type CompleteReportTaskParams struct {
	TaskID              uuid.UUID   `db:"task_id" json:"task_id"`
	RootBatchID         uuid.UUID   `db:"root_batch_id" json:"root_batch_id"`
	AnalysisExecutionID pgtype.UUID `db:"analysis_execution_id" json:"analysis_execution_id"`
	StorageUri          string      `db:"storage_uri" json:"storage_uri"`
	ByteSize            int64       `db:"byte_size" json:"byte_size"`
	Sha256              string      `db:"sha256" json:"sha256"`
}

func (q *Queries) CompleteReportTask(ctx context.Context, arg CompleteReportTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeReportTask,
		arg.TaskID,
		arg.RootBatchID,
		arg.AnalysisExecutionID,
		arg.StorageUri,
		arg.ByteSize,
		arg.Sha256,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureAnalysisExecution = `-- name: EnsureAnalysisExecution :exec
INSERT INTO analysis_executions (id, report_fingerprint)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
SET report_fingerprint = EXCLUDED.report_fingerprint
`

type EnsureAnalysisExecutionParams struct {
	ID                uuid.UUID `db:"id" json:"id"`
	ReportFingerprint string    `db:"report_fingerprint" json:"report_fingerprint"`
}

func (q *Queries) EnsureAnalysisExecution(ctx context.Context, arg EnsureAnalysisExecutionParams) error {
	_, err := q.db.Exec(ctx, ensureAnalysisExecution, arg.ID, arg.ReportFingerprint)
	return err
}

const findReportCacheHit = `-- name: FindReportCacheHit :one
SELECT id, analysis_execution_id, root_batch_id, storage_uri, byte_size, sha256, expires_at, artifact_missing_at, artifact_corrupt_at, artifact_corruption_reason, artifact_removed_at, artifact_removed_by, artifact_removal_reason, created_at, updated_at
FROM reports
WHERE analysis_execution_id = $1
  AND expires_at > clock_timestamp()
  AND artifact_missing_at IS NULL
  AND artifact_corrupt_at IS NULL
  AND artifact_removed_at IS NULL
`

func (q *Queries) FindReportCacheHit(ctx context.Context, analysisExecutionID uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, findReportCacheHit, analysisExecutionID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AnalysisExecutionID,
		&i.RootBatchID,
		&i.StorageUri,
		&i.ByteSize,
		&i.Sha256,
		&i.ExpiresAt,
		&i.ArtifactMissingAt,
		&i.ArtifactCorruptAt,
		&i.ArtifactCorruptionReason,
		&i.ArtifactRemovedAt,
		&i.ArtifactRemovedBy,
		&i.ArtifactRemovalReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportByExecutionID = `-- name: GetReportByExecutionID :one
SELECT id, analysis_execution_id, root_batch_id, storage_uri, byte_size, sha256, expires_at, artifact_missing_at, artifact_corrupt_at, artifact_corruption_reason, artifact_removed_at, artifact_removed_by, artifact_removal_reason, created_at, updated_at FROM reports WHERE analysis_execution_id = $1
`

func (q *Queries) GetReportByExecutionID(ctx context.Context, analysisExecutionID uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByExecutionID, analysisExecutionID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AnalysisExecutionID,
		&i.RootBatchID,
		&i.StorageUri,
		&i.ByteSize,
		&i.Sha256,
		&i.ExpiresAt,
		&i.ArtifactMissingAt,
		&i.ArtifactCorruptAt,
		&i.ArtifactCorruptionReason,
		&i.ArtifactRemovedAt,
		&i.ArtifactRemovedBy,
		&i.ArtifactRemovalReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, analysis_execution_id, root_batch_id, storage_uri, byte_size, sha256, expires_at, artifact_missing_at, artifact_corrupt_at, artifact_corruption_reason, artifact_removed_at, artifact_removed_by, artifact_removal_reason, created_at, updated_at FROM reports WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AnalysisExecutionID,
		&i.RootBatchID,
		&i.StorageUri,
		&i.ByteSize,
		&i.Sha256,
		&i.ExpiresAt,
		&i.ArtifactMissingAt,
		&i.ArtifactCorruptAt,
		&i.ArtifactCorruptionReason,
		&i.ArtifactRemovedAt,
		&i.ArtifactRemovedBy,
		&i.ArtifactRemovalReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (
    analysis_execution_id,
    root_batch_id,
    storage_uri,
    byte_size,
    sha256,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (analysis_execution_id) DO NOTHING
RETURNING id, analysis_execution_id, root_batch_id, storage_uri, byte_size, sha256, expires_at, artifact_missing_at, artifact_corrupt_at, artifact_corruption_reason, artifact_removed_at, artifact_removed_by, artifact_removal_reason, created_at, updated_at
`

type InsertReportParams struct {
	AnalysisExecutionID uuid.UUID          `db:"analysis_execution_id" json:"analysis_execution_id"`
	RootBatchID         uuid.UUID          `db:"root_batch_id" json:"root_batch_id"`
	StorageUri          string             `db:"storage_uri" json:"storage_uri"`
	ByteSize            int64              `db:"byte_size" json:"byte_size"`
	Sha256              string             `db:"sha256" json:"sha256"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, insertReport,
		arg.AnalysisExecutionID,
		arg.RootBatchID,
		arg.StorageUri,
		arg.ByteSize,
		arg.Sha256,
		arg.ExpiresAt,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AnalysisExecutionID,
		&i.RootBatchID,
		&i.StorageUri,
		&i.ByteSize,
		&i.Sha256,
		&i.ExpiresAt,
		&i.ArtifactMissingAt,
		&i.ArtifactCorruptAt,
		&i.ArtifactCorruptionReason,
		&i.ArtifactRemovedAt,
		&i.ArtifactRemovedBy,
		&i.ArtifactRemovalReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReportAuditEvent = `-- name: InsertReportAuditEvent :exec
INSERT INTO report_audit_events (
    report_id,
    analysis_execution_id,
    event_type,
    actor_token_id,
    actor_component,
    actor_name,
    reason,
    request_id,
    storage_uri,
    storage_outcome,
    storage_error
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type InsertReportAuditEventParams struct {
	ReportID            uuid.UUID   `db:"report_id" json:"report_id"`
	AnalysisExecutionID uuid.UUID   `db:"analysis_execution_id" json:"analysis_execution_id"`
	EventType           string      `db:"event_type" json:"event_type"`
	ActorTokenID        pgtype.UUID `db:"actor_token_id" json:"actor_token_id"`
	ActorComponent      string      `db:"actor_component" json:"actor_component"`
	ActorName           pgtype.Text `db:"actor_name" json:"actor_name"`
	Reason              pgtype.Text `db:"reason" json:"reason"`
	RequestID           pgtype.Text `db:"request_id" json:"request_id"`
	StorageUri          string      `db:"storage_uri" json:"storage_uri"`
	StorageOutcome      string      `db:"storage_outcome" json:"storage_outcome"`
	StorageError        pgtype.Text `db:"storage_error" json:"storage_error"`
}

func (q *Queries) InsertReportAuditEvent(ctx context.Context, arg InsertReportAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertReportAuditEvent,
		arg.ReportID,
		arg.AnalysisExecutionID,
		arg.EventType,
		arg.ActorTokenID,
		arg.ActorComponent,
		arg.ActorName,
		arg.Reason,
		arg.RequestID,
		arg.StorageUri,
		arg.StorageOutcome,
		arg.StorageError,
	)
	return err
}

const lockAnalysisExecution = `-- name: LockAnalysisExecution :one
SELECT id FROM analysis_executions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAnalysisExecution(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockAnalysisExecution, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockReportByExecutionID = `-- name: LockReportByExecutionID :one
SELECT id, analysis_execution_id, root_batch_id, storage_uri, byte_size, sha256, expires_at, artifact_missing_at, artifact_corrupt_at, artifact_corruption_reason, artifact_removed_at, artifact_removed_by, artifact_removal_reason, created_at, updated_at FROM reports
WHERE analysis_execution_id = $1
FOR UPDATE
`

func (q *Queries) LockReportByExecutionID(ctx context.Context, analysisExecutionID uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, lockReportByExecutionID, analysisExecutionID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AnalysisExecutionID,
		&i.RootBatchID,
		&i.StorageUri,
		&i.ByteSize,
		&i.Sha256,
		&i.ExpiresAt,
		&i.ArtifactMissingAt,
		&i.ArtifactCorruptAt,
		&i.ArtifactCorruptionReason,
		&i.ArtifactRemovedAt,
		&i.ArtifactRemovedBy,
		&i.ArtifactRemovalReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockReportForRemoval = `-- name: LockReportForRemoval :one
SELECT id, analysis_execution_id, root_batch_id, storage_uri, byte_size, sha256, expires_at, artifact_missing_at, artifact_corrupt_at, artifact_corruption_reason, artifact_removed_at, artifact_removed_by, artifact_removal_reason, created_at, updated_at FROM reports
WHERE analysis_execution_id = $1
FOR UPDATE
`

func (q *Queries) LockReportForRemoval(ctx context.Context, analysisExecutionID uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, lockReportForRemoval, analysisExecutionID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AnalysisExecutionID,
		&i.RootBatchID,
		&i.StorageUri,
		&i.ByteSize,
		&i.Sha256,
		&i.ExpiresAt,
		&i.ArtifactMissingAt,
		&i.ArtifactCorruptAt,
		&i.ArtifactCorruptionReason,
		&i.ArtifactRemovedAt,
		&i.ArtifactRemovedBy,
		&i.ArtifactRemovalReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockReportRoot = `-- name: LockReportRoot :one
SELECT id, source_type, trace_id, created_at, updated_at, completed_at, published_at, last_publish_attempt_at, publish_retry_count, publish_error, stalled_at, n_subtasks, parent_id, parent_task_id, succeeded, pipeline_published_at, pipeline_publish_retry_count, pipeline_publish_error, purpose, pipeline_definition_hash, pipeline_idempotency_key, pipeline_request_fingerprint, pipeline_input_snapshot_at, analysis_execution_id, failure_kind, failure_task_id, failure_recorded_at FROM batches
WHERE id = $1
  AND analysis_execution_id = $2
  AND completed_at IS NULL
FOR UPDATE
`

type LockReportRootParams struct {
	ID                  uuid.UUID   `db:"id" json:"id"`
	AnalysisExecutionID pgtype.UUID `db:"analysis_execution_id" json:"analysis_execution_id"`
}

func (q *Queries) LockReportRoot(ctx context.Context, arg LockReportRootParams) (Batch, error) {
	row := q.db.QueryRow(ctx, lockReportRoot, arg.ID, arg.AnalysisExecutionID)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PublishedAt,
		&i.LastPublishAttemptAt,
		&i.PublishRetryCount,
		&i.PublishError,
		&i.StalledAt,
		&i.NSubtasks,
		&i.ParentID,
		&i.ParentTaskID,
		&i.Succeeded,
		&i.PipelinePublishedAt,
		&i.PipelinePublishRetryCount,
		&i.PipelinePublishError,
		&i.Purpose,
		&i.PipelineDefinitionHash,
		&i.PipelineIdempotencyKey,
		&i.PipelineRequestFingerprint,
		&i.PipelineInputSnapshotAt,
		&i.AnalysisExecutionID,
		&i.FailureKind,
		&i.FailureTaskID,
		&i.FailureRecordedAt,
	)
	return i, err
}

const lockReportTask = `-- name: LockReportTask :one
SELECT id, batch_id, kind, source_type, source_abbr, url, payload, payload_hash, meta, trace_id, frequency, next_run_at, expires_at, status, retry_count, failure_message, last_run_at, created_at, updated_at, previous_task_id, next_task_id, logical_key FROM tasks WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockReportTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, lockReportTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Kind,
		&i.SourceType,
		&i.SourceAbbr,
		&i.Url,
		&i.Payload,
		&i.PayloadHash,
		&i.Meta,
		&i.TraceID,
		&i.Frequency,
		&i.NextRunAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RetryCount,
		&i.FailureMessage,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviousTaskID,
		&i.NextTaskID,
		&i.LogicalKey,
	)
	return i, err
}

const markReportCorrupt = `-- name: MarkReportCorrupt :execrows
UPDATE reports
SET artifact_corrupt_at = clock_timestamp(),
    artifact_corruption_reason = $2,
    updated_at = clock_timestamp()
WHERE id = $1
  AND artifact_corrupt_at IS NULL
  AND artifact_missing_at IS NULL
  AND artifact_removed_at IS NULL
`

type MarkReportCorruptParams struct {
	ID                       uuid.UUID   `db:"id" json:"id"`
	ArtifactCorruptionReason pgtype.Text `db:"artifact_corruption_reason" json:"artifact_corruption_reason"`
}

func (q *Queries) MarkReportCorrupt(ctx context.Context, arg MarkReportCorruptParams) (int64, error) {
	result, err := q.db.Exec(ctx, markReportCorrupt, arg.ID, arg.ArtifactCorruptionReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markReportMissing = `-- name: MarkReportMissing :execrows
UPDATE reports
SET artifact_missing_at = clock_timestamp(),
    updated_at = clock_timestamp()
WHERE id = $1
  AND expires_at > clock_timestamp()
  AND artifact_missing_at IS NULL
  AND artifact_corrupt_at IS NULL
  AND artifact_removed_at IS NULL
`

func (q *Queries) MarkReportMissing(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markReportMissing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markReportRemoved = `-- name: MarkReportRemoved :execrows
UPDATE reports
SET artifact_removed_at = clock_timestamp(),
    artifact_removed_by = $1,
    artifact_removal_reason = $2,
    updated_at = clock_timestamp()
WHERE id = $3
  AND artifact_removed_at IS NULL
`

type MarkReportRemovedParams struct {
	ActorTokenID pgtype.UUID `db:"actor_token_id" json:"actor_token_id"`
	Reason       pgtype.Text `db:"reason" json:"reason"`
	ID           uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) MarkReportRemoved(ctx context.Context, arg MarkReportRemovedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markReportRemoved, arg.ActorTokenID, arg.Reason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
