// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueSchedules = `-- name: ClaimDueSchedules :many
SELECT id, name, enabled, config_present, config_hash, kind, source_type, source_abbr, url, payload, meta, frequency, run_on_insert, next_fire_at, last_fire_at, last_materialized_at, last_materialized_task_id, last_error, created_at, updated_at
FROM schedules
WHERE enabled = true
  AND config_present = true
  AND next_fire_at <= NOW()
ORDER BY next_fire_at ASC, id ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimDueSchedules(ctx context.Context, lim int32) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, claimDueSchedules, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.ConfigPresent,
			&i.ConfigHash,
			&i.Kind,
			&i.SourceType,
			&i.SourceAbbr,
			&i.Url,
			&i.Payload,
			&i.Meta,
			&i.Frequency,
			&i.RunOnInsert,
			&i.NextFireAt,
			&i.LastFireAt,
			&i.LastMaterializedAt,
			&i.LastMaterializedTaskID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, name, enabled, config_present, config_hash, kind, source_type, source_abbr, url, payload, meta, frequency, run_on_insert, next_fire_at, last_fire_at, last_materialized_at, last_materialized_task_id, last_error, created_at, updated_at
FROM schedules
ORDER BY source_type ASC, source_abbr ASC, name ASC
LIMIT $2
OFFSET $1
`

type ListSchedulesParams struct {
	Off int32 `db:"off" json:"off"`
	Lim int32 `db:"lim" json:"lim"`
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.ConfigPresent,
			&i.ConfigHash,
			&i.Kind,
			&i.SourceType,
			&i.SourceAbbr,
			&i.Url,
			&i.Payload,
			&i.Meta,
			&i.Frequency,
			&i.RunOnInsert,
			&i.NextFireAt,
			&i.LastFireAt,
			&i.LastMaterializedAt,
			&i.LastMaterializedTaskID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduleError = `-- name: MarkScheduleError :exec
UPDATE schedules
SET last_fire_at = NOW(),
    last_error = $1,
    next_fire_at = NOW() + frequency,
    updated_at = NOW()
WHERE id = $2
`

type MarkScheduleErrorParams struct {
	LastError pgtype.Text `db:"last_error" json:"last_error"`
	ID        uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) MarkScheduleError(ctx context.Context, arg MarkScheduleErrorParams) error {
	_, err := q.db.Exec(ctx, markScheduleError, arg.LastError, arg.ID)
	return err
}

const markScheduleMaterialized = `-- name: MarkScheduleMaterialized :exec
UPDATE schedules
SET last_fire_at = NOW(),
    last_materialized_at = NOW(),
    last_materialized_task_id = $1,
    last_error = NULL,
    next_fire_at = NOW() + frequency,
    updated_at = NOW()
WHERE id = $2
`

type MarkScheduleMaterializedParams struct {
	TaskID pgtype.UUID `db:"task_id" json:"task_id"`
	ID     uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) MarkScheduleMaterialized(ctx context.Context, arg MarkScheduleMaterializedParams) error {
	_, err := q.db.Exec(ctx, markScheduleMaterialized, arg.TaskID, arg.ID)
	return err
}

const markSchedulesConfigAbsent = `-- name: MarkSchedulesConfigAbsent :exec
UPDATE schedules
SET config_present = false,
    updated_at = NOW()
WHERE config_present = true
`

func (q *Queries) MarkSchedulesConfigAbsent(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markSchedulesConfigAbsent)
	return err
}

const upsertSchedule = `-- name: UpsertSchedule :one
INSERT INTO schedules (
    id,
    name,
    enabled,
    config_present,
    config_hash,
    kind,
    source_type,
    source_abbr,
    url,
    payload,
    meta,
    frequency,
    run_on_insert,
    next_fire_at
) VALUES (
    $1,
    $2,
    $3,
    true,
    $4,
    $5,
    $6,
    $7,
    $8,
    COALESCE($9::jsonb, '{}'::jsonb),
    $10::jsonb,
    $11,
    $12,
    CASE
        WHEN $12::boolean THEN NOW()
        ELSE NOW() + $11
    END
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    enabled = EXCLUDED.enabled,
    config_present = true,
    config_hash = EXCLUDED.config_hash,
    kind = EXCLUDED.kind,
    source_type = EXCLUDED.source_type,
    source_abbr = EXCLUDED.source_abbr,
    url = EXCLUDED.url,
    payload = EXCLUDED.payload,
    meta = EXCLUDED.meta,
    frequency = EXCLUDED.frequency,
    run_on_insert = EXCLUDED.run_on_insert,
    next_fire_at = CASE
        WHEN schedules.config_hash IS DISTINCT FROM EXCLUDED.config_hash THEN NOW()
        WHEN schedules.frequency IS DISTINCT FROM EXCLUDED.frequency
          OR schedules.run_on_insert IS DISTINCT FROM EXCLUDED.run_on_insert
        THEN CASE
            WHEN schedules.last_fire_at IS NOT NULL THEN schedules.last_fire_at + EXCLUDED.frequency
            WHEN EXCLUDED.run_on_insert THEN NOW()
            ELSE NOW() + EXCLUDED.frequency
        END
        ELSE schedules.next_fire_at
    END,
    updated_at = NOW()
RETURNING id, name, enabled, config_present, config_hash, kind, source_type, source_abbr, url, payload, meta, frequency, run_on_insert, next_fire_at, last_fire_at, last_materialized_at, last_materialized_task_id, last_error, created_at, updated_at
`

type UpsertScheduleParams struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	Name        string          `db:"name" json:"name"`
	Enabled     bool            `db:"enabled" json:"enabled"`
	ConfigHash  string          `db:"config_hash" json:"config_hash"`
	Kind        TaskKind        `db:"kind" json:"kind"`
	SourceType  SourceType      `db:"source_type" json:"source_type"`
	SourceAbbr  string          `db:"source_abbr" json:"source_abbr"`
	Url         string          `db:"url" json:"url"`
	Payload     []byte          `db:"payload" json:"payload"`
	Meta        []byte          `db:"meta" json:"meta"`
	Frequency   pgtype.Interval `db:"frequency" json:"frequency"`
	RunOnInsert bool            `db:"run_on_insert" json:"run_on_insert"`
}

func (q *Queries) UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, upsertSchedule,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.ConfigHash,
		arg.Kind,
		arg.SourceType,
		arg.SourceAbbr,
		arg.Url,
		arg.Payload,
		arg.Meta,
		arg.Frequency,
		arg.RunOnInsert,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.ConfigPresent,
		&i.ConfigHash,
		&i.Kind,
		&i.SourceType,
		&i.SourceAbbr,
		&i.Url,
		&i.Payload,
		&i.Meta,
		&i.Frequency,
		&i.RunOnInsert,
		&i.NextFireAt,
		&i.LastFireAt,
		&i.LastMaterializedAt,
		&i.LastMaterializedTaskID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
