// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimTasks = `-- name: ClaimTasks :many
UPDATE tasks
SET status = 'RUNNING',
    retry_count = retry_count + 1,
    last_run_at = NOW(),
    updated_at = NOW()
WHERE id IN (
    SELECT id
    FROM tasks
    WHERE (
            status = 'PENDING'
        AND next_run_at <= NOW()
        AND (expires_at IS NULL OR expires_at > NOW())
        AND kind = ANY($1::task_kind[])
        AND (
            COALESCE(array_length($2::source_type[], 1), 0) = 0
            OR source_type = ANY($2::source_type[])
        )
    ) OR (
            status = 'RUNNING'
        AND last_run_at < NOW() - INTERVAL '30 minutes'
        AND (expires_at IS NULL OR expires_at > NOW())
        AND kind = ANY($1::task_kind[])
        AND (
            COALESCE(array_length($2::source_type[], 1), 0) = 0
            OR source_type = ANY($2::source_type[])
        )
    )
    ORDER BY next_run_at ASC
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, batch_id, kind, source_type, source_abbr, url, payload, payload_hash, meta, trace_id, frequency, next_run_at, expires_at, status, retry_count, last_run_at, created_at, updated_at
`

type ClaimTasksParams struct {
	Kinds       []TaskKind   `db:"kinds" json:"kinds"`
	SourceTypes []SourceType `db:"source_types" json:"source_types"`
	MaxTasks    int32        `db:"max_tasks" json:"max_tasks"`
}

func (q *Queries) ClaimTasks(ctx context.Context, arg ClaimTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, claimTasks, arg.Kinds, arg.SourceTypes, arg.MaxTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Kind,
			&i.SourceType,
			&i.SourceAbbr,
			&i.Url,
			&i.Payload,
			&i.PayloadHash,
			&i.Meta,
			&i.TraceID,
			&i.Frequency,
			&i.NextRunAt,
			&i.ExpiresAt,
			&i.Status,
			&i.RetryCount,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeTask = `-- name: CompleteTask :exec
UPDATE tasks
SET status = CASE
        WHEN frequency IS NOT NULL
         AND (expires_at IS NULL OR NOW() + frequency <= expires_at)
            THEN 'PENDING'::task_status
        ELSE 'COMPLETED'::task_status
    END,
    next_run_at = CASE
        WHEN frequency IS NOT NULL
         AND (expires_at IS NULL OR NOW() + frequency <= expires_at)
            THEN NOW() + frequency
        ELSE next_run_at
    END,
    last_run_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CompleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeTask, id)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    batch_id,
    kind,
    source_type,
    source_abbr,
    url,
    payload,
    payload_hash,
    meta,
    trace_id,
    frequency,
    next_run_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    COALESCE($11, NOW()),
    $12
)
RETURNING id, batch_id, kind, source_type, source_abbr, url, payload, payload_hash, meta, trace_id, frequency, next_run_at, expires_at, status, retry_count, last_run_at, created_at, updated_at
`

type CreateTaskParams struct {
	BatchID     uuid.UUID          `db:"batch_id" json:"batch_id"`
	Kind        TaskKind           `db:"kind" json:"kind"`
	SourceType  SourceType         `db:"source_type" json:"source_type"`
	SourceAbbr  string             `db:"source_abbr" json:"source_abbr"`
	Url         string             `db:"url" json:"url"`
	Payload     []byte             `db:"payload" json:"payload"`
	PayloadHash pgtype.Text        `db:"payload_hash" json:"payload_hash"`
	Meta        []byte             `db:"meta" json:"meta"`
	TraceID     string             `db:"trace_id" json:"trace_id"`
	Frequency   pgtype.Interval    `db:"frequency" json:"frequency"`
	NextRunAt   interface{}        `db:"next_run_at" json:"next_run_at"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.BatchID,
		arg.Kind,
		arg.SourceType,
		arg.SourceAbbr,
		arg.Url,
		arg.Payload,
		arg.PayloadHash,
		arg.Meta,
		arg.TraceID,
		arg.Frequency,
		arg.NextRunAt,
		arg.ExpiresAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Kind,
		&i.SourceType,
		&i.SourceAbbr,
		&i.Url,
		&i.Payload,
		&i.PayloadHash,
		&i.Meta,
		&i.TraceID,
		&i.Frequency,
		&i.NextRunAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RetryCount,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureBatchExists = `-- name: EnsureBatchExists :exec
INSERT INTO batches (id, source_type, trace_id)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type EnsureBatchExistsParams struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	SourceType SourceType  `db:"source_type" json:"source_type"`
	TraceID    pgtype.Text `db:"trace_id" json:"trace_id"`
}

func (q *Queries) EnsureBatchExists(ctx context.Context, arg EnsureBatchExistsParams) error {
	_, err := q.db.Exec(ctx, ensureBatchExists, arg.ID, arg.SourceType, arg.TraceID)
	return err
}

const extendActiveTaskExpiry = `-- name: ExtendActiveTaskExpiry :exec
UPDATE tasks
SET expires_at = $1,
    updated_at = NOW()
WHERE source_abbr    = $2
  AND kind         = $3
  AND payload_hash = $4
  AND status IN ('PENDING', 'RUNNING')
`

type ExtendActiveTaskExpiryParams struct {
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	SourceAbbr  string             `db:"source_abbr" json:"source_abbr"`
	Kind        TaskKind           `db:"kind" json:"kind"`
	PayloadHash pgtype.Text        `db:"payload_hash" json:"payload_hash"`
}

// Updates expires_at on an existing PENDING/RUNNING task identified by its dedup key.
// Used when CreateTask returns ErrTaskAlreadyActive to refresh the task's lifetime.
func (q *Queries) ExtendActiveTaskExpiry(ctx context.Context, arg ExtendActiveTaskExpiryParams) error {
	_, err := q.db.Exec(ctx, extendActiveTaskExpiry,
		arg.ExpiresAt,
		arg.SourceAbbr,
		arg.Kind,
		arg.PayloadHash,
	)
	return err
}

const failTask = `-- name: FailTask :exec
UPDATE tasks
SET status = 'FAILED',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) FailTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, failTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, batch_id, kind, source_type, source_abbr, url, payload, payload_hash, meta, trace_id, frequency, next_run_at, expires_at, status, retry_count, last_run_at, created_at, updated_at
FROM tasks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Kind,
		&i.SourceType,
		&i.SourceAbbr,
		&i.Url,
		&i.Payload,
		&i.PayloadHash,
		&i.Meta,
		&i.TraceID,
		&i.Frequency,
		&i.NextRunAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RetryCount,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunnableTasks = `-- name: ListRunnableTasks :many
SELECT id, batch_id, kind, source_type, source_abbr, url, payload, payload_hash, meta, trace_id, frequency, next_run_at, expires_at, status, retry_count, last_run_at, created_at, updated_at
FROM tasks
WHERE (
        status = 'PENDING'
    AND next_run_at <= NOW()
    AND (expires_at IS NULL OR expires_at > NOW())
) OR (
        status = 'RUNNING'
    AND last_run_at < NOW() - INTERVAL '30 minutes'
    AND (expires_at IS NULL OR expires_at > NOW())
)
ORDER BY next_run_at ASC, created_at ASC
LIMIT $1
`

func (q *Queries) ListRunnableTasks(ctx context.Context, limit int32) ([]Task, error) {
	rows, err := q.db.Query(ctx, listRunnableTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Kind,
			&i.SourceType,
			&i.SourceAbbr,
			&i.Url,
			&i.Payload,
			&i.PayloadHash,
			&i.Meta,
			&i.TraceID,
			&i.Frequency,
			&i.NextRunAt,
			&i.ExpiresAt,
			&i.Status,
			&i.RetryCount,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByBatchID = `-- name: ListTasksByBatchID :many
SELECT id, batch_id, kind, source_type, source_abbr, url, payload, payload_hash, meta, trace_id, frequency, next_run_at, expires_at, status, retry_count, last_run_at, created_at, updated_at
FROM tasks
WHERE batch_id = $1
ORDER BY created_at ASC, next_run_at ASC
`

func (q *Queries) ListTasksByBatchID(ctx context.Context, batchID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByBatchID, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Kind,
			&i.SourceType,
			&i.SourceAbbr,
			&i.Url,
			&i.Payload,
			&i.PayloadHash,
			&i.Meta,
			&i.TraceID,
			&i.Frequency,
			&i.NextRunAt,
			&i.ExpiresAt,
			&i.Status,
			&i.RetryCount,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTasks = `-- name: ReleaseTasks :exec
UPDATE tasks
SET status      = 'PENDING',
    retry_count = GREATEST(retry_count - 1, 0),
    next_run_at = NOW() + INTERVAL '3 seconds',
    updated_at  = NOW()
WHERE id = ANY($1::uuid[])
  AND status = 'RUNNING'
`

// Resets RUNNING tasks back to PENDING in bulk, undoing the ClaimTasks
// retry_count increment. Used when dispatch is skipped (e.g. rate-limited)
// so tasks are retried on the next scheduler tick without consuming retry slots.
func (q *Queries) ReleaseTasks(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseTasks, ids)
	return err
}
