// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_fetches.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserFetch = `-- name: CreateUserFetch :one
INSERT INTO fetches (user_id)
VALUES ($1)
RETURNING id, user_id, created_at, completed_at
`

func (q *Queries) CreateUserFetch(ctx context.Context, userID pgtype.UUID) (Fetch, error) {
	row := q.db.QueryRow(ctx, createUserFetch, userID)
	var i Fetch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createUserFetchItem = `-- name: CreateUserFetchItem :one
INSERT INTO fetch_items (
    fetch_id,
    candidate_id,
    task_id,
    snapshot_status
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING fetch_id, candidate_id, task_id, snapshot_status, created_at
`

type CreateUserFetchItemParams struct {
	FetchID        uuid.UUID   `db:"fetch_id" json:"fetch_id"`
	CandidateID    uuid.UUID   `db:"candidate_id" json:"candidate_id"`
	TaskID         pgtype.UUID `db:"task_id" json:"task_id"`
	SnapshotStatus pgtype.Text `db:"snapshot_status" json:"snapshot_status"`
}

func (q *Queries) CreateUserFetchItem(ctx context.Context, arg CreateUserFetchItemParams) (FetchItem, error) {
	row := q.db.QueryRow(ctx, createUserFetchItem,
		arg.FetchID,
		arg.CandidateID,
		arg.TaskID,
		arg.SnapshotStatus,
	)
	var i FetchItem
	err := row.Scan(
		&i.FetchID,
		&i.CandidateID,
		&i.TaskID,
		&i.SnapshotStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePageFetchTaskByURL = `-- name: GetActivePageFetchTaskByURL :one
SELECT id, batch_id, kind, source_type, source_abbr, url, payload, payload_hash, meta, trace_id, frequency, next_run_at, expires_at, status, retry_count, last_run_at, created_at, updated_at
FROM tasks
WHERE kind = 'PAGE_FETCH'
  AND url = $1
  AND status IN ('PENDING', 'RUNNING')
LIMIT 1
`

// Companion to CreateTask's ON CONFLICT path. When CreateTask reports the
// duplicate-active conflict, callers use this to recover the existing task's
// id without an extra round-trip. Returns the row that owns the
// uq_tasks_active_page_fetch index slot.
func (q *Queries) GetActivePageFetchTaskByURL(ctx context.Context, url string) (Task, error) {
	row := q.db.QueryRow(ctx, getActivePageFetchTaskByURL, url)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Kind,
		&i.SourceType,
		&i.SourceAbbr,
		&i.Url,
		&i.Payload,
		&i.PayloadHash,
		&i.Meta,
		&i.TraceID,
		&i.Frequency,
		&i.NextRunAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RetryCount,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFetch = `-- name: GetUserFetch :one
SELECT id, user_id, created_at, completed_at
FROM fetches
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserFetch(ctx context.Context, id uuid.UUID) (Fetch, error) {
	row := q.db.QueryRow(ctx, getUserFetch, id)
	var i Fetch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUserFetchProgress = `-- name: GetUserFetchProgress :one
WITH resolved AS (
    SELECT
        COALESCE(i.snapshot_status, t.status::text) AS status
    FROM fetch_items i
    LEFT JOIN tasks t ON t.id = i.task_id
    WHERE i.fetch_id = $1
)
SELECT
    COUNT(*)                                                                   AS total,
    COUNT(*) FILTER (WHERE status = 'PENDING')                                 AS pending,
    COUNT(*) FILTER (WHERE status = 'RUNNING')                                 AS running,
    COUNT(*) FILTER (WHERE status = 'COMPLETED')                               AS completed,
    COUNT(*) FILTER (WHERE status = 'FAILED')                                  AS failed,
    COUNT(*) FILTER (WHERE status = 'ALREADY_COMPLETE')                        AS already_complete,
    (COUNT(*) > 0 AND COUNT(*) FILTER (
        WHERE status IN ('COMPLETED', 'FAILED', 'ALREADY_COMPLETE')
    ) = COUNT(*))                                                              AS terminal
FROM resolved
`

type GetUserFetchProgressRow struct {
	Total           int64       `db:"total" json:"total"`
	Pending         int64       `db:"pending" json:"pending"`
	Running         int64       `db:"running" json:"running"`
	Completed       int64       `db:"completed" json:"completed"`
	Failed          int64       `db:"failed" json:"failed"`
	AlreadyComplete int64       `db:"already_complete" json:"already_complete"`
	Terminal        pgtype.Bool `db:"terminal" json:"terminal"`
}

// Aggregates item status using COALESCE(snapshot_status, tasks.status).
// Returns counters plus a derived `terminal` flag (all items in COMPLETED /
// FAILED / ALREADY_COMPLETE).
func (q *Queries) GetUserFetchProgress(ctx context.Context, fetchID uuid.UUID) (GetUserFetchProgressRow, error) {
	row := q.db.QueryRow(ctx, getUserFetchProgress, fetchID)
	var i GetUserFetchProgressRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Running,
		&i.Completed,
		&i.Failed,
		&i.AlreadyComplete,
		&i.Terminal,
	)
	return i, err
}

const listUserFetchItems = `-- name: ListUserFetchItems :many
SELECT
    i.fetch_id,
    i.candidate_id,
    i.task_id,
    i.snapshot_status,
    i.created_at,
    t.status AS task_status
FROM fetch_items i
LEFT JOIN tasks t ON t.id = i.task_id
WHERE i.fetch_id = $1
ORDER BY i.created_at ASC
`

type ListUserFetchItemsRow struct {
	FetchID        uuid.UUID          `db:"fetch_id" json:"fetch_id"`
	CandidateID    uuid.UUID          `db:"candidate_id" json:"candidate_id"`
	TaskID         pgtype.UUID        `db:"task_id" json:"task_id"`
	SnapshotStatus pgtype.Text        `db:"snapshot_status" json:"snapshot_status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	TaskStatus     NullTaskStatus     `db:"task_status" json:"task_status"`
}

func (q *Queries) ListUserFetchItems(ctx context.Context, fetchID uuid.UUID) ([]ListUserFetchItemsRow, error) {
	rows, err := q.db.Query(ctx, listUserFetchItems, fetchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserFetchItemsRow
	for rows.Next() {
		var i ListUserFetchItemsRow
		if err := rows.Scan(
			&i.FetchID,
			&i.CandidateID,
			&i.TaskID,
			&i.SnapshotStatus,
			&i.CreatedAt,
			&i.TaskStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserFetchCompleted = `-- name: MarkUserFetchCompleted :exec
UPDATE fetches
SET completed_at = NOW()
WHERE id = $1
  AND completed_at IS NULL
`

// Sets completed_at on transition to terminal. Idempotent (WHERE clause
// guards against double-set). v1 callers may skip this — progress endpoint
// computes terminal on-the-fly. Reserved for v2 notification dispatcher.
func (q *Queries) MarkUserFetchCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserFetchCompleted, id)
	return err
}
