// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_fetches.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserFetch = `-- name: CreateUserFetch :one
INSERT INTO fetches (user_id)
VALUES ($1)
RETURNING id, user_id, created_at, completed_at
`

func (q *Queries) CreateUserFetch(ctx context.Context, userID pgtype.UUID) (Fetch, error) {
	row := q.db.QueryRow(ctx, createUserFetch, userID)
	var i Fetch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createUserFetchItem = `-- name: CreateUserFetchItem :one
INSERT INTO fetch_items (
    fetch_id,
    candidate_id,
    task_id,
    snapshot_status
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING fetch_id, candidate_id, task_id, snapshot_status, created_at
`

type CreateUserFetchItemParams struct {
	FetchID        uuid.UUID   `db:"fetch_id" json:"fetch_id"`
	CandidateID    uuid.UUID   `db:"candidate_id" json:"candidate_id"`
	TaskID         pgtype.UUID `db:"task_id" json:"task_id"`
	SnapshotStatus pgtype.Text `db:"snapshot_status" json:"snapshot_status"`
}

func (q *Queries) CreateUserFetchItem(ctx context.Context, arg CreateUserFetchItemParams) (FetchItem, error) {
	row := q.db.QueryRow(ctx, createUserFetchItem,
		arg.FetchID,
		arg.CandidateID,
		arg.TaskID,
		arg.SnapshotStatus,
	)
	var i FetchItem
	err := row.Scan(
		&i.FetchID,
		&i.CandidateID,
		&i.TaskID,
		&i.SnapshotStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getUserFetch = `-- name: GetUserFetch :one
SELECT id, user_id, created_at, completed_at
FROM fetches
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserFetch(ctx context.Context, id uuid.UUID) (Fetch, error) {
	row := q.db.QueryRow(ctx, getUserFetch, id)
	var i Fetch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUserFetchProgress = `-- name: GetUserFetchProgress :one
WITH resolved AS (
    SELECT
        i.candidate_id,
        COALESCE(i.snapshot_status, t.status::text) AS status
    FROM fetch_items i
    LEFT JOIN tasks t ON t.id = i.task_id
    WHERE i.fetch_id = $1
)
SELECT
    (SELECT COUNT(*) FROM resolved)                                            AS total,
    ARRAY(
        SELECT candidate_id FROM resolved
        WHERE status = 'PENDING'
        ORDER BY candidate_id
    )::uuid[]                                                                  AS pending_candidate_ids,
    ARRAY(
        SELECT candidate_id FROM resolved
        WHERE status = 'RUNNING'
        ORDER BY candidate_id
    )::uuid[]                                                                  AS running_candidate_ids,
    ARRAY(
        SELECT candidate_id FROM resolved
        WHERE status = 'COMPLETED'
        ORDER BY candidate_id
    )::uuid[]                                                                  AS completed_candidate_ids,
    ARRAY(
        SELECT candidate_id FROM resolved
        WHERE status = 'FAILED'
        ORDER BY candidate_id
    )::uuid[]                                                                  AS failed_candidate_ids,
    ARRAY(
        SELECT candidate_id FROM resolved
        WHERE status = 'ALREADY_COMPLETE'
        ORDER BY candidate_id
    )::uuid[]                                                                  AS already_complete_candidate_ids,
    ((SELECT COUNT(*) FROM resolved) > 0 AND (SELECT COUNT(*) FROM resolved
        WHERE status IN ('COMPLETED', 'FAILED', 'ALREADY_COMPLETE')
    ) = (SELECT COUNT(*) FROM resolved))                                        AS terminal
`

type GetUserFetchProgressRow struct {
	Total                       int64       `db:"total" json:"total"`
	PendingCandidateIds         []uuid.UUID `db:"pending_candidate_ids" json:"pending_candidate_ids"`
	RunningCandidateIds         []uuid.UUID `db:"running_candidate_ids" json:"running_candidate_ids"`
	CompletedCandidateIds       []uuid.UUID `db:"completed_candidate_ids" json:"completed_candidate_ids"`
	FailedCandidateIds          []uuid.UUID `db:"failed_candidate_ids" json:"failed_candidate_ids"`
	AlreadyCompleteCandidateIds []uuid.UUID `db:"already_complete_candidate_ids" json:"already_complete_candidate_ids"`
	Terminal                    pgtype.Bool `db:"terminal" json:"terminal"`
}

// Aggregates item status using COALESCE(snapshot_status, tasks.status).
// Returns candidate IDs grouped by status plus a derived `terminal` flag (all
// items in COMPLETED / FAILED / ALREADY_COMPLETE).
func (q *Queries) GetUserFetchProgress(ctx context.Context, fetchID uuid.UUID) (GetUserFetchProgressRow, error) {
	row := q.db.QueryRow(ctx, getUserFetchProgress, fetchID)
	var i GetUserFetchProgressRow
	err := row.Scan(
		&i.Total,
		&i.PendingCandidateIds,
		&i.RunningCandidateIds,
		&i.CompletedCandidateIds,
		&i.FailedCandidateIds,
		&i.AlreadyCompleteCandidateIds,
		&i.Terminal,
	)
	return i, err
}

const listUserFetchItems = `-- name: ListUserFetchItems :many
SELECT
    i.fetch_id,
    i.candidate_id,
    i.task_id,
    i.snapshot_status,
    i.created_at,
    t.status AS task_status
FROM fetch_items i
LEFT JOIN tasks t ON t.id = i.task_id
WHERE i.fetch_id = $1
ORDER BY i.created_at ASC
`

type ListUserFetchItemsRow struct {
	FetchID        uuid.UUID          `db:"fetch_id" json:"fetch_id"`
	CandidateID    uuid.UUID          `db:"candidate_id" json:"candidate_id"`
	TaskID         pgtype.UUID        `db:"task_id" json:"task_id"`
	SnapshotStatus pgtype.Text        `db:"snapshot_status" json:"snapshot_status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	TaskStatus     NullTaskStatus     `db:"task_status" json:"task_status"`
}

func (q *Queries) ListUserFetchItems(ctx context.Context, fetchID uuid.UUID) ([]ListUserFetchItemsRow, error) {
	rows, err := q.db.Query(ctx, listUserFetchItems, fetchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserFetchItemsRow
	for rows.Next() {
		var i ListUserFetchItemsRow
		if err := rows.Scan(
			&i.FetchID,
			&i.CandidateID,
			&i.TaskID,
			&i.SnapshotStatus,
			&i.CreatedAt,
			&i.TaskStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserFetchCompleted = `-- name: MarkUserFetchCompleted :exec
UPDATE fetches
SET completed_at = NOW()
WHERE id = $1
  AND completed_at IS NULL
`

// Sets completed_at on transition to terminal. Idempotent (WHERE clause
// guards against double-set). v1 callers may skip this — progress endpoint
// computes terminal on-the-fly. Reserved for v2 notification dispatcher.
func (q *Queries) MarkUserFetchCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserFetchCompleted, id)
	return err
}
