// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_fetches.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserFetchRequest = `-- name: CreateUserFetchRequest :one
INSERT INTO user_fetch_requests (user_id)
VALUES ($1)
RETURNING id, user_id, created_at, completed_at
`

func (q *Queries) CreateUserFetchRequest(ctx context.Context, userID pgtype.UUID) (UserFetchRequest, error) {
	row := q.db.QueryRow(ctx, createUserFetchRequest, userID)
	var i UserFetchRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createUserFetchRequestItem = `-- name: CreateUserFetchRequestItem :one
INSERT INTO user_fetch_request_items (
    request_id,
    candidate_id,
    task_id,
    snapshot_status
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING request_id, candidate_id, task_id, snapshot_status, created_at
`

type CreateUserFetchRequestItemParams struct {
	RequestID      uuid.UUID   `db:"request_id" json:"request_id"`
	CandidateID    uuid.UUID   `db:"candidate_id" json:"candidate_id"`
	TaskID         pgtype.UUID `db:"task_id" json:"task_id"`
	SnapshotStatus pgtype.Text `db:"snapshot_status" json:"snapshot_status"`
}

func (q *Queries) CreateUserFetchRequestItem(ctx context.Context, arg CreateUserFetchRequestItemParams) (UserFetchRequestItem, error) {
	row := q.db.QueryRow(ctx, createUserFetchRequestItem,
		arg.RequestID,
		arg.CandidateID,
		arg.TaskID,
		arg.SnapshotStatus,
	)
	var i UserFetchRequestItem
	err := row.Scan(
		&i.RequestID,
		&i.CandidateID,
		&i.TaskID,
		&i.SnapshotStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePageFetchTaskByURL = `-- name: GetActivePageFetchTaskByURL :one
SELECT id, batch_id, kind, source_type, source_abbr, url, payload, payload_hash, meta, trace_id, frequency, next_run_at, expires_at, status, retry_count, last_run_at, created_at, updated_at
FROM tasks
WHERE kind = 'PAGE_FETCH'
  AND url = $1
  AND status IN ('PENDING', 'RUNNING')
LIMIT 1
`

// Companion to CreateTask's ON CONFLICT path. When CreateTask reports the
// duplicate-active conflict, callers use this to recover the existing task's
// id without an extra round-trip. Returns the row that owns the
// uq_tasks_active_page_fetch index slot.
func (q *Queries) GetActivePageFetchTaskByURL(ctx context.Context, url string) (Task, error) {
	row := q.db.QueryRow(ctx, getActivePageFetchTaskByURL, url)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Kind,
		&i.SourceType,
		&i.SourceAbbr,
		&i.Url,
		&i.Payload,
		&i.PayloadHash,
		&i.Meta,
		&i.TraceID,
		&i.Frequency,
		&i.NextRunAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RetryCount,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFetchRequest = `-- name: GetUserFetchRequest :one
SELECT id, user_id, created_at, completed_at
FROM user_fetch_requests
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserFetchRequest(ctx context.Context, id uuid.UUID) (UserFetchRequest, error) {
	row := q.db.QueryRow(ctx, getUserFetchRequest, id)
	var i UserFetchRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUserFetchRequestProgress = `-- name: GetUserFetchRequestProgress :one
WITH resolved AS (
    SELECT
        COALESCE(i.snapshot_status, t.status::text) AS status
    FROM user_fetch_request_items i
    LEFT JOIN tasks t ON t.id = i.task_id
    WHERE i.request_id = $1
)
SELECT
    COUNT(*)                                                                   AS total,
    COUNT(*) FILTER (WHERE status = 'PENDING')                                 AS pending,
    COUNT(*) FILTER (WHERE status = 'RUNNING')                                 AS running,
    COUNT(*) FILTER (WHERE status = 'COMPLETED')                               AS completed,
    COUNT(*) FILTER (WHERE status = 'FAILED')                                  AS failed,
    COUNT(*) FILTER (WHERE status = 'ALREADY_COMPLETE')                        AS already_complete,
    (COUNT(*) > 0 AND COUNT(*) FILTER (
        WHERE status IN ('COMPLETED', 'FAILED', 'ALREADY_COMPLETE')
    ) = COUNT(*))                                                              AS terminal
FROM resolved
`

type GetUserFetchRequestProgressRow struct {
	Total           int64       `db:"total" json:"total"`
	Pending         int64       `db:"pending" json:"pending"`
	Running         int64       `db:"running" json:"running"`
	Completed       int64       `db:"completed" json:"completed"`
	Failed          int64       `db:"failed" json:"failed"`
	AlreadyComplete int64       `db:"already_complete" json:"already_complete"`
	Terminal        pgtype.Bool `db:"terminal" json:"terminal"`
}

// Aggregates item status using COALESCE(snapshot_status, tasks.status).
// Returns counters plus a derived `terminal` flag (all items in COMPLETED /
// FAILED / ALREADY_COMPLETE).
func (q *Queries) GetUserFetchRequestProgress(ctx context.Context, requestID uuid.UUID) (GetUserFetchRequestProgressRow, error) {
	row := q.db.QueryRow(ctx, getUserFetchRequestProgress, requestID)
	var i GetUserFetchRequestProgressRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Running,
		&i.Completed,
		&i.Failed,
		&i.AlreadyComplete,
		&i.Terminal,
	)
	return i, err
}

const listUserFetchRequestItems = `-- name: ListUserFetchRequestItems :many
SELECT
    i.request_id,
    i.candidate_id,
    i.task_id,
    i.snapshot_status,
    i.created_at,
    t.status AS task_status
FROM user_fetch_request_items i
LEFT JOIN tasks t ON t.id = i.task_id
WHERE i.request_id = $1
ORDER BY i.created_at ASC
`

type ListUserFetchRequestItemsRow struct {
	RequestID      uuid.UUID          `db:"request_id" json:"request_id"`
	CandidateID    uuid.UUID          `db:"candidate_id" json:"candidate_id"`
	TaskID         pgtype.UUID        `db:"task_id" json:"task_id"`
	SnapshotStatus pgtype.Text        `db:"snapshot_status" json:"snapshot_status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	TaskStatus     NullTaskStatus     `db:"task_status" json:"task_status"`
}

func (q *Queries) ListUserFetchRequestItems(ctx context.Context, requestID uuid.UUID) ([]ListUserFetchRequestItemsRow, error) {
	rows, err := q.db.Query(ctx, listUserFetchRequestItems, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserFetchRequestItemsRow
	for rows.Next() {
		var i ListUserFetchRequestItemsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.CandidateID,
			&i.TaskID,
			&i.SnapshotStatus,
			&i.CreatedAt,
			&i.TaskStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserFetchRequestCompleted = `-- name: MarkUserFetchRequestCompleted :exec
UPDATE user_fetch_requests
SET completed_at = NOW()
WHERE id = $1
  AND completed_at IS NULL
`

// Sets completed_at on transition to terminal. Idempotent (WHERE clause
// guards against double-set). v1 callers may skip this — progress endpoint
// computes terminal on-the-fly. Reserved for v2 notification dispatcher.
func (q *Queries) MarkUserFetchRequestCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserFetchRequestCompleted, id)
	return err
}
