// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSink creates a new instance of MockSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSink {
	mock := &MockSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSink is an autogenerated mock type for the Sink type
type MockSink struct {
	mock.Mock
}

type MockSink_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSink) EXPECT() *MockSink_Expecter {
	return &MockSink_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockSink
func (_mock *MockSink) Handle(ctx context.Context, sourceURL string, candidates []model.Candidates) error {
	ret := _mock.Called(ctx, sourceURL, candidates)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []model.Candidates) error); ok {
		r0 = returnFunc(ctx, sourceURL, candidates)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSink_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockSink_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceURL string
//   - candidates []model.Candidates
func (_e *MockSink_Expecter) Handle(ctx interface{}, sourceURL interface{}, candidates interface{}) *MockSink_Handle_Call {
	return &MockSink_Handle_Call{Call: _e.mock.On("Handle", ctx, sourceURL, candidates)}
}

func (_c *MockSink_Handle_Call) Run(run func(ctx context.Context, sourceURL string, candidates []model.Candidates)) *MockSink_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []model.Candidates
		if args[2] != nil {
			arg2 = args[2].([]model.Candidates)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSink_Handle_Call) Return(err error) *MockSink_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSink_Handle_Call) RunAndReturn(run func(ctx context.Context, sourceURL string, candidates []model.Candidates) error) *MockSink_Handle_Call {
	_c.Call.Return(run)
	return _c
}
