version: 1

parsers:
  www.dpp.org.tw:
    enabled: true
    jsonld: false
    date_layouts:
      - "2006-01-02"
    html:
      title:
        - "article.news_content h2"
      date:
        - "p.news_content_date"
      content:
        - "#media_contents p"

  www.tpp.org.tw:
    enabled: true
    jsonld: false
    date_layouts:
      - "2006/01/02"
    html:
      title:
        - "div.content_topic"
      date:
        - "span.content_date"
      content:
        - "div.content_description"

  www.kmt.org.tw:
    enabled: true
    jsonld: false
    date_layouts:
      - "2006-01-02T15:04:05-07:00"
    html:
      title:
        - "#div1 h3"
      date:
        - "#div1 div.post-footer-line i.pdt abbr.published@title"
      content:
        - "#div1 div.post-body p"

  tw.news.yahoo.com:
    enabled: true
    jsonld: true # Yahoo has excellent JSON-LD
    html:
      content:
        - ".caas-body"
