#!/usr/bin/env bash
#
# Bake credentials from .secrets/* into env/local/<ENV>.local.env so the
# Taskfile dotenv layering picks them up. The output file is gitignored;
# never commit it.
#
# Usage:
#   ENV=test ./script/secrets-bake.sh
#   ENV=e2e  ./script/secrets-bake.sh
#
# Hardening:
#   - umask 077 so any temp file is owner-only.
#   - Atomic write via mktemp + mv (no half-written file readable).
#   - Final chmod 0600 on the output.
#   - Refuses ENV=prod: prod credentials must come from the deployment
#     platform (k8s secret / Docker swarm secret / AWS Secrets Manager),
#     never from .secrets/ in this repo.
#   - Refuses tokens containing chars that would break dotenv parsing
#     ($, ", \, CR, LF) — current rotation produces hex tokens, but a
#     future rotation that hand-edits .secrets/* could otherwise corrupt
#     the layered file or smuggle YAML.

set -euo pipefail
umask 077

ENV="${ENV:-test}"
SECRETS_DIR=".secrets"
OUT_DIR="env/local"
OUT="${OUT_DIR}/${ENV}.local.env"

case "$ENV" in
    test|e2e) ;;
    prod)
        echo "ENV=prod refused: prod secrets come from the deployment platform, not .secrets/." >&2
        exit 1
        ;;
    *)
        echo "ENV must be one of test|e2e|prod, got: $ENV" >&2
        exit 1
        ;;
esac

if [ ! -d "$SECRETS_DIR" ]; then
    echo "$SECRETS_DIR missing — run from repo root" >&2
    exit 1
fi

mkdir -p "$OUT_DIR"

# Map .secrets/<file> → env-var name. Add new entries here when a new
# .secrets/<file> needs to ship into the env layer.
declare -a MAP=(
    "valkey_prism:VALKEY_APP_PASSWORD"
)

tmp="$(mktemp "${OUT_DIR}/.bake.${ENV}.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

{
    printf '# Generated by script/secrets-bake.sh ENV=%s on %s\n' \
        "$ENV" "$(date -Iseconds)"
    printf '# DO NOT COMMIT. chmod 0600. Regenerate via the script above.\n'
    printf '# === bake-managed ===\n'
    for entry in "${MAP[@]}"; do
        src_name="${entry%%:*}"
        var_name="${entry##*:}"
        src="$SECRETS_DIR/$src_name"
        if [ ! -f "$src" ]; then
            echo "missing $src" >&2
            exit 1
        fi
        val="$(tr -d '\r\n' < "$src")"
        case "$val" in
            *\$*|*\"*|*\\*|*$'\n'*|*$'\r'*)
                echo "secret $src contains forbidden chars (\$, \", \\, CR, LF)" >&2
                exit 1
                ;;
        esac
        printf '%s=%s\n' "$var_name" "$val"
    done
} > "$tmp"

chmod 0600 "$tmp"
mv "$tmp" "$OUT"
trap - EXIT
echo "wrote $OUT"
