// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/discovery"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBackfiller creates a new instance of MockBackfiller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackfiller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackfiller {
	mock := &MockBackfiller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackfiller is an autogenerated mock type for the Backfiller type
type MockBackfiller struct {
	mock.Mock
}

type MockBackfiller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackfiller) EXPECT() *MockBackfiller_Expecter {
	return &MockBackfiller_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockBackfiller
func (_mock *MockBackfiller) Run(ctx context.Context, req discovery.BackfillRequest) (discovery.BackfillResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 discovery.BackfillResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, discovery.BackfillRequest) (discovery.BackfillResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, discovery.BackfillRequest) discovery.BackfillResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(discovery.BackfillResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, discovery.BackfillRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackfiller_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockBackfiller_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - req discovery.BackfillRequest
func (_e *MockBackfiller_Expecter) Run(ctx interface{}, req interface{}) *MockBackfiller_Run_Call {
	return &MockBackfiller_Run_Call{Call: _e.mock.On("Run", ctx, req)}
}

func (_c *MockBackfiller_Run_Call) Run(run func(ctx context.Context, req discovery.BackfillRequest)) *MockBackfiller_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 discovery.BackfillRequest
		if args[1] != nil {
			arg1 = args[1].(discovery.BackfillRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackfiller_Run_Call) Return(backfillResult discovery.BackfillResult, err error) *MockBackfiller_Run_Call {
	_c.Call.Return(backfillResult, err)
	return _c
}

func (_c *MockBackfiller_Run_Call) RunAndReturn(run func(ctx context.Context, req discovery.BackfillRequest) (discovery.BackfillResult, error)) *MockBackfiller_Run_Call {
	_c.Call.Return(run)
	return _c
}
