// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/discovery"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlanner creates a new instance of MockPlanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlanner {
	mock := &MockPlanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlanner is an autogenerated mock type for the Planner type
type MockPlanner struct {
	mock.Mock
}

type MockPlanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlanner) EXPECT() *MockPlanner_Expecter {
	return &MockPlanner_Expecter{mock: &_m.Mock}
}

// Plan provides a mock function for the type MockPlanner
func (_mock *MockPlanner) Plan(ctx context.Context, req discovery.PlannerRequest) (discovery.PlannerResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Plan")
	}

	var r0 discovery.PlannerResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, discovery.PlannerRequest) (discovery.PlannerResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, discovery.PlannerRequest) discovery.PlannerResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(discovery.PlannerResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, discovery.PlannerRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanner_Plan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Plan'
type MockPlanner_Plan_Call struct {
	*mock.Call
}

// Plan is a helper method to define mock.On call
//   - ctx context.Context
//   - req discovery.PlannerRequest
func (_e *MockPlanner_Expecter) Plan(ctx interface{}, req interface{}) *MockPlanner_Plan_Call {
	return &MockPlanner_Plan_Call{Call: _e.mock.On("Plan", ctx, req)}
}

func (_c *MockPlanner_Plan_Call) Run(run func(ctx context.Context, req discovery.PlannerRequest)) *MockPlanner_Plan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 discovery.PlannerRequest
		if args[1] != nil {
			arg1 = args[1].(discovery.PlannerRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlanner_Plan_Call) Return(plannerResult discovery.PlannerResult, err error) *MockPlanner_Plan_Call {
	_c.Call.Return(plannerResult, err)
	return _c
}

func (_c *MockPlanner_Plan_Call) RunAndReturn(run func(ctx context.Context, req discovery.PlannerRequest) (discovery.PlannerResult, error)) *MockPlanner_Plan_Call {
	_c.Call.Return(run)
	return _c
}
