// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSearchClient creates a new instance of MockSearchClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchClient {
	mock := &MockSearchClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearchClient is an autogenerated mock type for the SearchClient type
type MockSearchClient struct {
	mock.Mock
}

type MockSearchClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchClient) EXPECT() *MockSearchClient_Expecter {
	return &MockSearchClient_Expecter{mock: &_m.Mock}
}

// DiscoverNews provides a mock function for the type MockSearchClient
func (_mock *MockSearchClient) DiscoverNews(ctx context.Context, query string, site string) ([]model.Candidates, error) {
	ret := _mock.Called(ctx, query, site)

	if len(ret) == 0 {
		panic("no return value specified for DiscoverNews")
	}

	var r0 []model.Candidates
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Candidates, error)); ok {
		return returnFunc(ctx, query, site)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []model.Candidates); ok {
		r0 = returnFunc(ctx, query, site)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Candidates)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, query, site)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchClient_DiscoverNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoverNews'
type MockSearchClient_DiscoverNews_Call struct {
	*mock.Call
}

// DiscoverNews is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - site string
func (_e *MockSearchClient_Expecter) DiscoverNews(ctx interface{}, query interface{}, site interface{}) *MockSearchClient_DiscoverNews_Call {
	return &MockSearchClient_DiscoverNews_Call{Call: _e.mock.On("DiscoverNews", ctx, query, site)}
}

func (_c *MockSearchClient_DiscoverNews_Call) Run(run func(ctx context.Context, query string, site string)) *MockSearchClient_DiscoverNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSearchClient_DiscoverNews_Call) Return(candidatess []model.Candidates, err error) *MockSearchClient_DiscoverNews_Call {
	_c.Call.Return(candidatess, err)
	return _c
}

func (_c *MockSearchClient_DiscoverNews_Call) RunAndReturn(run func(ctx context.Context, query string, site string) ([]model.Candidates, error)) *MockSearchClient_DiscoverNews_Call {
	_c.Call.Return(run)
	return _c
}
