// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/collector"
	mock "github.com/stretchr/testify/mock"
)

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockParser
func (_mock *MockParser) Parse(ctx context.Context, url string, data string) (*collector.Article, error) {
	ret := _mock.Called(ctx, url, data)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *collector.Article
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*collector.Article, error)); ok {
		return returnFunc(ctx, url, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *collector.Article); ok {
		r0 = returnFunc(ctx, url, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collector.Article)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, url, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - data string
func (_e *MockParser_Expecter) Parse(ctx interface{}, url interface{}, data interface{}) *MockParser_Parse_Call {
	return &MockParser_Parse_Call{Call: _e.mock.On("Parse", ctx, url, data)}
}

func (_c *MockParser_Parse_Call) Run(run func(ctx context.Context, url string, data string)) *MockParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockParser_Parse_Call) Return(article *collector.Article, err error) *MockParser_Parse_Call {
	_c.Call.Return(article, err)
	return _c
}

func (_c *MockParser_Parse_Call) RunAndReturn(run func(ctx context.Context, url string, data string) (*collector.Article, error)) *MockParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
