// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/analyzer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalyzer creates a new instance of MockAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyzer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyzer {
	mock := &MockAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalyzer is an autogenerated mock type for the Analyzer type
type MockAnalyzer struct {
	mock.Mock
}

type MockAnalyzer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyzer) EXPECT() *MockAnalyzer_Expecter {
	return &MockAnalyzer_Expecter{mock: &_m.Mock}
}

// EmbedArticle provides a mock function for the type MockAnalyzer
func (_mock *MockAnalyzer) EmbedArticle(ctx context.Context, title string, content string) ([]float32, error) {
	ret := _mock.Called(ctx, title, content)

	if len(ret) == 0 {
		panic("no return value specified for EmbedArticle")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]float32, error)); ok {
		return returnFunc(ctx, title, content)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []float32); ok {
		r0 = returnFunc(ctx, title, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, title, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyzer_EmbedArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedArticle'
type MockAnalyzer_EmbedArticle_Call struct {
	*mock.Call
}

// EmbedArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - content string
func (_e *MockAnalyzer_Expecter) EmbedArticle(ctx interface{}, title interface{}, content interface{}) *MockAnalyzer_EmbedArticle_Call {
	return &MockAnalyzer_EmbedArticle_Call{Call: _e.mock.On("EmbedArticle", ctx, title, content)}
}

func (_c *MockAnalyzer_EmbedArticle_Call) Run(run func(ctx context.Context, title string, content string)) *MockAnalyzer_EmbedArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyzer_EmbedArticle_Call) Return(float32s []float32, err error) *MockAnalyzer_EmbedArticle_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockAnalyzer_EmbedArticle_Call) RunAndReturn(run func(ctx context.Context, title string, content string) ([]float32, error)) *MockAnalyzer_EmbedArticle_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractTopic provides a mock function for the type MockAnalyzer
func (_mock *MockAnalyzer) ExtractTopic(ctx context.Context, in *analyzer.TopicExtractionInput) (*analyzer.TopicExtractionOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ExtractTopic")
	}

	var r0 *analyzer.TopicExtractionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *analyzer.TopicExtractionInput) (*analyzer.TopicExtractionOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *analyzer.TopicExtractionInput) *analyzer.TopicExtractionOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*analyzer.TopicExtractionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *analyzer.TopicExtractionInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyzer_ExtractTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractTopic'
type MockAnalyzer_ExtractTopic_Call struct {
	*mock.Call
}

// ExtractTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - in *analyzer.TopicExtractionInput
func (_e *MockAnalyzer_Expecter) ExtractTopic(ctx interface{}, in interface{}) *MockAnalyzer_ExtractTopic_Call {
	return &MockAnalyzer_ExtractTopic_Call{Call: _e.mock.On("ExtractTopic", ctx, in)}
}

func (_c *MockAnalyzer_ExtractTopic_Call) Run(run func(ctx context.Context, in *analyzer.TopicExtractionInput)) *MockAnalyzer_ExtractTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *analyzer.TopicExtractionInput
		if args[1] != nil {
			arg1 = args[1].(*analyzer.TopicExtractionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyzer_ExtractTopic_Call) Return(topicExtractionOutput *analyzer.TopicExtractionOutput, err error) *MockAnalyzer_ExtractTopic_Call {
	_c.Call.Return(topicExtractionOutput, err)
	return _c
}

func (_c *MockAnalyzer_ExtractTopic_Call) RunAndReturn(run func(ctx context.Context, in *analyzer.TopicExtractionInput) (*analyzer.TopicExtractionOutput, error)) *MockAnalyzer_ExtractTopic_Call {
	_c.Call.Return(run)
	return _c
}

// ScoreStance provides a mock function for the type MockAnalyzer
func (_mock *MockAnalyzer) ScoreStance(ctx context.Context, in *analyzer.StanceScoringInput) (*analyzer.StanceScoringOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ScoreStance")
	}

	var r0 *analyzer.StanceScoringOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *analyzer.StanceScoringInput) (*analyzer.StanceScoringOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *analyzer.StanceScoringInput) *analyzer.StanceScoringOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*analyzer.StanceScoringOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *analyzer.StanceScoringInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyzer_ScoreStance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScoreStance'
type MockAnalyzer_ScoreStance_Call struct {
	*mock.Call
}

// ScoreStance is a helper method to define mock.On call
//   - ctx context.Context
//   - in *analyzer.StanceScoringInput
func (_e *MockAnalyzer_Expecter) ScoreStance(ctx interface{}, in interface{}) *MockAnalyzer_ScoreStance_Call {
	return &MockAnalyzer_ScoreStance_Call{Call: _e.mock.On("ScoreStance", ctx, in)}
}

func (_c *MockAnalyzer_ScoreStance_Call) Run(run func(ctx context.Context, in *analyzer.StanceScoringInput)) *MockAnalyzer_ScoreStance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *analyzer.StanceScoringInput
		if args[1] != nil {
			arg1 = args[1].(*analyzer.StanceScoringInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyzer_ScoreStance_Call) Return(stanceScoringOutput *analyzer.StanceScoringOutput, err error) *MockAnalyzer_ScoreStance_Call {
	_c.Call.Return(stanceScoringOutput, err)
	return _c
}

func (_c *MockAnalyzer_ScoreStance_Call) RunAndReturn(run func(ctx context.Context, in *analyzer.StanceScoringInput) (*analyzer.StanceScoringOutput, error)) *MockAnalyzer_ScoreStance_Call {
	_c.Call.Return(run)
	return _c
}
