// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ChiaYuChang/prism/internal/analyzer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStanceScorer creates a new instance of MockStanceScorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStanceScorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStanceScorer {
	mock := &MockStanceScorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStanceScorer is an autogenerated mock type for the StanceScorer type
type MockStanceScorer struct {
	mock.Mock
}

type MockStanceScorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStanceScorer) EXPECT() *MockStanceScorer_Expecter {
	return &MockStanceScorer_Expecter{mock: &_m.Mock}
}

// ScoreStance provides a mock function for the type MockStanceScorer
func (_mock *MockStanceScorer) ScoreStance(ctx context.Context, in *analyzer.StanceScoringInput) (*analyzer.StanceScoringOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ScoreStance")
	}

	var r0 *analyzer.StanceScoringOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *analyzer.StanceScoringInput) (*analyzer.StanceScoringOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *analyzer.StanceScoringInput) *analyzer.StanceScoringOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*analyzer.StanceScoringOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *analyzer.StanceScoringInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStanceScorer_ScoreStance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScoreStance'
type MockStanceScorer_ScoreStance_Call struct {
	*mock.Call
}

// ScoreStance is a helper method to define mock.On call
//   - ctx context.Context
//   - in *analyzer.StanceScoringInput
func (_e *MockStanceScorer_Expecter) ScoreStance(ctx interface{}, in interface{}) *MockStanceScorer_ScoreStance_Call {
	return &MockStanceScorer_ScoreStance_Call{Call: _e.mock.On("ScoreStance", ctx, in)}
}

func (_c *MockStanceScorer_ScoreStance_Call) Run(run func(ctx context.Context, in *analyzer.StanceScoringInput)) *MockStanceScorer_ScoreStance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *analyzer.StanceScoringInput
		if args[1] != nil {
			arg1 = args[1].(*analyzer.StanceScoringInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStanceScorer_ScoreStance_Call) Return(stanceScoringOutput *analyzer.StanceScoringOutput, err error) *MockStanceScorer_ScoreStance_Call {
	_c.Call.Return(stanceScoringOutput, err)
	return _c
}

func (_c *MockStanceScorer_ScoreStance_Call) RunAndReturn(run func(ctx context.Context, in *analyzer.StanceScoringInput) (*analyzer.StanceScoringOutput, error)) *MockStanceScorer_ScoreStance_Call {
	_c.Call.Return(run)
	return _c
}
